// Content for the landing page. Tokenized code strings are rendered with v-html.
// Keep any HTML below scoped to known-safe token spans (tok-*) — it is trusted
// authored content, not user input.

export interface IdeTab {
  id: string
  label: string
  filename: string
  iconClass: 'bpmn' | 'kt' | 'json'
  iconText: string
  paneType: 'image' | 'code'
  src?: string
  code?: string
  beta?: boolean
}

export const ideTabs: IdeTab[] = [
  {
    id: 'bpmn',
    label: 'bike-leasing.bpmn',
    filename: 'bike-leasing.bpmn',
    iconClass: 'bpmn',
    iconText: '\u25C7',
    paneType: 'image',
    src: 'bike-leasing.svg',
  },
  {
    id: 'api',
    label: 'BikeLeasingProcessApi.kt',
    filename: 'BikeLeasingProcessApi.kt',
    iconClass: 'kt',
    iconText: 'Kt',
    paneType: 'code',
    code: [
      `<span class="line"><span class="tok-c">// Generated by bpmn-to-code</span></span>`,
      `<span class="line"><span class="tok-k">object</span> <span class="tok-t">BikeLeasingProcessApi</span> {</span>`,
      `<span class="line">  <span class="tok-k">val</span> PROCESS_ID: <span class="tok-t">ProcessId</span> = <span class="tok-t">ProcessId</span>(<span class="tok-s">"bikeLeasing"</span>)</span>`,
      `<span class="line">  <span class="tok-k">val</span> PROCESS_ENGINE: <span class="tok-t">BpmnEngine</span> = <span class="tok-t">BpmnEngine</span>.ZEEBE</span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-k">object</span> <span class="tok-t">FlowNodes</span> {</span>`,
      `<span class="line">    <span class="tok-k">object</span> <span class="tok-t">ServiceTaskSendContract</span> : <span class="tok-t">AbstractFlowNode</span>(</span>`,
      `<span class="line">      id = <span class="tok-t">ElementId</span>(<span class="tok-t">ServiceTaskSendContract</span>.ELEMENT_ID),</span>`,
      `<span class="line">      elementType = <span class="tok-t">BpmnElementType</span>.SERVICE_TASK,</span>`,
      `<span class="line">      name = <span class="tok-s">"Send contract"</span>,</span>`,
      `<span class="line">    ), <span class="tok-t">HasSuccessors</span>&lt;<span class="tok-t">ServiceTaskSendContract</span>.<span class="tok-t">Next</span>&gt;, <span class="tok-t">HasJobType</span>, <span class="tok-t">HasVariables</span> {</span>`,
      `<span class="line">      <span class="tok-k">const val</span> ELEMENT_ID: <span class="tok-t">String</span> = <span class="tok-s">"serviceTask_sendContract"</span></span>`,
      `<span class="line">      <span class="tok-k">override val</span> jobType: <span class="tok-t">String</span> = <span class="tok-t">ServiceTasks</span>.MIRAVELO_SEND_CONTRACT</span>`,
      `<span class="line"> </span>`,
      `<span class="line">      <span class="tok-k">object</span> <span class="tok-t">Variables</span> : <span class="tok-t">RegisteredVariableDefinitions</span>() {</span>`,
      `<span class="line">        <span class="tok-k">val</span> APPLICATION_ID: <span class="tok-t">VariableName</span>.<span class="tok-t">Input</span> = input(<span class="tok-t">ProcessVariables</span>.APPLICATION_ID)</span>`,
      `<span class="line">        <span class="tok-k">val</span> CONTRACT_ID: <span class="tok-t">VariableName</span>.<span class="tok-t">Output</span> = output(<span class="tok-t">ProcessVariables</span>.CONTRACT_ID)</span>`,
      `<span class="line">      }</span>`,
      `<span class="line"> </span>`,
      `<span class="line">      <span class="tok-k">object</span> <span class="tok-t">Next</span> {</span>`,
      `<span class="line">        <span class="tok-k">val</span> gatewayAwaitSignature: <span class="tok-t">SequenceFlows</span>&lt;<span class="tok-t">GatewayAwaitSignature</span>&gt;</span>`,
      `<span class="line">          <span class="tok-k">get</span>() = <span class="tok-t">SequenceFlows</span>.single(</span>`,
      `<span class="line">            flowId = <span class="tok-t">ElementId</span>(<span class="tok-s">"flow_sendContractToAwaitSignature"</span>),</span>`,
      `<span class="line">            target = <span class="tok-t">GatewayAwaitSignature</span>,</span>`,
      `<span class="line">          )</span>`,
      `<span class="line">      }</span>`,
      `<span class="line">    }</span>`,
      `<span class="line">    <span class="tok-c">// … one object per BPMN element</span></span>`,
      `<span class="line">  }</span>`,
      `<span class="line">}</span>`,
      `<span class="line"> </span>`,
      `<span class="line"><span class="tok-c">// ServiceTasks.kt — generated once for all processes</span></span>`,
      `<span class="line"><span class="tok-k">object</span> <span class="tok-t">ServiceTasks</span> {</span>`,
      `<span class="line">  <span class="tok-k">const val</span> MIRAVELO_SEND_CONTRACT: <span class="tok-t">String</span> = <span class="tok-s">"miravelo.sendContract"</span></span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
  {
    id: 'test',
    label: 'BikeLeasingRulesTest.kt',
    filename: 'BikeLeasingRulesTest.kt',
    iconClass: 'kt',
    iconText: 'Kt',
    paneType: 'code',
    beta: true,
    code: [
      `<span class="line"><span class="tok-k">class</span> <span class="tok-t">BikeLeasingRulesTest</span> {</span>`,
      `<span class="line"> </span>`,
      `<span class="line">  <span class="tok-a">@Test</span></span>`,
      `<span class="line">  <span class="tok-k">fun</span> <span class="tok-s">\`bike leasing process passes architecture rules\`</span>() {</span>`,
      `<span class="line"> </span>`,
      `<span class="line">    <span class="tok-c">// when: validating the BPMN file</span></span>`,
      `<span class="line">    <span class="tok-k">val</span> result = <span class="tok-t">BpmnValidator</span></span>`,
      `<span class="line">      .fromClasspath(<span class="tok-s">"bpmn/bike-leasing.bpmn"</span>)</span>`,
      `<span class="line">      .engine(<span class="tok-t">ProcessEngine</span>.<span class="tok-n">ZEEBE</span>)</span>`,
      `<span class="line">      .withRules(</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_SERVICE_TASK_IMPLEMENTATION</span>,</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_MESSAGE_NAME</span>,</span>`,
      `<span class="line">        <span class="tok-t">BpmnRules</span>.<span class="tok-n">MISSING_TIMER_DEFINITION</span>,</span>`,
      `<span class="line">      )</span>`,
      `<span class="line">      .validate()</span>`,
      `<span class="line"> </span>`,
      `<span class="line">    <span class="tok-c">// then: no errors or violations</span></span>`,
      `<span class="line">    result.assertNoErrors()</span>`,
      `<span class="line">    result.assertNoViolations(<span class="tok-s">"missing-service-task-implementation"</span>)</span>`,
      `<span class="line">    result.assertNoViolations(<span class="tok-s">"missing-message-name"</span>)</span>`,
      `<span class="line">  }</span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
  {
    id: 'json',
    label: 'bikeLeasing.json',
    filename: 'bikeLeasing.json',
    iconClass: 'json',
    iconText: '{}',
    paneType: 'code',
    beta: true,
    code: [
      `<span class="line">{</span>`,
      `<span class="line">  <span class="tok-s">"$schema"</span>: <span class="tok-s">"https://miragon.github.io/bpmn-to-code/schema/process-model/2.0.json"</span>,</span>`,
      `<span class="line">  <span class="tok-s">"formatVersion"</span>: <span class="tok-s">"2.1"</span>,</span>`,
      `<span class="line">  <span class="tok-s">"process"</span>: {</span>`,
      `<span class="line">    <span class="tok-s">"id"</span>: <span class="tok-s">"bikeLeasing"</span>,</span>`,
      `<span class="line">    <span class="tok-s">"name"</span>: <span class="tok-s">"MiraVelo Bike Leasing"</span>,</span>`,
      `<span class="line">    <span class="tok-s">"engine"</span>: <span class="tok-s">"ZEEBE"</span>,</span>`,
      `<span class="line">    <span class="tok-s">"flowNodes"</span>: [</span>`,
      `<span class="line">      {</span>`,
      `<span class="line">        <span class="tok-s">"id"</span>: <span class="tok-s">"startEvent_leasingRequestReceived"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"type"</span>: <span class="tok-s">"startEvent"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"name"</span>: <span class="tok-s">"Leasing request received"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"flow_leasingRequestReceivedToValidateApplication"</span>],</span>`,
      `<span class="line">        <span class="tok-s">"eventDefinitions"</span>: [</span>`,
      `<span class="line">          { <span class="tok-s">"type"</span>: <span class="tok-s">"message"</span>, <span class="tok-s">"messageRef"</span>: <span class="tok-s">"message_leasingRequestReceived"</span> }</span>`,
      `<span class="line">        ]</span>`,
      `<span class="line">      },</span>`,
      `<span class="line">      {</span>`,
      `<span class="line">        <span class="tok-s">"id"</span>: <span class="tok-s">"serviceTask_validateApplication"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"type"</span>: <span class="tok-s">"serviceTask"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"name"</span>: <span class="tok-s">"Validate application"</span>,</span>`,
      `<span class="line">        <span class="tok-s">"incoming"</span>: [<span class="tok-s">"flow_leasingRequestReceivedToValidateApplication"</span>],</span>`,
      `<span class="line">        <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"flow_validateApplicationToCheckCreditRating"</span>],</span>`,
      `<span class="line">        <span class="tok-s">"boundaryEventRefs"</span>: [<span class="tok-s">"boundary_applicationInvalid"</span>],</span>`,
      `<span class="line">        <span class="tok-s">"implementation"</span>: { <span class="tok-s">"type"</span>: <span class="tok-s">"jobWorker"</span>, <span class="tok-s">"jobType"</span>: <span class="tok-s">"miravelo.validateApplication"</span> }</span>`,
      `<span class="line">      }</span>`,
      `<span class="line">    ]</span>`,
      `<span class="line">  },</span>`,
      `<span class="line">  <span class="tok-s">"definitions"</span>: {</span>`,
      `<span class="line">    <span class="tok-s">"messages"</span>: [</span>`,
      `<span class="line">      { <span class="tok-s">"id"</span>: <span class="tok-s">"message_leasingRequestReceived"</span>, <span class="tok-s">"name"</span>: <span class="tok-s">"miravelo.leasingRequestReceived"</span> }</span>`,
      `<span class="line">    ]</span>`,
      `<span class="line">  }</span>`,
      `<span class="line">}</span>`,
    ].join(''),
  },
]

export const generateCompare = {
  before: [
    `<span class="cline"><span class="tok-c">// scattered across your codebase</span></span>`,
    `<span class="cline">client.newCreateInstanceCommand()</span>`,
    `<span class="cline">  .bpmnProcessId(<span class="tok-s">"bikeLeasing"</span>)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// typo? runtime error.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newPublishMessageCommand()</span>`,
    `<span class="cline">  .messageName(<span class="tok-s">"miravelo.contractSigned"</span>)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// renamed? silent failure.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-a">@JobWorker</span>(type = <span class="tok-s">"miravelo.sendContract"</span>)</span>`,
    `<span class="cline"><span class="tok-k">fun</span> sendContract() { <span class="tok-c">/* ... */</span> }</span>`,
  ].join(''),
  after: [
    `<span class="cline"><span class="tok-k">import</span> <span class="tok-t">BikeLeasingProcessApi</span>.*</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newCreateInstanceCommand()</span>`,
    `<span class="cline">  .bpmnProcessId(PROCESS_ID)</span>`,
    `<span class="cline">  .send() <span class="tok-c">// rename → compiler error.</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline">client.newPublishMessageCommand()</span>`,
    `<span class="cline">  .messageName(<span class="tok-t">Messages</span>.MIRAVELO_CONTRACT_SIGNED)</span>`,
    `<span class="cline">  .send()</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-a">@JobWorker</span>(type = <span class="tok-t">ServiceTasks</span>.MIRAVELO_SEND_CONTRACT)</span>`,
    `<span class="cline"><span class="tok-k">fun</span> sendContract() { <span class="tok-c">/* ... */</span> }</span>`,
  ].join(''),
}

export const surfaceCompare = {
  before: [
    `<span class="cline"><span class="tok-k">&lt;bpmndi:BPMNShape</span> <span class="tok-a">id</span>=<span class="tok-s">"Event_12xytcj_di"</span></span>`,
    `<span class="cline">    <span class="tok-a">bpmnElement</span>=<span class="tok-s">"startEvent_leasingRequestReceived"</span><span class="tok-k">&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;dc:Bounds</span> <span class="tok-a">x</span>=<span class="tok-s">"42"</span> <span class="tok-a">y</span>=<span class="tok-s">"302"</span> <span class="tok-a">width</span>=<span class="tok-s">"36"</span> <span class="tok-a">height</span>=<span class="tok-s">"36"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;bpmndi:BPMNLabel&gt;</span></span>`,
    `<span class="cline">    <span class="tok-k">&lt;dc:Bounds</span> <span class="tok-a">x</span>=<span class="tok-s">"16"</span> <span class="tok-a">y</span>=<span class="tok-s">"345"</span> <span class="tok-a">width</span>=<span class="tok-s">"88"</span> <span class="tok-a">height</span>=<span class="tok-s">"27"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;/bpmndi:BPMNLabel&gt;</span></span>`,
    `<span class="cline"><span class="tok-k">&lt;/bpmndi:BPMNShape&gt;</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-k">&lt;bpmndi:BPMNEdge</span> <span class="tok-a">id</span>=<span class="tok-s">"Flow_1csfyyz_di"</span><span class="tok-k">&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"78"</span> <span class="tok-a">y</span>=<span class="tok-s">"320"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"155"</span> <span class="tok-a">y</span>=<span class="tok-s">"320"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"155"</span> <span class="tok-a">y</span>=<span class="tok-s">"200"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline">  <span class="tok-k">&lt;di:waypoint</span> <span class="tok-a">x</span>=<span class="tok-s">"230"</span> <span class="tok-a">y</span>=<span class="tok-s">"200"</span><span class="tok-k"> /&gt;</span></span>`,
    `<span class="cline"><span class="tok-k">&lt;/bpmndi:BPMNEdge&gt;</span></span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-c">&lt;!-- ~200 more lines of diagram interchange --&gt;</span></span>`,
  ].join(''),
  after: [
    `<span class="cline">{</span>`,
    `<span class="cline">  <span class="tok-s">"id"</span>: <span class="tok-s">"startEvent_leasingRequestReceived"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"type"</span>: <span class="tok-s">"startEvent"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"name"</span>: <span class="tok-s">"Leasing request received"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"flow_leasingRequestReceivedToValidateApplication"</span>],</span>`,
    `<span class="cline">  <span class="tok-s">"eventDefinitions"</span>: [</span>`,
    `<span class="cline">    { <span class="tok-s">"type"</span>: <span class="tok-s">"message"</span>, <span class="tok-s">"messageRef"</span>: <span class="tok-s">"message_leasingRequestReceived"</span> }</span>`,
    `<span class="cline">  ]</span>`,
    `<span class="cline">},</span>`,
    `<span class="cline">{</span>`,
    `<span class="cline">  <span class="tok-s">"id"</span>: <span class="tok-s">"timer_signatureReminder"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"type"</span>: <span class="tok-s">"boundaryEvent"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"name"</span>: <span class="tok-s">"7 days passed"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"outgoing"</span>: [<span class="tok-s">"flow_signatureReminderToSendReminderMail"</span>],</span>`,
    `<span class="cline">  <span class="tok-s">"attachedToRef"</span>: <span class="tok-s">"subProcess_concludeContract"</span>,</span>`,
    `<span class="cline">  <span class="tok-s">"cancelActivity"</span>: false,</span>`,
    `<span class="cline">  <span class="tok-s">"eventDefinitions"</span>: [</span>`,
    `<span class="cline">    { <span class="tok-s">"type"</span>: <span class="tok-s">"timer"</span>, <span class="tok-s">"timerType"</span>: <span class="tok-s">"DURATION"</span>, <span class="tok-s">"expression"</span>: <span class="tok-s">"P7D"</span> }</span>`,
    `<span class="cline">  ]</span>`,
    `<span class="cline">}</span>`,
    `<span class="cline blank"> </span>`,
    `<span class="cline"><span class="tok-c">// Nodes · flows · names. Nothing else.</span></span>`,
  ].join(''),
}

export interface RunnerRule {
  name: string
  hint: string
}

export const validateRules = {
  command: '$ ./gradlew test',
  fail: [
    { name: 'missing-service-task-implementation', hint: '<span class="tok-s">serviceTask_sendContract</span>: Service task has no implementation.' },
    { name: 'missing-message-name', hint: '<span class="tok-s">event_contractSigned</span>: Message element is missing a \'name\' attribute.' },
    { name: 'missing-timer-definition', hint: '<span class="tok-s">timer_signatureReminder</span>: Timer event definition has no valid type.' },
    { name: 'missing-called-element', hint: '<span class="tok-s">callActivity_cancelBikeOrder</span>: Call activity is missing a \'calledElement\'.' },
  ] as RunnerRule[],
  pass: [
    { name: 'missing-service-task-implementation', hint: 'Every service task has an implementation.' },
    { name: 'missing-message-name', hint: 'Every message is named.' },
    { name: 'missing-timer-definition', hint: 'Every timer has a type and a value.' },
    { name: 'missing-called-element', hint: 'Every call activity names its process.' },
  ] as RunnerRule[],
}

export interface Skill {
  icon: string
  name: string
  description: string
}

export const skills: Skill[] = [
  {
    icon: '\u2708',
    name: 'migrate-to-bpmn-to-code-apis',
    description: 'Replace hardcoded BPMN strings with references to the generated Process API, or rewrite 5.x references to the 6.x FlowNodes. Scans your source, shows a migration plan, and applies it after approval.',
  },
  {
    icon: '\u270E',
    name: 'build-bpmn-styleguide',
    description: 'Create a BPMN_STYLE_GUIDE.md with your team\'s conventions in an interactive wizard. validate-bpmn-style then checks your diagrams against it.',
  },
]
