// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.AttachedBoundaryEvent;
import io.miragon.bpmn.runtime.BoundaryEvent;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnErrorDefinition;
import io.miragon.bpmn.runtime.BpmnEscalationDefinition;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.CallActivity;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ErrorEvent;
import io.miragon.bpmn.runtime.EscalationEvent;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.FlowScope;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasMessage;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.LeadsTo;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import io.miragon.bpmn.runtime.Successor;
import io.miragon.bpmn.runtime.TimerEvent;
import io.miragon.bpmn.runtime.TimerType;
import io.miragon.bpmn.runtime.VariableName;
import java.util.List;

public final class BikeLeasingProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("bikeLeasing");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.ZEEBE;

  private BikeLeasingProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static BoundaryApplicationInvalid boundaryApplicationInvalid() {
      return BoundaryApplicationInvalid.INSTANCE;
    }

    public static BoundaryCompensateContract boundaryCompensateContract() {
      return BoundaryCompensateContract.INSTANCE;
    }

    public static BoundaryCompensateInsurance boundaryCompensateInsurance() {
      return BoundaryCompensateInsurance.INSTANCE;
    }

    public static BoundaryCompensateOrder boundaryCompensateOrder() {
      return BoundaryCompensateOrder.INSTANCE;
    }

    public static BoundaryContractNotSigned boundaryContractNotSigned() {
      return BoundaryContractNotSigned.INSTANCE;
    }

    public static BusinessRuleTaskCheckCreditRating businessRuleTaskCheckCreditRating() {
      return BusinessRuleTaskCheckCreditRating.INSTANCE;
    }

    public static CallActivityCancelBikeOrder callActivityCancelBikeOrder() {
      return CallActivityCancelBikeOrder.INSTANCE;
    }

    public static EndEventApplicationCancelled endEventApplicationCancelled() {
      return EndEventApplicationCancelled.INSTANCE;
    }

    public static EndEventApplicationRejected endEventApplicationRejected() {
      return EndEventApplicationRejected.INSTANCE;
    }

    public static EndEventContractConcluded endEventContractConcluded() {
      return EndEventContractConcluded.INSTANCE;
    }

    public static EndEventContractNotSigned endEventContractNotSigned() {
      return EndEventContractNotSigned.INSTANCE;
    }

    public static EndEventCustomerReminded endEventCustomerReminded() {
      return EndEventCustomerReminded.INSTANCE;
    }

    public static EndEventDeliveryAddressUpdated endEventDeliveryAddressUpdated() {
      return EndEventDeliveryAddressUpdated.INSTANCE;
    }

    public static EndEventLeasingActive endEventLeasingActive() {
      return EndEventLeasingActive.INSTANCE;
    }

    public static EventContractSigned eventContractSigned() {
      return EventContractSigned.INSTANCE;
    }

    public static EventReverseApplication eventReverseApplication() {
      return EventReverseApplication.INSTANCE;
    }

    public static GatewayAwaitSignature gatewayAwaitSignature() {
      return GatewayAwaitSignature.INSTANCE;
    }

    public static GatewayCollectRejections gatewayCollectRejections() {
      return GatewayCollectRejections.INSTANCE;
    }

    public static GatewayFork gatewayFork() {
      return GatewayFork.INSTANCE;
    }

    public static GatewayIsSolvent gatewayIsSolvent() {
      return GatewayIsSolvent.INSTANCE;
    }

    public static GatewayJoin gatewayJoin() {
      return GatewayJoin.INSTANCE;
    }

    public static ReceiveTaskHandoverReported receiveTaskHandoverReported() {
      return ReceiveTaskHandoverReported.INSTANCE;
    }

    public static ServiceTaskCancelContract serviceTaskCancelContract() {
      return ServiceTaskCancelContract.INSTANCE;
    }

    public static ServiceTaskCancelPolicy serviceTaskCancelPolicy() {
      return ServiceTaskCancelPolicy.INSTANCE;
    }

    public static ServiceTaskIssueInsurancePolicy serviceTaskIssueInsurancePolicy() {
      return ServiceTaskIssueInsurancePolicy.INSTANCE;
    }

    public static ServiceTaskOrderBike serviceTaskOrderBike() {
      return ServiceTaskOrderBike.INSTANCE;
    }

    public static ServiceTaskSendCancellationConfirmation serviceTaskSendCancellationConfirmation(
        ) {
      return ServiceTaskSendCancellationConfirmation.INSTANCE;
    }

    public static ServiceTaskSendContract serviceTaskSendContract() {
      return ServiceTaskSendContract.INSTANCE;
    }

    public static ServiceTaskSendRejection serviceTaskSendRejection() {
      return ServiceTaskSendRejection.INSTANCE;
    }

    public static ServiceTaskSendReminderMail serviceTaskSendReminderMail() {
      return ServiceTaskSendReminderMail.INSTANCE;
    }

    public static ServiceTaskValidateApplication serviceTaskValidateApplication() {
      return ServiceTaskValidateApplication.INSTANCE;
    }

    public static StartEventAddressChanged startEventAddressChanged() {
      return StartEventAddressChanged.INSTANCE;
    }

    public static StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
      return StartEventApplicationWithdrawn.INSTANCE;
    }

    public static StartEventCustomerEligible startEventCustomerEligible() {
      return StartEventCustomerEligible.INSTANCE;
    }

    public static StartEventLeasingRequestReceived startEventLeasingRequestReceived() {
      return StartEventLeasingRequestReceived.INSTANCE;
    }

    public static SubProcessAddressChanged subProcessAddressChanged() {
      return SubProcessAddressChanged.INSTANCE;
    }

    public static SubProcessApplicationWithdrawn subProcessApplicationWithdrawn() {
      return SubProcessApplicationWithdrawn.INSTANCE;
    }

    public static SubProcessConcludeContract subProcessConcludeContract() {
      return SubProcessConcludeContract.INSTANCE;
    }

    public static TimerSignatureDeadline timerSignatureDeadline() {
      return TimerSignatureDeadline.INSTANCE;
    }

    public static TimerSignatureReminder timerSignatureReminder() {
      return TimerSignatureReminder.INSTANCE;
    }

    public static TimerWithdrawalPeriodElapsed timerWithdrawalPeriodElapsed() {
      return TimerWithdrawalPeriodElapsed.INSTANCE;
    }

    public static UserTaskUpdateDeliveryAddress userTaskUpdateDeliveryAddress() {
      return UserTaskUpdateDeliveryAddress.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          BoundaryApplicationInvalid.INSTANCE,
          BoundaryCompensateContract.INSTANCE,
          BoundaryCompensateInsurance.INSTANCE,
          BoundaryCompensateOrder.INSTANCE,
          BoundaryContractNotSigned.INSTANCE,
          BusinessRuleTaskCheckCreditRating.INSTANCE,
          CallActivityCancelBikeOrder.INSTANCE,
          EndEventApplicationCancelled.INSTANCE,
          EndEventApplicationRejected.INSTANCE,
          EndEventContractConcluded.INSTANCE,
          EndEventContractNotSigned.INSTANCE,
          EndEventCustomerReminded.INSTANCE,
          EndEventDeliveryAddressUpdated.INSTANCE,
          EndEventLeasingActive.INSTANCE,
          EventContractSigned.INSTANCE,
          EventReverseApplication.INSTANCE,
          GatewayAwaitSignature.INSTANCE,
          GatewayCollectRejections.INSTANCE,
          GatewayFork.INSTANCE,
          GatewayIsSolvent.INSTANCE,
          GatewayJoin.INSTANCE,
          ReceiveTaskHandoverReported.INSTANCE,
          ServiceTaskCancelContract.INSTANCE,
          ServiceTaskCancelPolicy.INSTANCE,
          ServiceTaskIssueInsurancePolicy.INSTANCE,
          ServiceTaskOrderBike.INSTANCE,
          ServiceTaskSendCancellationConfirmation.INSTANCE,
          ServiceTaskSendContract.INSTANCE,
          ServiceTaskSendRejection.INSTANCE,
          ServiceTaskSendReminderMail.INSTANCE,
          ServiceTaskValidateApplication.INSTANCE,
          StartEventAddressChanged.INSTANCE,
          StartEventApplicationWithdrawn.INSTANCE,
          StartEventCustomerEligible.INSTANCE,
          StartEventLeasingRequestReceived.INSTANCE,
          SubProcessAddressChanged.INSTANCE,
          SubProcessApplicationWithdrawn.INSTANCE,
          SubProcessConcludeContract.INSTANCE,
          TimerSignatureDeadline.INSTANCE,
          TimerSignatureReminder.INSTANCE,
          TimerWithdrawalPeriodElapsed.INSTANCE,
          UserTaskUpdateDeliveryAddress.INSTANCE);
    }

    public static final class BoundaryApplicationInvalid extends AbstractFlowNode implements LeadsTo<GatewayCollectRejections>,
        Next.ServiceTaskValidateApplication,
        BoundaryEvent<ServiceTaskValidateApplication>,
        ErrorEvent {
      public static final String ELEMENT_ID = "boundary_applicationInvalid";

      public static final BoundaryApplicationInvalid INSTANCE = new BoundaryApplicationInvalid();

      private BoundaryApplicationInvalid() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Application invalid");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ERROR;
      }

      @Override
      public BpmnErrorDefinition getError() {
        return Errors.MIRAVELO_APPLICATION_INVALID;
      }

      @Override
      public ServiceTaskValidateApplication getAttachedTo() {
        return ServiceTaskValidateApplication.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public List<Successor<GatewayCollectRejections>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_applicationInvalidToCollectRejections"), GatewayCollectRejections.INSTANCE));
      }
    }

    public static final class BoundaryCompensateContract extends AbstractFlowNode implements Next.SubProcessConcludeContract, BoundaryEvent<SubProcessConcludeContract> {
      public static final String ELEMENT_ID = "boundary_compensateContract";

      public static final BoundaryCompensateContract INSTANCE = new BoundaryCompensateContract();

      private BoundaryCompensateContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Contract to revoke");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryCompensateInsurance extends AbstractFlowNode implements Next.ServiceTaskIssueInsurancePolicy, BoundaryEvent<ServiceTaskIssueInsurancePolicy> {
      public static final String ELEMENT_ID = "boundary_compensateInsurance";

      public static final BoundaryCompensateInsurance INSTANCE = new BoundaryCompensateInsurance();

      private BoundaryCompensateInsurance() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Policy to cancel");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public ServiceTaskIssueInsurancePolicy getAttachedTo() {
        return ServiceTaskIssueInsurancePolicy.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryCompensateOrder extends AbstractFlowNode implements Next.ServiceTaskOrderBike, BoundaryEvent<ServiceTaskOrderBike> {
      public static final String ELEMENT_ID = "boundary_compensateOrder";

      public static final BoundaryCompensateOrder INSTANCE = new BoundaryCompensateOrder();

      private BoundaryCompensateOrder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Order to cancel");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public ServiceTaskOrderBike getAttachedTo() {
        return ServiceTaskOrderBike.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryContractNotSigned extends AbstractFlowNode implements LeadsTo<GatewayCollectRejections>,
        Next.SubProcessConcludeContract,
        BoundaryEvent<SubProcessConcludeContract>,
        EscalationEvent {
      public static final String ELEMENT_ID = "boundary_contractNotSigned";

      public static final BoundaryContractNotSigned INSTANCE = new BoundaryContractNotSigned();

      private BoundaryContractNotSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Contract not signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ESCALATION;
      }

      @Override
      public BpmnEscalationDefinition getEscalation() {
        return Escalations.MIRAVELO_CONTRACT_NOT_SIGNED;
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public List<Successor<GatewayCollectRejections>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_contractNotSignedToCollectRejections"), GatewayCollectRejections.INSTANCE));
      }
    }

    public static final class BusinessRuleTaskCheckCreditRating extends AbstractFlowNode implements LeadsTo<GatewayIsSolvent>, Next.ServiceTaskValidateApplication {
      public static final String ELEMENT_ID = "businessRuleTask_checkCreditRating";

      public static final BusinessRuleTaskCheckCreditRating INSTANCE = new BusinessRuleTaskCheckCreditRating();

      private BusinessRuleTaskCheckCreditRating() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BUSINESS_RULE_TASK, "Check credit rating");
      }

      @Override
      public List<Successor<GatewayIsSolvent>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_checkCreditRatingToIsSolvent"), GatewayIsSolvent.INSTANCE));
      }
    }

    public static final class CallActivityCancelBikeOrder extends AbstractFlowNode implements CallActivity {
      public static final String ELEMENT_ID = "callActivity_cancelBikeOrder";

      public static final CallActivityCancelBikeOrder INSTANCE = new CallActivityCancelBikeOrder();

      private CallActivityCancelBikeOrder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.CALL_ACTIVITY, "Cancel bike order");
      }

      @Override
      public ProcessId getCalledProcess() {
        return new ProcessId("cancelBikeOrder");
      }

      public static final class Variables {
        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(ProcessVariables.APPLICATION_ID);

        public static final VariableName.Output CANCELLATION_COSTS = new VariableName.Output(ProcessVariables.CANCELLATION_COSTS);

        public static final VariableName.Input ORDER_IDS = new VariableName.Input(ProcessVariables.ORDER_IDS);

        private Variables() {
        }
      }

      public static final class Inputs {
        public static final InputOutputMapping APPLICATION_ID = new InputOutputMapping("applicationId", null, "${applicationId}");

        public static final InputOutputMapping ORDER_IDS = new InputOutputMapping("orderIds", "orderIds", null);

        private Inputs() {
        }
      }

      public static final class Outputs {
        public static final InputOutputMapping CANCELLATION_COSTS = new InputOutputMapping("cancellationCosts", "cancellationCosts", null);

        private Outputs() {
        }
      }
    }

    public static final class EndEventApplicationCancelled extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_applicationCancelled";

      public static final EndEventApplicationCancelled INSTANCE = new EndEventApplicationCancelled();

      private EndEventApplicationCancelled() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Application cancelled");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventApplicationRejected extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_applicationRejected";

      public static final EndEventApplicationRejected INSTANCE = new EndEventApplicationRejected();

      private EndEventApplicationRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Application rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TERMINATE;
      }
    }

    public static final class EndEventContractConcluded extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_contractConcluded";

      public static final EndEventContractConcluded INSTANCE = new EndEventContractConcluded();

      private EndEventContractConcluded() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Contract concluded");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventContractNotSigned extends AbstractFlowNode implements Event, EscalationEvent {
      public static final String ELEMENT_ID = "endEvent_contractNotSigned";

      public static final EndEventContractNotSigned INSTANCE = new EndEventContractNotSigned();

      private EndEventContractNotSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Contract not signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ESCALATION;
      }

      @Override
      public BpmnEscalationDefinition getEscalation() {
        return Escalations.MIRAVELO_CONTRACT_NOT_SIGNED;
      }
    }

    public static final class EndEventCustomerReminded extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_customerReminded";

      public static final EndEventCustomerReminded INSTANCE = new EndEventCustomerReminded();

      private EndEventCustomerReminded() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Customer reminded");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventDeliveryAddressUpdated extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_deliveryAddressUpdated";

      public static final EndEventDeliveryAddressUpdated INSTANCE = new EndEventDeliveryAddressUpdated();

      private EndEventDeliveryAddressUpdated() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Delivery address updated");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventLeasingActive extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_leasingActive";

      public static final EndEventLeasingActive INSTANCE = new EndEventLeasingActive();

      private EndEventLeasingActive() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Leasing active");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EventContractSigned extends AbstractFlowNode implements LeadsTo<EndEventContractConcluded>,
        Next.GatewayAwaitSignature,
        Event,
        HasMessage {
      public static final String ELEMENT_ID = "event_contractSigned";

      public static final EventContractSigned INSTANCE = new EventContractSigned();

      private EventContractSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "Contract signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_CONTRACT_SIGNED;
      }

      @Override
      public List<Successor<EndEventContractConcluded>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_contractSignedToContractConcluded"), EndEventContractConcluded.INSTANCE));
      }
    }

    public static final class EventReverseApplication extends AbstractFlowNode implements LeadsTo<ServiceTaskSendCancellationConfirmation>, Event {
      public static final String ELEMENT_ID = "event_reverseApplication";

      public static final EventReverseApplication INSTANCE = new EventReverseApplication();

      private EventReverseApplication() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_THROW_EVENT, "Application reversed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public List<Successor<ServiceTaskSendCancellationConfirmation>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_reverseApplicationToSendCancellationConfirmation"), ServiceTaskSendCancellationConfirmation.INSTANCE));
      }
    }

    public static final class GatewayAwaitSignature extends AbstractFlowNode implements LeadsTo<Next.GatewayAwaitSignature> {
      public static final String ELEMENT_ID = "gateway_awaitSignature";

      public static final GatewayAwaitSignature INSTANCE = new GatewayAwaitSignature();

      private GatewayAwaitSignature() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EVENT_BASED_GATEWAY, "Await signature");
      }

      @Override
      public List<Successor<Next.GatewayAwaitSignature>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_awaitSignatureToContractSigned"), EventContractSigned.INSTANCE),
            SequenceFlows.single(new ElementId("flow_awaitSignatureToSignatureDeadline"), TimerSignatureDeadline.INSTANCE));
      }
    }

    public static final class GatewayCollectRejections extends AbstractFlowNode implements LeadsTo<ServiceTaskSendRejection>, Next.GatewayIsSolvent {
      public static final String ELEMENT_ID = "gateway_collectRejections";

      public static final GatewayCollectRejections INSTANCE = new GatewayCollectRejections();

      private GatewayCollectRejections() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY);
      }

      @Override
      public List<Successor<ServiceTaskSendRejection>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_collectRejectionsToSendRejection"), ServiceTaskSendRejection.INSTANCE));
      }
    }

    public static final class GatewayFork extends AbstractFlowNode implements LeadsTo<Next.GatewayFork>, Next.SubProcessConcludeContract {
      public static final String ELEMENT_ID = "gateway_fork";

      public static final GatewayFork INSTANCE = new GatewayFork();

      private GatewayFork() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public List<Successor<Next.GatewayFork>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_forkToIssueInsurancePolicy"), ServiceTaskIssueInsurancePolicy.INSTANCE),
            SequenceFlows.single(new ElementId("flow_forkToOrderBike"), ServiceTaskOrderBike.INSTANCE));
      }
    }

    public static final class GatewayIsSolvent extends AbstractFlowNode implements LeadsTo<Next.GatewayIsSolvent> {
      public static final String ELEMENT_ID = "gateway_isSolvent";

      public static final GatewayIsSolvent INSTANCE = new GatewayIsSolvent();

      private GatewayIsSolvent() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Solvent?");
      }

      @Override
      public List<Successor<Next.GatewayIsSolvent>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_isSolventToCollectRejections"), "No", "${!solvent}", false, GatewayCollectRejections.INSTANCE),
            SequenceFlows.single(new ElementId("flow_isSolventToConcludeContract"), "Yes", null, true, SubProcessConcludeContract.INSTANCE));
      }
    }

    public static final class GatewayJoin extends AbstractFlowNode implements LeadsTo<ReceiveTaskHandoverReported>, Next.ServiceTaskIssueInsurancePolicy, Next.ServiceTaskOrderBike {
      public static final String ELEMENT_ID = "gateway_join";

      public static final GatewayJoin INSTANCE = new GatewayJoin();

      private GatewayJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public List<Successor<ReceiveTaskHandoverReported>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_joinToHandoverReported"), ReceiveTaskHandoverReported.INSTANCE));
      }
    }

    public static final class ReceiveTaskHandoverReported extends AbstractFlowNode implements LeadsTo<TimerWithdrawalPeriodElapsed>, HasMessage {
      public static final String ELEMENT_ID = "receiveTask_handoverReported";

      public static final ReceiveTaskHandoverReported INSTANCE = new ReceiveTaskHandoverReported();

      private ReceiveTaskHandoverReported() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.RECEIVE_TASK, "Await bike handover");
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_HANDOVER_REPORTED;
      }

      @Override
      public List<Successor<TimerWithdrawalPeriodElapsed>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_handoverReportedToWithdrawalPeriodElapsed"), TimerWithdrawalPeriodElapsed.INSTANCE));
      }
    }

    public static final class ServiceTaskCancelContract extends AbstractFlowNode implements HasJobType {
      public static final String ELEMENT_ID = "serviceTask_cancelContract";

      public static final ServiceTaskCancelContract INSTANCE = new ServiceTaskCancelContract();

      private ServiceTaskCancelContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Cancel contract");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.CANCEL_CONTRACT_DELEGATE;
      }
    }

    public static final class ServiceTaskCancelPolicy extends AbstractFlowNode implements HasJobType {
      public static final String ELEMENT_ID = "serviceTask_cancelPolicy";

      public static final ServiceTaskCancelPolicy INSTANCE = new ServiceTaskCancelPolicy();

      private ServiceTaskCancelPolicy() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Cancel policy");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_CANCEL_POLICY;
      }
    }

    public static final class ServiceTaskIssueInsurancePolicy extends AbstractFlowNode implements LeadsTo<Next.ServiceTaskIssueInsurancePolicy>, Next.GatewayFork, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_issueInsurancePolicy";

      public static final ServiceTaskIssueInsurancePolicy INSTANCE = new ServiceTaskIssueInsurancePolicy();

      private ServiceTaskIssueInsurancePolicy() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Issue insurance policy");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.IO_MIRAVELO_LEASING_ISSUE_INSURANCE_POLICY_DELEGATE;
      }

      @Override
      public List<Successor<Next.ServiceTaskIssueInsurancePolicy>> getOutgoing() {
        return List.of(
            new AttachedBoundaryEvent<>(BoundaryCompensateInsurance.INSTANCE),
            SequenceFlows.single(new ElementId("flow_issueInsurancePolicyToJoin"), GatewayJoin.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.Input BIKE_ID = new VariableName.Input(ProcessVariables.BIKE_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(ProcessVariables.BIKE_IDS);

        private Variables() {
        }
      }
    }

    public static final class ServiceTaskOrderBike extends AbstractFlowNode implements LeadsTo<Next.ServiceTaskOrderBike>, Next.GatewayFork, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_orderBike";

      public static final ServiceTaskOrderBike INSTANCE = new ServiceTaskOrderBike();

      private ServiceTaskOrderBike() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Order bike");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_ORDER_BIKE;
      }

      @Override
      public List<Successor<Next.ServiceTaskOrderBike>> getOutgoing() {
        return List.of(
            new AttachedBoundaryEvent<>(BoundaryCompensateOrder.INSTANCE),
            SequenceFlows.single(new ElementId("flow_orderBikeToJoin"), GatewayJoin.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.Input BIKE_ID = new VariableName.Input(ProcessVariables.BIKE_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(ProcessVariables.BIKE_IDS);

        private Variables() {
        }
      }
    }

    public static final class ServiceTaskSendCancellationConfirmation extends AbstractFlowNode implements LeadsTo<EndEventApplicationCancelled>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendCancellationConfirmation";

      public static final ServiceTaskSendCancellationConfirmation INSTANCE = new ServiceTaskSendCancellationConfirmation();

      private ServiceTaskSendCancellationConfirmation() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send cancellation confirmation");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION;
      }

      @Override
      public List<Successor<EndEventApplicationCancelled>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_sendCancellationConfirmationToApplicationCancelled"), EndEventApplicationCancelled.INSTANCE));
      }
    }

    public static final class ServiceTaskSendContract extends AbstractFlowNode implements LeadsTo<GatewayAwaitSignature>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendContract";

      public static final ServiceTaskSendContract INSTANCE = new ServiceTaskSendContract();

      private ServiceTaskSendContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send contract");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_CONTRACT_DELEGATE;
      }

      @Override
      public List<Successor<GatewayAwaitSignature>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_sendContractToAwaitSignature"), GatewayAwaitSignature.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(ProcessVariables.APPLICATION_ID);

        public static final VariableName.Output CONTRACT_ID = new VariableName.Output(ProcessVariables.CONTRACT_ID);

        private Variables() {
        }
      }
    }

    public static final class ServiceTaskSendRejection extends AbstractFlowNode implements LeadsTo<EndEventApplicationRejected>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendRejection";

      public static final ServiceTaskSendRejection INSTANCE = new ServiceTaskSendRejection();

      private ServiceTaskSendRejection() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send rejection");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_REJECTION;
      }

      @Override
      public List<Successor<EndEventApplicationRejected>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_sendRejectionToApplicationRejected"), EndEventApplicationRejected.INSTANCE));
      }
    }

    public static final class ServiceTaskSendReminderMail extends AbstractFlowNode implements LeadsTo<EndEventCustomerReminded>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendReminderMail";

      public static final ServiceTaskSendReminderMail INSTANCE = new ServiceTaskSendReminderMail();

      private ServiceTaskSendReminderMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send reminder mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MAIL_SERVICE_SEND_REMINDER_APPLICATION_ID_;
      }

      @Override
      public List<Successor<EndEventCustomerReminded>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_sendReminderMailToCustomerReminded"), EndEventCustomerReminded.INSTANCE));
      }
    }

    public static final class ServiceTaskValidateApplication extends AbstractFlowNode implements LeadsTo<Next.ServiceTaskValidateApplication>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_validateApplication";

      public static final ServiceTaskValidateApplication INSTANCE = new ServiceTaskValidateApplication();

      private ServiceTaskValidateApplication() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Validate application");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.VALIDATE_APPLICATION_DELEGATE;
      }

      @Override
      public List<Successor<Next.ServiceTaskValidateApplication>> getOutgoing() {
        return List.of(
            new AttachedBoundaryEvent<>(BoundaryApplicationInvalid.INSTANCE),
            SequenceFlows.single(new ElementId("flow_validateApplicationToCheckCreditRating"), BusinessRuleTaskCheckCreditRating.INSTANCE));
      }
    }

    public static final class StartEventAddressChanged extends AbstractFlowNode implements LeadsTo<UserTaskUpdateDeliveryAddress>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_addressChanged";

      public static final StartEventAddressChanged INSTANCE = new StartEventAddressChanged();

      private StartEventAddressChanged() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Address changed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_ADDRESS_CHANGED;
      }

      public boolean isInterrupting() {
        return false;
      }

      @Override
      public List<Successor<UserTaskUpdateDeliveryAddress>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_addressChangedToUpdateDeliveryAddress"), UserTaskUpdateDeliveryAddress.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.Input CITY = new VariableName.Input(ProcessVariables.CITY);

        public static final VariableName.Input STREET = new VariableName.Input(ProcessVariables.STREET);

        private Variables() {
        }
      }
    }

    public static final class StartEventApplicationWithdrawn extends AbstractFlowNode implements LeadsTo<EventReverseApplication>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_applicationWithdrawn";

      public static final StartEventApplicationWithdrawn INSTANCE = new StartEventApplicationWithdrawn();

      private StartEventApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Application withdrawn");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_APPLICATION_WITHDRAWN;
      }

      public boolean isInterrupting() {
        return true;
      }

      @Override
      public List<Successor<EventReverseApplication>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_applicationWithdrawnToReverseApplication"), EventReverseApplication.INSTANCE));
      }
    }

    public static final class StartEventCustomerEligible extends AbstractFlowNode implements LeadsTo<ServiceTaskSendContract>, Event {
      public static final String ELEMENT_ID = "startEvent_customerEligible";

      public static final StartEventCustomerEligible INSTANCE = new StartEventCustomerEligible();

      private StartEventCustomerEligible() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Customer eligible");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public List<Successor<ServiceTaskSendContract>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_customerEligibleToSendContract"), ServiceTaskSendContract.INSTANCE));
      }
    }

    public static final class StartEventLeasingRequestReceived extends AbstractFlowNode implements LeadsTo<ServiceTaskValidateApplication>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_leasingRequestReceived";

      public static final StartEventLeasingRequestReceived INSTANCE = new StartEventLeasingRequestReceived();

      private StartEventLeasingRequestReceived() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Leasing request received");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_LEASING_REQUEST_RECEIVED;
      }

      @Override
      public List<Successor<ServiceTaskValidateApplication>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_leasingRequestReceivedToValidateApplication"), ServiceTaskValidateApplication.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.Input AGE = new VariableName.Input(ProcessVariables.AGE);

        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(ProcessVariables.APPLICATION_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(ProcessVariables.BIKE_IDS);

        public static final VariableName.Input MONTHLY_NET_INCOME = new VariableName.Input(ProcessVariables.MONTHLY_NET_INCOME);

        private Variables() {
        }
      }
    }

    public static final class SubProcessAddressChanged extends AbstractFlowNode implements FlowScope<SubProcessAddressChanged.Start> {
      public static final String ELEMENT_ID = "subProcess_addressChanged";

      public static final SubProcessAddressChanged INSTANCE = new SubProcessAddressChanged();

      private SubProcessAddressChanged() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EVENT_SUB_PROCESS, "Delivery address changed");
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventAddressChanged startEventAddressChanged() {
          return StartEventAddressChanged.INSTANCE;
        }
      }
    }

    public static final class SubProcessApplicationWithdrawn extends AbstractFlowNode implements FlowScope<SubProcessApplicationWithdrawn.Start> {
      public static final String ELEMENT_ID = "subProcess_applicationWithdrawn";

      public static final SubProcessApplicationWithdrawn INSTANCE = new SubProcessApplicationWithdrawn();

      private SubProcessApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EVENT_SUB_PROCESS, "Application withdrawn");
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
          return StartEventApplicationWithdrawn.INSTANCE;
        }
      }
    }

    public static final class SubProcessConcludeContract extends AbstractFlowNode implements LeadsTo<Next.SubProcessConcludeContract>, Next.GatewayIsSolvent, FlowScope<SubProcessConcludeContract.Start> {
      public static final String ELEMENT_ID = "subProcess_concludeContract";

      public static final SubProcessConcludeContract INSTANCE = new SubProcessConcludeContract();

      private SubProcessConcludeContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SUB_PROCESS, "Conclude contract");
      }

      @Override
      public List<Successor<Next.SubProcessConcludeContract>> getOutgoing() {
        return List.of(
            new AttachedBoundaryEvent<>(BoundaryCompensateContract.INSTANCE),
            new AttachedBoundaryEvent<>(BoundaryContractNotSigned.INSTANCE),
            SequenceFlows.single(new ElementId("flow_concludeContractToFork"), GatewayFork.INSTANCE),
            new AttachedBoundaryEvent<>(TimerSignatureReminder.INSTANCE));
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventCustomerEligible startEventCustomerEligible() {
          return StartEventCustomerEligible.INSTANCE;
        }
      }
    }

    public static final class TimerSignatureDeadline extends AbstractFlowNode implements LeadsTo<EndEventContractNotSigned>,
        Next.GatewayAwaitSignature,
        Event,
        TimerEvent {
      public static final String ELEMENT_ID = "timer_signatureDeadline";

      public static final TimerSignatureDeadline INSTANCE = new TimerSignatureDeadline();

      private TimerSignatureDeadline() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "14 days passed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P14D");
      }

      @Override
      public List<Successor<EndEventContractNotSigned>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_signatureDeadlineToContractNotSigned"), EndEventContractNotSigned.INSTANCE));
      }
    }

    public static final class TimerSignatureReminder extends AbstractFlowNode implements LeadsTo<ServiceTaskSendReminderMail>,
        Next.SubProcessConcludeContract,
        BoundaryEvent<SubProcessConcludeContract>,
        TimerEvent {
      public static final String ELEMENT_ID = "timer_signatureReminder";

      public static final TimerSignatureReminder INSTANCE = new TimerSignatureReminder();

      private TimerSignatureReminder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "7 days passed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P7D");
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return false;
      }

      @Override
      public List<Successor<ServiceTaskSendReminderMail>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_signatureReminderToSendReminderMail"), ServiceTaskSendReminderMail.INSTANCE));
      }
    }

    public static final class TimerWithdrawalPeriodElapsed extends AbstractFlowNode implements LeadsTo<EndEventLeasingActive>, Event, TimerEvent {
      public static final String ELEMENT_ID = "timer_withdrawalPeriodElapsed";

      public static final TimerWithdrawalPeriodElapsed INSTANCE = new TimerWithdrawalPeriodElapsed();

      private TimerWithdrawalPeriodElapsed() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "Withdrawal period elapsed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "${withdrawalPeriod}");
      }

      @Override
      public List<Successor<EndEventLeasingActive>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_withdrawalPeriodElapsedToLeasingActive"), EndEventLeasingActive.INSTANCE));
      }
    }

    public static final class UserTaskUpdateDeliveryAddress extends AbstractFlowNode implements LeadsTo<EndEventDeliveryAddressUpdated> {
      public static final String ELEMENT_ID = "userTask_updateDeliveryAddress";

      public static final UserTaskUpdateDeliveryAddress INSTANCE = new UserTaskUpdateDeliveryAddress();

      private UserTaskUpdateDeliveryAddress() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Update delivery address");
      }

      @Override
      public List<Successor<EndEventDeliveryAddressUpdated>> getOutgoing() {
        return List.of(
            SequenceFlows.single(new ElementId("flow_updateDeliveryAddressToDeliveryAddressUpdated"), EndEventDeliveryAddressUpdated.INSTANCE));
      }

      public static final class Variables {
        public static final VariableName.InOut DELIVERY_ADDRESS = new VariableName.InOut(ProcessVariables.DELIVERY_ADDRESS);

        private Variables() {
        }
      }
    }

    /**
     * One marker per element leading to several others, implemented by every element it leads to.
     */
    public static final class Next {
      private Next() {
      }

      public interface GatewayAwaitSignature extends FlowNode {
      }

      public interface GatewayFork extends FlowNode {
      }

      public interface GatewayIsSolvent extends FlowNode {
      }

      public interface ServiceTaskIssueInsurancePolicy extends FlowNode {
      }

      public interface ServiceTaskOrderBike extends FlowNode {
      }

      public interface ServiceTaskValidateApplication extends FlowNode {
      }

      public interface SubProcessConcludeContract extends FlowNode {
      }
    }
  }
}
