// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BoundaryEvent;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnError;
import io.miragon.bpmn.runtime.BpmnEscalation;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.FlowScope;
import io.miragon.bpmn.runtime.HasOutgoingFlows;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlow;
import io.miragon.bpmn.runtime.VariableName;
import java.lang.Override;
import java.lang.String;
import java.util.List;

public final class BikeLeasingProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId(Names.PROCESS_ID);

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.ZEEBE;

  public static final class Names {
    public static final String PROCESS_ID = "bikeLeasing";
  }

  /**
   * Typed navigation over the process flow. Each element is a nested class exposing its {@code id}, {@code elementType} and display {@code name}, plus the elements reachable from it behind {@code getNext()} — so a full path is verified by the compiler and offered by autocomplete. Every element is a direct child of {@code Flow}, whatever its subprocess depth; a subprocess opens its interior via {@code getStartEvents()}, and {@code all()} lists every element.
   */
  public static final class Flow {
    /**
     * Every node of this flow, so tests can check all elements (job workers, deployed ids, …) without reflection.
     */
    public static List<FlowNode> all() {
      return List.of(
          new BoundaryApplicationInvalid(),
          new BoundaryCompensateContract(),
          new BoundaryCompensateInsurance(),
          new BoundaryCompensateOrder(),
          new BoundaryContractNotSigned(),
          new BusinessRuleTaskCheckCreditRating(),
          new CallActivityCancelBikeOrder(),
          new EndEventApplicationCancelled(),
          new EndEventApplicationRejected(),
          new EndEventContractConcluded(),
          new EndEventContractNotSigned(),
          new EndEventCustomerReminded(),
          new EndEventDeliveryAddressUpdated(),
          new EndEventLeasingActive(),
          new EventContractSigned(),
          new EventReverseApplication(),
          new GatewayAwaitSignature(),
          new GatewayCollectRejections(),
          new GatewayFork(),
          new GatewayIsSolvent(),
          new GatewayJoin(),
          new ReceiveTaskHandoverReported(),
          new ServiceTaskCancelContract(),
          new ServiceTaskCancelPolicy(),
          new ServiceTaskIssueInsurancePolicy(),
          new ServiceTaskOrderBike(),
          new ServiceTaskSendCancellationConfirmation(),
          new ServiceTaskSendContract(),
          new ServiceTaskSendRejection(),
          new ServiceTaskSendReminderMail(),
          new ServiceTaskValidateApplication(),
          new StartEventAddressChanged(),
          new StartEventApplicationWithdrawn(),
          new StartEventCustomerEligible(),
          new StartEventLeasingRequestReceived(),
          new SubProcessAddressChanged(),
          new SubProcessApplicationWithdrawn(),
          new SubProcessConcludeContract(),
          new TimerSignatureDeadline(),
          new TimerSignatureReminder(),
          new TimerWithdrawalPeriodElapsed(),
          new UserTaskUpdateDeliveryAddress());
    }

    public static BoundaryApplicationInvalid boundaryApplicationInvalid() {
      return new BoundaryApplicationInvalid();
    }

    public static BoundaryCompensateContract boundaryCompensateContract() {
      return new BoundaryCompensateContract();
    }

    public static BoundaryCompensateInsurance boundaryCompensateInsurance() {
      return new BoundaryCompensateInsurance();
    }

    public static BoundaryCompensateOrder boundaryCompensateOrder() {
      return new BoundaryCompensateOrder();
    }

    public static BoundaryContractNotSigned boundaryContractNotSigned() {
      return new BoundaryContractNotSigned();
    }

    public static BusinessRuleTaskCheckCreditRating businessRuleTaskCheckCreditRating() {
      return new BusinessRuleTaskCheckCreditRating();
    }

    public static CallActivityCancelBikeOrder callActivityCancelBikeOrder() {
      return new CallActivityCancelBikeOrder();
    }

    public static EndEventApplicationCancelled endEventApplicationCancelled() {
      return new EndEventApplicationCancelled();
    }

    public static EndEventApplicationRejected endEventApplicationRejected() {
      return new EndEventApplicationRejected();
    }

    public static EndEventContractConcluded endEventContractConcluded() {
      return new EndEventContractConcluded();
    }

    public static EndEventContractNotSigned endEventContractNotSigned() {
      return new EndEventContractNotSigned();
    }

    public static EndEventCustomerReminded endEventCustomerReminded() {
      return new EndEventCustomerReminded();
    }

    public static EndEventDeliveryAddressUpdated endEventDeliveryAddressUpdated() {
      return new EndEventDeliveryAddressUpdated();
    }

    public static EndEventLeasingActive endEventLeasingActive() {
      return new EndEventLeasingActive();
    }

    public static EventContractSigned eventContractSigned() {
      return new EventContractSigned();
    }

    public static EventReverseApplication eventReverseApplication() {
      return new EventReverseApplication();
    }

    public static GatewayAwaitSignature gatewayAwaitSignature() {
      return new GatewayAwaitSignature();
    }

    public static GatewayCollectRejections gatewayCollectRejections() {
      return new GatewayCollectRejections();
    }

    public static GatewayFork gatewayFork() {
      return new GatewayFork();
    }

    public static GatewayIsSolvent gatewayIsSolvent() {
      return new GatewayIsSolvent();
    }

    public static GatewayJoin gatewayJoin() {
      return new GatewayJoin();
    }

    public static ReceiveTaskHandoverReported receiveTaskHandoverReported() {
      return new ReceiveTaskHandoverReported();
    }

    public static ServiceTaskCancelContract serviceTaskCancelContract() {
      return new ServiceTaskCancelContract();
    }

    public static ServiceTaskCancelPolicy serviceTaskCancelPolicy() {
      return new ServiceTaskCancelPolicy();
    }

    public static ServiceTaskIssueInsurancePolicy serviceTaskIssueInsurancePolicy() {
      return new ServiceTaskIssueInsurancePolicy();
    }

    public static ServiceTaskOrderBike serviceTaskOrderBike() {
      return new ServiceTaskOrderBike();
    }

    public static ServiceTaskSendCancellationConfirmation serviceTaskSendCancellationConfirmation(
        ) {
      return new ServiceTaskSendCancellationConfirmation();
    }

    public static ServiceTaskSendContract serviceTaskSendContract() {
      return new ServiceTaskSendContract();
    }

    public static ServiceTaskSendRejection serviceTaskSendRejection() {
      return new ServiceTaskSendRejection();
    }

    public static ServiceTaskSendReminderMail serviceTaskSendReminderMail() {
      return new ServiceTaskSendReminderMail();
    }

    public static ServiceTaskValidateApplication serviceTaskValidateApplication() {
      return new ServiceTaskValidateApplication();
    }

    public static StartEventAddressChanged startEventAddressChanged() {
      return new StartEventAddressChanged();
    }

    public static StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
      return new StartEventApplicationWithdrawn();
    }

    public static StartEventCustomerEligible startEventCustomerEligible() {
      return new StartEventCustomerEligible();
    }

    public static StartEventLeasingRequestReceived startEventLeasingRequestReceived() {
      return new StartEventLeasingRequestReceived();
    }

    public static SubProcessAddressChanged subProcessAddressChanged() {
      return new SubProcessAddressChanged();
    }

    public static SubProcessApplicationWithdrawn subProcessApplicationWithdrawn() {
      return new SubProcessApplicationWithdrawn();
    }

    public static SubProcessConcludeContract subProcessConcludeContract() {
      return new SubProcessConcludeContract();
    }

    public static TimerSignatureDeadline timerSignatureDeadline() {
      return new TimerSignatureDeadline();
    }

    public static TimerSignatureReminder timerSignatureReminder() {
      return new TimerSignatureReminder();
    }

    public static TimerWithdrawalPeriodElapsed timerWithdrawalPeriodElapsed() {
      return new TimerWithdrawalPeriodElapsed();
    }

    public static UserTaskUpdateDeliveryAddress userTaskUpdateDeliveryAddress() {
      return new UserTaskUpdateDeliveryAddress();
    }

    public static final class BoundaryApplicationInvalid extends AbstractFlowNode implements HasSuccessors<BoundaryApplicationInvalid.Next>, HasOutgoingFlows<BoundaryApplicationInvalid.OutgoingFlows>, BoundaryEvent<ServiceTaskValidateApplication> {
      public static final String ELEMENT_ID = "boundary_applicationInvalid";

      public static final BpmnError ERROR = Errors.MIRAVELO_APPLICATION_INVALID_APPLICATION_INVALID;

      public BoundaryApplicationInvalid() {
        super(new ElementId(ELEMENT_ID), "ERROR_BOUNDARY_EVENT", "Application invalid");
      }

      @Override
      public ServiceTaskValidateApplication getAttachedTo() {
        return new ServiceTaskValidateApplication();
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public GatewayCollectRejections gatewayCollectRejections() {
          return new GatewayCollectRejections();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayCollectRejections> toGatewayCollectRejections() {
          return new SequenceFlow<>(new ElementId("flow_applicationInvalidToCollectRejections"), null, null, false, new GatewayCollectRejections());
        }
      }
    }

    public static final class BoundaryCompensateContract extends AbstractFlowNode implements BoundaryEvent<SubProcessConcludeContract> {
      public static final String ELEMENT_ID = "boundary_compensateContract";

      public BoundaryCompensateContract() {
        super(new ElementId(ELEMENT_ID), "COMPENSATION_BOUNDARY_EVENT", "Contract to revoke");
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return new SubProcessConcludeContract();
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryCompensateInsurance extends AbstractFlowNode implements BoundaryEvent<ServiceTaskIssueInsurancePolicy> {
      public static final String ELEMENT_ID = "boundary_compensateInsurance";

      public BoundaryCompensateInsurance() {
        super(new ElementId(ELEMENT_ID), "COMPENSATION_BOUNDARY_EVENT", "Policy to cancel");
      }

      @Override
      public ServiceTaskIssueInsurancePolicy getAttachedTo() {
        return new ServiceTaskIssueInsurancePolicy();
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryCompensateOrder extends AbstractFlowNode implements BoundaryEvent<ServiceTaskOrderBike> {
      public static final String ELEMENT_ID = "boundary_compensateOrder";

      public BoundaryCompensateOrder() {
        super(new ElementId(ELEMENT_ID), "COMPENSATION_BOUNDARY_EVENT", "Order to cancel");
      }

      @Override
      public ServiceTaskOrderBike getAttachedTo() {
        return new ServiceTaskOrderBike();
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }
    }

    public static final class BoundaryContractNotSigned extends AbstractFlowNode implements HasSuccessors<BoundaryContractNotSigned.Next>, HasOutgoingFlows<BoundaryContractNotSigned.OutgoingFlows>, BoundaryEvent<SubProcessConcludeContract> {
      public static final String ELEMENT_ID = "boundary_contractNotSigned";

      public static final BpmnEscalation ESCALATION = Escalations.MIRAVELO_CONTRACT_NOT_SIGNED_CONTRACT_NOT_SIGNED;

      public BoundaryContractNotSigned() {
        super(new ElementId(ELEMENT_ID), "ESCALATION_BOUNDARY_EVENT", "Contract not signed");
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return new SubProcessConcludeContract();
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public GatewayCollectRejections gatewayCollectRejections() {
          return new GatewayCollectRejections();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayCollectRejections> toGatewayCollectRejections() {
          return new SequenceFlow<>(new ElementId("flow_contractNotSignedToCollectRejections"), null, null, false, new GatewayCollectRejections());
        }
      }
    }

    public static final class BusinessRuleTaskCheckCreditRating extends AbstractFlowNode implements HasSuccessors<BusinessRuleTaskCheckCreditRating.Next>, HasOutgoingFlows<BusinessRuleTaskCheckCreditRating.OutgoingFlows> {
      public static final String ELEMENT_ID = "businessRuleTask_checkCreditRating";

      public BusinessRuleTaskCheckCreditRating() {
        super(new ElementId(ELEMENT_ID), "BUSINESS_RULE_TASK", "Check credit rating");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public GatewayIsSolvent gatewayIsSolvent() {
          return new GatewayIsSolvent();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayIsSolvent> toGatewayIsSolvent() {
          return new SequenceFlow<>(new ElementId("flow_checkCreditRatingToIsSolvent"), null, null, false, new GatewayIsSolvent());
        }
      }
    }

    public static final class CallActivityCancelBikeOrder extends AbstractFlowNode {
      public static final String ELEMENT_ID = "callActivity_cancelBikeOrder";

      public static final ProcessId CALLED_PROCESS = new ProcessId("cancelBikeOrder");

      public CallActivityCancelBikeOrder() {
        super(new ElementId(ELEMENT_ID), "CALL_ACTIVITY", "Cancel bike order");
      }

      public static final class Variables {
        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(Names.APPLICATION_ID);

        public static final VariableName.Output CANCELLATION_COSTS = new VariableName.Output(Names.CANCELLATION_COSTS);

        public static final VariableName.Input ORDER_IDS = new VariableName.Input(Names.ORDER_IDS);

        public static final class Names {
          public static final String APPLICATION_ID = "applicationId";

          public static final String CANCELLATION_COSTS = "cancellationCosts";

          public static final String ORDER_IDS = "orderIds";
        }
      }

      public static final class Inputs {
        public static final InputOutputMapping APPLICATION_ID = new InputOutputMapping("applicationId", null, "${applicationId}");

        public static final InputOutputMapping ORDER_IDS = new InputOutputMapping("orderIds", "orderIds", null);
      }

      public static final class Outputs {
        public static final InputOutputMapping CANCELLATION_COSTS = new InputOutputMapping("cancellationCosts", "cancellationCosts", null);
      }
    }

    public static final class EndEventApplicationCancelled extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_applicationCancelled";

      public EndEventApplicationCancelled() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Application cancelled");
      }
    }

    public static final class EndEventApplicationRejected extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_applicationRejected";

      public EndEventApplicationRejected() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Application rejected");
      }
    }

    public static final class EndEventContractConcluded extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_contractConcluded";

      public EndEventContractConcluded() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Contract concluded");
      }
    }

    public static final class EndEventContractNotSigned extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_contractNotSigned";

      public static final BpmnEscalation ESCALATION = Escalations.MIRAVELO_CONTRACT_NOT_SIGNED_CONTRACT_NOT_SIGNED;

      public EndEventContractNotSigned() {
        super(new ElementId(ELEMENT_ID), "ESCALATION_END_EVENT", "Contract not signed");
      }
    }

    public static final class EndEventCustomerReminded extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_customerReminded";

      public EndEventCustomerReminded() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Customer reminded");
      }
    }

    public static final class EndEventDeliveryAddressUpdated extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_deliveryAddressUpdated";

      public EndEventDeliveryAddressUpdated() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Delivery address updated");
      }
    }

    public static final class EndEventLeasingActive extends AbstractFlowNode {
      public static final String ELEMENT_ID = "endEvent_leasingActive";

      public EndEventLeasingActive() {
        super(new ElementId(ELEMENT_ID), "END_EVENT", "Leasing active");
      }
    }

    public static final class EventContractSigned extends AbstractFlowNode implements HasSuccessors<EventContractSigned.Next>, HasOutgoingFlows<EventContractSigned.OutgoingFlows> {
      public static final String ELEMENT_ID = "event_contractSigned";

      public static final MessageName MESSAGE = Messages.MIRAVELO_CONTRACT_SIGNED;

      public EventContractSigned() {
        super(new ElementId(ELEMENT_ID), "MESSAGE_INTERMEDIATE_CATCH_EVENT", "Contract signed");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventContractConcluded endEventContractConcluded() {
          return new EndEventContractConcluded();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventContractConcluded> toEndEventContractConcluded() {
          return new SequenceFlow<>(new ElementId("flow_contractSignedToContractConcluded"), null, null, false, new EndEventContractConcluded());
        }
      }
    }

    public static final class EventReverseApplication extends AbstractFlowNode implements HasSuccessors<EventReverseApplication.Next>, HasOutgoingFlows<EventReverseApplication.OutgoingFlows> {
      public static final String ELEMENT_ID = "event_reverseApplication";

      public EventReverseApplication() {
        super(new ElementId(ELEMENT_ID), "COMPENSATION_INTERMEDIATE_THROW_EVENT", "Application reversed");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ServiceTaskSendCancellationConfirmation serviceTaskSendCancellationConfirmation() {
          return new ServiceTaskSendCancellationConfirmation();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskSendCancellationConfirmation> toServiceTaskSendCancellationConfirmation(
            ) {
          return new SequenceFlow<>(new ElementId("flow_reverseApplicationToSendCancellationConfirmation"), null, null, false, new ServiceTaskSendCancellationConfirmation());
        }
      }
    }

    public static final class GatewayAwaitSignature extends AbstractFlowNode implements HasSuccessors<GatewayAwaitSignature.Next>, HasOutgoingFlows<GatewayAwaitSignature.OutgoingFlows> {
      public static final String ELEMENT_ID = "gateway_awaitSignature";

      public GatewayAwaitSignature() {
        super(new ElementId(ELEMENT_ID), "EVENT_BASED_GATEWAY", "Await signature");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EventContractSigned eventContractSigned() {
          return new EventContractSigned();
        }

        public TimerSignatureDeadline timerSignatureDeadline() {
          return new TimerSignatureDeadline();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EventContractSigned> toEventContractSigned() {
          return new SequenceFlow<>(new ElementId("flow_awaitSignatureToContractSigned"), null, null, false, new EventContractSigned());
        }

        public SequenceFlow<TimerSignatureDeadline> toTimerSignatureDeadline() {
          return new SequenceFlow<>(new ElementId("flow_awaitSignatureToSignatureDeadline"), null, null, false, new TimerSignatureDeadline());
        }
      }
    }

    public static final class GatewayCollectRejections extends AbstractFlowNode implements HasSuccessors<GatewayCollectRejections.Next>, HasOutgoingFlows<GatewayCollectRejections.OutgoingFlows> {
      public static final String ELEMENT_ID = "gateway_collectRejections";

      public GatewayCollectRejections() {
        super(new ElementId(ELEMENT_ID), "EXCLUSIVE_GATEWAY");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ServiceTaskSendRejection serviceTaskSendRejection() {
          return new ServiceTaskSendRejection();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskSendRejection> toServiceTaskSendRejection() {
          return new SequenceFlow<>(new ElementId("flow_collectRejectionsToSendRejection"), null, null, false, new ServiceTaskSendRejection());
        }
      }
    }

    public static final class GatewayFork extends AbstractFlowNode implements HasSuccessors<GatewayFork.Next>, HasOutgoingFlows<GatewayFork.OutgoingFlows> {
      public static final String ELEMENT_ID = "gateway_fork";

      public GatewayFork() {
        super(new ElementId(ELEMENT_ID), "PARALLEL_GATEWAY");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ServiceTaskIssueInsurancePolicy serviceTaskIssueInsurancePolicy() {
          return new ServiceTaskIssueInsurancePolicy();
        }

        public ServiceTaskOrderBike serviceTaskOrderBike() {
          return new ServiceTaskOrderBike();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskIssueInsurancePolicy> toServiceTaskIssueInsurancePolicy() {
          return new SequenceFlow<>(new ElementId("flow_forkToIssueInsurancePolicy"), null, null, false, new ServiceTaskIssueInsurancePolicy());
        }

        public SequenceFlow<ServiceTaskOrderBike> toServiceTaskOrderBike() {
          return new SequenceFlow<>(new ElementId("flow_forkToOrderBike"), null, null, false, new ServiceTaskOrderBike());
        }
      }
    }

    public static final class GatewayIsSolvent extends AbstractFlowNode implements HasSuccessors<GatewayIsSolvent.Next>, HasOutgoingFlows<GatewayIsSolvent.OutgoingFlows> {
      public static final String ELEMENT_ID = "gateway_isSolvent";

      public GatewayIsSolvent() {
        super(new ElementId(ELEMENT_ID), "EXCLUSIVE_GATEWAY", "Solvent?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public GatewayCollectRejections gatewayCollectRejections() {
          return new GatewayCollectRejections();
        }

        public SubProcessConcludeContract subProcessConcludeContract() {
          return new SubProcessConcludeContract();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayCollectRejections> toGatewayCollectRejections() {
          return new SequenceFlow<>(new ElementId("flow_isSolventToCollectRejections"), "No", "${!solvent}", false, new GatewayCollectRejections());
        }

        public SequenceFlow<SubProcessConcludeContract> toSubProcessConcludeContract() {
          return new SequenceFlow<>(new ElementId("flow_isSolventToConcludeContract"), "Yes", null, true, new SubProcessConcludeContract());
        }
      }
    }

    public static final class GatewayJoin extends AbstractFlowNode implements HasSuccessors<GatewayJoin.Next>, HasOutgoingFlows<GatewayJoin.OutgoingFlows> {
      public static final String ELEMENT_ID = "gateway_join";

      public GatewayJoin() {
        super(new ElementId(ELEMENT_ID), "PARALLEL_GATEWAY");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ReceiveTaskHandoverReported receiveTaskHandoverReported() {
          return new ReceiveTaskHandoverReported();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ReceiveTaskHandoverReported> toReceiveTaskHandoverReported() {
          return new SequenceFlow<>(new ElementId("flow_joinToHandoverReported"), null, null, false, new ReceiveTaskHandoverReported());
        }
      }
    }

    public static final class ReceiveTaskHandoverReported extends AbstractFlowNode implements HasSuccessors<ReceiveTaskHandoverReported.Next>, HasOutgoingFlows<ReceiveTaskHandoverReported.OutgoingFlows> {
      public static final String ELEMENT_ID = "receiveTask_handoverReported";

      public static final MessageName MESSAGE = Messages.MIRAVELO_HANDOVER_REPORTED;

      public ReceiveTaskHandoverReported() {
        super(new ElementId(ELEMENT_ID), "RECEIVE_TASK", "Await bike handover");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public TimerWithdrawalPeriodElapsed timerWithdrawalPeriodElapsed() {
          return new TimerWithdrawalPeriodElapsed();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<TimerWithdrawalPeriodElapsed> toTimerWithdrawalPeriodElapsed() {
          return new SequenceFlow<>(new ElementId("flow_handoverReportedToWithdrawalPeriodElapsed"), null, null, false, new TimerWithdrawalPeriodElapsed());
        }
      }
    }

    public static final class ServiceTaskCancelContract extends AbstractFlowNode {
      public static final String ELEMENT_ID = "serviceTask_cancelContract";

      public static final String JOB_TYPE = ServiceTasks.CANCEL_CONTRACT_DELEGATE;

      public ServiceTaskCancelContract() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Cancel contract");
      }
    }

    public static final class ServiceTaskCancelPolicy extends AbstractFlowNode {
      public static final String ELEMENT_ID = "serviceTask_cancelPolicy";

      public static final String JOB_TYPE = ServiceTasks.MIRAVELO_CANCEL_POLICY;

      public ServiceTaskCancelPolicy() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Cancel policy");
      }
    }

    public static final class ServiceTaskIssueInsurancePolicy extends AbstractFlowNode implements HasSuccessors<ServiceTaskIssueInsurancePolicy.Next>, HasOutgoingFlows<ServiceTaskIssueInsurancePolicy.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_issueInsurancePolicy";

      public static final String JOB_TYPE = ServiceTasks.IO_MIRAVELO_LEASING_ISSUE_INSURANCE_POLICY_DELEGATE;

      public ServiceTaskIssueInsurancePolicy() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Issue insurance policy");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.Input BIKE_ID = new VariableName.Input(Names.BIKE_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(Names.BIKE_IDS);

        public static final class Names {
          public static final String BIKE_ID = "bikeId";

          public static final String BIKE_IDS = "bikeIds";
        }
      }

      public static final class Next {
        public BoundaryCompensateInsurance boundaryCompensateInsurance() {
          return new BoundaryCompensateInsurance();
        }

        public GatewayJoin gatewayJoin() {
          return new GatewayJoin();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayJoin> toGatewayJoin() {
          return new SequenceFlow<>(new ElementId("flow_issueInsurancePolicyToJoin"), null, null, false, new GatewayJoin());
        }
      }
    }

    public static final class ServiceTaskOrderBike extends AbstractFlowNode implements HasSuccessors<ServiceTaskOrderBike.Next>, HasOutgoingFlows<ServiceTaskOrderBike.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_orderBike";

      public static final String JOB_TYPE = ServiceTasks.MIRAVELO_ORDER_BIKE;

      public ServiceTaskOrderBike() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Order bike");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.Input BIKE_ID = new VariableName.Input(Names.BIKE_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(Names.BIKE_IDS);

        public static final class Names {
          public static final String BIKE_ID = "bikeId";

          public static final String BIKE_IDS = "bikeIds";
        }
      }

      public static final class Next {
        public BoundaryCompensateOrder boundaryCompensateOrder() {
          return new BoundaryCompensateOrder();
        }

        public GatewayJoin gatewayJoin() {
          return new GatewayJoin();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayJoin> toGatewayJoin() {
          return new SequenceFlow<>(new ElementId("flow_orderBikeToJoin"), null, null, false, new GatewayJoin());
        }
      }
    }

    public static final class ServiceTaskSendCancellationConfirmation extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendCancellationConfirmation.Next>, HasOutgoingFlows<ServiceTaskSendCancellationConfirmation.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_sendCancellationConfirmation";

      public static final String JOB_TYPE = ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION;

      public ServiceTaskSendCancellationConfirmation() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Send cancellation confirmation");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventApplicationCancelled endEventApplicationCancelled() {
          return new EndEventApplicationCancelled();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventApplicationCancelled> toEndEventApplicationCancelled() {
          return new SequenceFlow<>(new ElementId("flow_sendCancellationConfirmationToApplicationCancelled"), null, null, false, new EndEventApplicationCancelled());
        }
      }
    }

    public static final class ServiceTaskSendContract extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendContract.Next>, HasOutgoingFlows<ServiceTaskSendContract.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_sendContract";

      public static final String JOB_TYPE = ServiceTasks.SEND_CONTRACT_DELEGATE;

      public ServiceTaskSendContract() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Send contract");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(Names.APPLICATION_ID);

        public static final VariableName.Output CONTRACT_ID = new VariableName.Output(Names.CONTRACT_ID);

        public static final class Names {
          public static final String APPLICATION_ID = "applicationId";

          public static final String CONTRACT_ID = "contractId";
        }
      }

      public static final class Next {
        public GatewayAwaitSignature gatewayAwaitSignature() {
          return new GatewayAwaitSignature();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayAwaitSignature> toGatewayAwaitSignature() {
          return new SequenceFlow<>(new ElementId("flow_sendContractToAwaitSignature"), null, null, false, new GatewayAwaitSignature());
        }
      }
    }

    public static final class ServiceTaskSendRejection extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendRejection.Next>, HasOutgoingFlows<ServiceTaskSendRejection.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_sendRejection";

      public static final String JOB_TYPE = ServiceTasks.MIRAVELO_SEND_REJECTION;

      public ServiceTaskSendRejection() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Send rejection");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventApplicationRejected endEventApplicationRejected() {
          return new EndEventApplicationRejected();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventApplicationRejected> toEndEventApplicationRejected() {
          return new SequenceFlow<>(new ElementId("flow_sendRejectionToApplicationRejected"), null, null, false, new EndEventApplicationRejected());
        }
      }
    }

    public static final class ServiceTaskSendReminderMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendReminderMail.Next>, HasOutgoingFlows<ServiceTaskSendReminderMail.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_sendReminderMail";

      public static final String JOB_TYPE = ServiceTasks.MAIL_SERVICE_SEND_REMINDER_APPLICATION_ID_;

      public ServiceTaskSendReminderMail() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Send reminder mail");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventCustomerReminded endEventCustomerReminded() {
          return new EndEventCustomerReminded();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventCustomerReminded> toEndEventCustomerReminded() {
          return new SequenceFlow<>(new ElementId("flow_sendReminderMailToCustomerReminded"), null, null, false, new EndEventCustomerReminded());
        }
      }
    }

    public static final class ServiceTaskValidateApplication extends AbstractFlowNode implements HasSuccessors<ServiceTaskValidateApplication.Next>, HasOutgoingFlows<ServiceTaskValidateApplication.OutgoingFlows> {
      public static final String ELEMENT_ID = "serviceTask_validateApplication";

      public static final String JOB_TYPE = ServiceTasks.VALIDATE_APPLICATION_DELEGATE;

      public ServiceTaskValidateApplication() {
        super(new ElementId(ELEMENT_ID), "SERVICE_TASK", "Validate application");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public BoundaryApplicationInvalid boundaryApplicationInvalid() {
          return new BoundaryApplicationInvalid();
        }

        public BusinessRuleTaskCheckCreditRating businessRuleTaskCheckCreditRating() {
          return new BusinessRuleTaskCheckCreditRating();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<BusinessRuleTaskCheckCreditRating> toBusinessRuleTaskCheckCreditRating(
            ) {
          return new SequenceFlow<>(new ElementId("flow_validateApplicationToCheckCreditRating"), null, null, false, new BusinessRuleTaskCheckCreditRating());
        }
      }
    }

    public static final class StartEventAddressChanged extends AbstractFlowNode implements HasSuccessors<StartEventAddressChanged.Next>, HasOutgoingFlows<StartEventAddressChanged.OutgoingFlows> {
      public static final String ELEMENT_ID = "startEvent_addressChanged";

      public static final MessageName MESSAGE = Messages.MIRAVELO_ADDRESS_CHANGED;

      public StartEventAddressChanged() {
        super(new ElementId(ELEMENT_ID), "MESSAGE_START_EVENT", "Address changed");
      }

      public boolean isInterrupting() {
        return false;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.Input CITY = new VariableName.Input(Names.CITY);

        public static final VariableName.Input STREET = new VariableName.Input(Names.STREET);

        public static final class Names {
          public static final String CITY = "city";

          public static final String STREET = "street";
        }
      }

      public static final class Next {
        public UserTaskUpdateDeliveryAddress userTaskUpdateDeliveryAddress() {
          return new UserTaskUpdateDeliveryAddress();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<UserTaskUpdateDeliveryAddress> toUserTaskUpdateDeliveryAddress() {
          return new SequenceFlow<>(new ElementId("flow_addressChangedToUpdateDeliveryAddress"), null, null, false, new UserTaskUpdateDeliveryAddress());
        }
      }
    }

    public static final class StartEventApplicationWithdrawn extends AbstractFlowNode implements HasSuccessors<StartEventApplicationWithdrawn.Next>, HasOutgoingFlows<StartEventApplicationWithdrawn.OutgoingFlows> {
      public static final String ELEMENT_ID = "startEvent_applicationWithdrawn";

      public static final MessageName MESSAGE = Messages.MIRAVELO_APPLICATION_WITHDRAWN;

      public StartEventApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), "MESSAGE_START_EVENT", "Application withdrawn");
      }

      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EventReverseApplication eventReverseApplication() {
          return new EventReverseApplication();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EventReverseApplication> toEventReverseApplication() {
          return new SequenceFlow<>(new ElementId("flow_applicationWithdrawnToReverseApplication"), null, null, false, new EventReverseApplication());
        }
      }
    }

    public static final class StartEventCustomerEligible extends AbstractFlowNode implements HasSuccessors<StartEventCustomerEligible.Next>, HasOutgoingFlows<StartEventCustomerEligible.OutgoingFlows> {
      public static final String ELEMENT_ID = "startEvent_customerEligible";

      public StartEventCustomerEligible() {
        super(new ElementId(ELEMENT_ID), "START_EVENT", "Customer eligible");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ServiceTaskSendContract serviceTaskSendContract() {
          return new ServiceTaskSendContract();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskSendContract> toServiceTaskSendContract() {
          return new SequenceFlow<>(new ElementId("flow_customerEligibleToSendContract"), null, null, false, new ServiceTaskSendContract());
        }
      }
    }

    public static final class StartEventLeasingRequestReceived extends AbstractFlowNode implements HasSuccessors<StartEventLeasingRequestReceived.Next>, HasOutgoingFlows<StartEventLeasingRequestReceived.OutgoingFlows> {
      public static final String ELEMENT_ID = "startEvent_leasingRequestReceived";

      public static final MessageName MESSAGE = Messages.MIRAVELO_LEASING_REQUEST_RECEIVED;

      public StartEventLeasingRequestReceived() {
        super(new ElementId(ELEMENT_ID), "MESSAGE_START_EVENT", "Leasing request received");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.Input AGE = new VariableName.Input(Names.AGE);

        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(Names.APPLICATION_ID);

        public static final VariableName.Input BIKE_IDS = new VariableName.Input(Names.BIKE_IDS);

        public static final VariableName.Input MONTHLY_NET_INCOME = new VariableName.Input(Names.MONTHLY_NET_INCOME);

        public static final class Names {
          public static final String AGE = "age";

          public static final String APPLICATION_ID = "applicationId";

          public static final String BIKE_IDS = "bikeIds";

          public static final String MONTHLY_NET_INCOME = "monthlyNetIncome";
        }
      }

      public static final class Next {
        public ServiceTaskValidateApplication serviceTaskValidateApplication() {
          return new ServiceTaskValidateApplication();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskValidateApplication> toServiceTaskValidateApplication() {
          return new SequenceFlow<>(new ElementId("flow_leasingRequestReceivedToValidateApplication"), null, null, false, new ServiceTaskValidateApplication());
        }
      }
    }

    public static final class SubProcessAddressChanged extends AbstractFlowNode implements FlowScope<SubProcessAddressChanged.Start> {
      public static final String ELEMENT_ID = "subProcess_addressChanged";

      public SubProcessAddressChanged() {
        super(new ElementId(ELEMENT_ID), "EVENT_SUB_PROCESS", "Delivery address changed");
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventAddressChanged startEventAddressChanged() {
          return new StartEventAddressChanged();
        }
      }
    }

    public static final class SubProcessApplicationWithdrawn extends AbstractFlowNode implements FlowScope<SubProcessApplicationWithdrawn.Start> {
      public static final String ELEMENT_ID = "subProcess_applicationWithdrawn";

      public SubProcessApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), "EVENT_SUB_PROCESS", "Application withdrawn");
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
          return new StartEventApplicationWithdrawn();
        }
      }
    }

    public static final class SubProcessConcludeContract extends AbstractFlowNode implements HasSuccessors<SubProcessConcludeContract.Next>, HasOutgoingFlows<SubProcessConcludeContract.OutgoingFlows>, FlowScope<SubProcessConcludeContract.Start> {
      public static final String ELEMENT_ID = "subProcess_concludeContract";

      public SubProcessConcludeContract() {
        super(new ElementId(ELEMENT_ID), "SUB_PROCESS", "Conclude contract");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Next {
        public BoundaryCompensateContract boundaryCompensateContract() {
          return new BoundaryCompensateContract();
        }

        public BoundaryContractNotSigned boundaryContractNotSigned() {
          return new BoundaryContractNotSigned();
        }

        public GatewayFork gatewayFork() {
          return new GatewayFork();
        }

        public TimerSignatureReminder timerSignatureReminder() {
          return new TimerSignatureReminder();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<GatewayFork> toGatewayFork() {
          return new SequenceFlow<>(new ElementId("flow_concludeContractToFork"), null, null, false, new GatewayFork());
        }
      }

      public static final class Start {
        public StartEventCustomerEligible startEventCustomerEligible() {
          return new StartEventCustomerEligible();
        }
      }
    }

    public static final class TimerSignatureDeadline extends AbstractFlowNode implements HasSuccessors<TimerSignatureDeadline.Next>, HasOutgoingFlows<TimerSignatureDeadline.OutgoingFlows> {
      public static final String ELEMENT_ID = "timer_signatureDeadline";

      public static final BpmnTimer TIMER = new BpmnTimer("Duration", "P14D");

      public TimerSignatureDeadline() {
        super(new ElementId(ELEMENT_ID), "TIMER_INTERMEDIATE_CATCH_EVENT", "14 days passed");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventContractNotSigned endEventContractNotSigned() {
          return new EndEventContractNotSigned();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventContractNotSigned> toEndEventContractNotSigned() {
          return new SequenceFlow<>(new ElementId("flow_signatureDeadlineToContractNotSigned"), null, null, false, new EndEventContractNotSigned());
        }
      }
    }

    public static final class TimerSignatureReminder extends AbstractFlowNode implements HasSuccessors<TimerSignatureReminder.Next>, HasOutgoingFlows<TimerSignatureReminder.OutgoingFlows>, BoundaryEvent<SubProcessConcludeContract> {
      public static final String ELEMENT_ID = "timer_signatureReminder";

      public static final BpmnTimer TIMER = new BpmnTimer("Duration", "P7D");

      public TimerSignatureReminder() {
        super(new ElementId(ELEMENT_ID), "TIMER_BOUNDARY_EVENT", "7 days passed");
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return new SubProcessConcludeContract();
      }

      @Override
      public boolean isInterrupting() {
        return false;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public ServiceTaskSendReminderMail serviceTaskSendReminderMail() {
          return new ServiceTaskSendReminderMail();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<ServiceTaskSendReminderMail> toServiceTaskSendReminderMail() {
          return new SequenceFlow<>(new ElementId("flow_signatureReminderToSendReminderMail"), null, null, false, new ServiceTaskSendReminderMail());
        }
      }
    }

    public static final class TimerWithdrawalPeriodElapsed extends AbstractFlowNode implements HasSuccessors<TimerWithdrawalPeriodElapsed.Next>, HasOutgoingFlows<TimerWithdrawalPeriodElapsed.OutgoingFlows> {
      public static final String ELEMENT_ID = "timer_withdrawalPeriodElapsed";

      public static final BpmnTimer TIMER = new BpmnTimer("Duration", "${withdrawalPeriod}");

      public TimerWithdrawalPeriodElapsed() {
        super(new ElementId(ELEMENT_ID), "TIMER_INTERMEDIATE_CATCH_EVENT", "Withdrawal period elapsed");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Next {
        public EndEventLeasingActive endEventLeasingActive() {
          return new EndEventLeasingActive();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventLeasingActive> toEndEventLeasingActive() {
          return new SequenceFlow<>(new ElementId("flow_withdrawalPeriodElapsedToLeasingActive"), null, null, false, new EndEventLeasingActive());
        }
      }
    }

    public static final class UserTaskUpdateDeliveryAddress extends AbstractFlowNode implements HasSuccessors<UserTaskUpdateDeliveryAddress.Next>, HasOutgoingFlows<UserTaskUpdateDeliveryAddress.OutgoingFlows> {
      public static final String ELEMENT_ID = "userTask_updateDeliveryAddress";

      public UserTaskUpdateDeliveryAddress() {
        super(new ElementId(ELEMENT_ID), "USER_TASK", "Update delivery address");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public OutgoingFlows getOutgoingFlows() {
        return new OutgoingFlows();
      }

      public static final class Variables {
        public static final VariableName.InOut DELIVERY_ADDRESS = new VariableName.InOut(Names.DELIVERY_ADDRESS);

        public static final class Names {
          public static final String DELIVERY_ADDRESS = "deliveryAddress";
        }
      }

      public static final class Next {
        public EndEventDeliveryAddressUpdated endEventDeliveryAddressUpdated() {
          return new EndEventDeliveryAddressUpdated();
        }
      }

      public static final class OutgoingFlows {
        public SequenceFlow<EndEventDeliveryAddressUpdated> toEndEventDeliveryAddressUpdated() {
          return new SequenceFlow<>(new ElementId("flow_updateDeliveryAddressToDeliveryAddressUpdated"), null, null, false, new EndEventDeliveryAddressUpdated());
        }
      }
    }
  }
}
