// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.BpmnErrorDefinition;
import java.util.List;

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
public final class Errors {
  public static final BpmnErrorDefinition MIRAVELO_APPLICATION_INVALID = new BpmnErrorDefinition("miravelo.applicationInvalid", "applicationInvalid");

  public static List<BpmnErrorDefinition> all() {
    return List.of(
        MIRAVELO_APPLICATION_INVALID);
  }
}
