// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.BpmnError;

public final class Errors {
  public static final BpmnError ERROR_INVALID_MAIL_500 = new BpmnError("Error_InvalidMail", "500");
}
