// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.BpmnEscalationDefinition;
import java.util.List;

/**
 * BPMN escalation definitions with name and code, as thrown and caught by the processes.
 */
public final class Escalations {
  public static final BpmnEscalationDefinition MIRAVELO_CONTRACT_NOT_SIGNED = new BpmnEscalationDefinition("miravelo.contractNotSigned", "contractNotSigned");

  public static List<BpmnEscalationDefinition> all() {
    return List.of(
        MIRAVELO_CONTRACT_NOT_SIGNED);
  }
}
