// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.MessageName;

/**
 * BPMN message names used to correlate messages to running process instances.
 */
public final class Messages {
  public static final MessageName MESSAGE_FORM_SUBMITTED = new MessageName("Message_FormSubmitted");
}
