// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnError;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.HasInner;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.Navigable;
import io.miragon.bpmn.runtime.NavigationScope;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SignalName;
import io.miragon.bpmn.runtime.VariableName;
import java.lang.Override;
import java.lang.String;

public final class NewsletterSubscriptionProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("newsletterSubscription");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.ZEEBE;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId CALL_ACTIVITY_ABORT_REGISTRATION = new ElementId("CallActivity_AbortRegistration");

    public static final ElementId ACTIVITY_CONFIRM_REGISTRATION = new ElementId("Activity_ConfirmRegistration");

    public static final ElementId ACTIVITY_SEND_CONFIRMATION_MAIL = new ElementId("Activity_SendConfirmationMail");

    public static final ElementId ACTIVITY_SEND_WELCOME_MAIL = new ElementId("Activity_SendWelcomeMail");

    public static final ElementId ACTIVITY_NOTIFY_COMMUNITY = new ElementId("Activity_NotifyCommunity");

    public static final ElementId GATEWAY_SPLIT_NOTIFICATIONS = new ElementId("Gateway_SplitNotifications");

    public static final ElementId GATEWAY_JOIN_NOTIFICATIONS = new ElementId("Gateway_JoinNotifications");

    public static final ElementId COMPENSATION_END_EVENT_REGISTRATION_ABORTED = new ElementId("CompensationEndEvent_RegistrationAborted");

    public static final ElementId COMPENSATION_EVENT_ON_SUBSCRIPTION_COUNTER = new ElementId("CompensationEvent_OnSubscriptionCounter");

    public static final ElementId COMPENSATION_TASK_DECREMENT_SUBSCRIPTION_COUNTER = new ElementId("CompensationTask_DecrementSubscriptionCounter");

    public static final ElementId END_EVENT_REGISTRATION_COMPLETED = new ElementId("EndEvent_RegistrationCompleted");

    public static final ElementId END_EVENT_REGISTRATION_NOT_POSSIBLE = new ElementId("EndEvent_RegistrationNotPossible");

    public static final ElementId END_EVENT_SUBSCRIPTION_CONFIRMED = new ElementId("EndEvent_SubscriptionConfirmed");

    public static final ElementId ERROR_EVENT_INVALID_MAIL = new ElementId("ErrorEvent_InvalidMail");

    public static final ElementId SERVICE_TASK_INCREMENT_SUBSCRIPTION_COUNTER = new ElementId("serviceTask_incrementSubscriptionCounter");

    public static final ElementId START_EVENT_REQUEST_RECEIVED = new ElementId("StartEvent_RequestReceived");

    public static final ElementId START_EVENT_SUBMIT_REGISTRATION_FORM = new ElementId("StartEvent_SubmitRegistrationForm");

    public static final ElementId SUB_PROCESS_CONFIRMATION = new ElementId("SubProcess_Confirmation");

    public static final ElementId TIMER_AFTER_3_DAYS = new ElementId("Timer_After3Days");

    public static final ElementId TIMER_EVERY_DAY = new ElementId("Timer_EveryDay");
  }

  /**
   * Call activities grouped by element. Each nested class exposes the called {@code PROCESS_ID} plus the variable mappings passed into ({@code Inputs}) and returned from ({@code Outputs}) the called process.
   */
  public static final class CallActivities {
    public static final class CallActivityAbortRegistration {
      public static final ProcessId PROCESS_ID = new ProcessId("abort-registration");

      public static final class Inputs {
        public static final InputOutputMapping CHILD_REASON_CODE = new InputOutputMapping("childReasonCode", null, "${reasonCode}");

        public static final InputOutputMapping CHILD_SUBSCRIPTION_ID = new InputOutputMapping("childSubscriptionId", "subscriptionId", null);
      }

      public static final class Outputs {
        public static final InputOutputMapping ABORT_RESULT = new InputOutputMapping("abortResult", "childAbortResult", null);
      }
    }
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  public static final class Messages {
    public static final MessageName MESSAGE_FORM_SUBMITTED = new MessageName("Message_FormSubmitted");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String NEWSLETTER_SEND_CONFIRMATION_MAIL = "#{newsletterSendConfirmationMail}";

    public static final String NEWSLETTER_SEND_WELCOME_MAIL = "${newsletterSendWelcomeMail}";

    public static final String COUNTER_CLASS = "counterClass";

    public static final String NEWSLETTER_NOTIFY_COMMUNITY = "newsletter.notifyCommunity";

    public static final String NEWSLETTER_REGISTRATION_COMPLETED = "newsletter.registrationCompleted";
  }

  public static final class Timers {
    public static final BpmnTimer TIMER_AFTER_3_DAYS = new BpmnTimer("Duration", "${testVariable}");

    public static final BpmnTimer TIMER_EVERY_DAY = new BpmnTimer("Duration", "PT1M");
  }

  public static final class Errors {
    public static final BpmnError ERROR_INVALID_MAIL = new BpmnError("Error_InvalidMail", "500");
  }

  public static final class Compensations {
    public static final ElementId COMPENSATION_END_EVENT_REGISTRATION_ABORTED = new ElementId("CompensationEndEvent_RegistrationAborted");

    public static final ElementId COMPENSATION_EVENT_ON_SUBSCRIPTION_COUNTER = new ElementId("CompensationEvent_OnSubscriptionCounter");
  }

  public static final class Signals {
    public static final SignalName SIGNAL_REGISTRATION_NOT_POSSIBLE = new SignalName("Signal_RegistrationNotPossible");
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: {@code VariableName.Input}, {@code VariableName.Output}, or {@code VariableName.InOut} when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (for example, a method accepting {@code VariableName.Output}) get compile-time direction enforcement.
   */
  public static final class Variables {
    public static final class ActivitySendConfirmationMail {
      public static final VariableName.Input SUBSCRIPTION_ID = new VariableName.Input("subscriptionId");

      public static final VariableName.Input TEST_VARIABLE = new VariableName.Input("testVariable");
    }

    public static final class ActivitySendWelcomeMail {
      public static final VariableName.InOut SUBSCRIPTION_ID = new VariableName.InOut("subscriptionId");
    }

    public static final class CallActivityAbortRegistration {
      public static final VariableName.Input SUBSCRIPTION_ID = new VariableName.Input("subscriptionId");
    }

    public static final class EndEventRegistrationCompleted {
      public static final VariableName.Output SUBSCRIPTION_ID = new VariableName.Output("subscriptionId");
    }

    public static final class StartEventRequestReceived {
      public static final VariableName.Output SUBSCRIPTION_ID = new VariableName.Output("subscriptionId");
    }

    public static final class StartEventSubmitRegistrationForm {
      public static final VariableName.Output SUBSCRIPTION_ID = new VariableName.Output("subscriptionId");
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_05_I_3_X_1_Y = new BpmnFlow("Flow_05i3x1y", null, "StartEvent_RequestReceived", "Activity_SendConfirmationMail", null, false);

    public static final BpmnFlow FLOW_09_CUVZP = new BpmnFlow("Flow_09cuvzp", null, "SubProcess_Confirmation", "Gateway_SplitNotifications", null, false);

    public static final BpmnFlow FLOW_0_I_2_CTUV = new BpmnFlow("Flow_0i2ctuv", null, "ErrorEvent_InvalidMail", "EndEvent_RegistrationNotPossible", null, false);

    public static final BpmnFlow FLOW_0_X_4_EWVB = new BpmnFlow("Flow_0x4ewvb", null, "Timer_EveryDay", "Activity_SendConfirmationMail", null, false);

    public static final BpmnFlow FLOW_0_ZDMT_0_T = new BpmnFlow("Flow_0zdmt0t", null, "serviceTask_incrementSubscriptionCounter", "SubProcess_Confirmation", null, false);

    public static final BpmnFlow FLOW_16_HUB_0_N = new BpmnFlow("Flow_16hub0n", null, "Gateway_SplitNotifications", "Activity_SendWelcomeMail", null, false);

    public static final BpmnFlow FLOW_1862_JD_8 = new BpmnFlow("Flow_1862jd8", null, "Gateway_JoinNotifications", "EndEvent_RegistrationCompleted", null, false);

    public static final BpmnFlow FLOW_1_BCKM_43 = new BpmnFlow("Flow_1bckm43", null, "Activity_SendConfirmationMail", "Activity_ConfirmRegistration", null, false);

    public static final BpmnFlow FLOW_1_BSB_8_NO = new BpmnFlow("Flow_1bsb8no", null, "CallActivity_AbortRegistration", "CompensationEndEvent_RegistrationAborted", null, false);

    public static final BpmnFlow FLOW_1_CPWE_57 = new BpmnFlow("Flow_1cpwe57", null, "Activity_ConfirmRegistration", "EndEvent_SubscriptionConfirmed", null, false);

    public static final BpmnFlow FLOW_1_CSFYYZ = new BpmnFlow("Flow_1csfyyz", null, "StartEvent_SubmitRegistrationForm", "serviceTask_incrementSubscriptionCounter", null, false);

    public static final BpmnFlow FLOW_1_DUWY_83 = new BpmnFlow("Flow_1duwy83", null, "Activity_NotifyCommunity", "Gateway_JoinNotifications", null, false);

    public static final BpmnFlow FLOW_1_I_7_HJID = new BpmnFlow("Flow_1i7hjid", null, "Activity_SendWelcomeMail", "Gateway_JoinNotifications", null, false);

    public static final BpmnFlow FLOW_1_L_1_LJ_4_M = new BpmnFlow("Flow_1l1lj4m", null, "Timer_After3Days", "CallActivity_AbortRegistration", null, false);

    public static final BpmnFlow FLOW_1_P_5_T_47_Z = new BpmnFlow("Flow_1p5t47z", null, "Gateway_SplitNotifications", "Activity_NotifyCommunity", null, false);
  }

  /**
   * Typed navigation over the process flow.
   * Each element is a node exposing its {@code id}, {@code elementType} and display {@code name}, plus the elements reachable from it as named accessors — so a full path is verified by the compiler and offered by autocomplete. A subprocess's interior is its nested {@code Inner} scope.
   * Intended for tooling, tests, and reasoning about the process shape.
   */
  public static final class Relations {
    public static ActivityNotifyCommunity activityNotifyCommunity() {
      return new ActivityNotifyCommunity();
    }

    public static ActivitySendWelcomeMail activitySendWelcomeMail() {
      return new ActivitySendWelcomeMail();
    }

    public static CallActivityAbortRegistration callActivityAbortRegistration() {
      return new CallActivityAbortRegistration();
    }

    public static CompensationEndEventRegistrationAborted compensationEndEventRegistrationAborted(
        ) {
      return new CompensationEndEventRegistrationAborted();
    }

    public static CompensationEventOnSubscriptionCounter compensationEventOnSubscriptionCounter() {
      return new CompensationEventOnSubscriptionCounter();
    }

    public static CompensationTaskDecrementSubscriptionCounter compensationTaskDecrementSubscriptionCounter(
        ) {
      return new CompensationTaskDecrementSubscriptionCounter();
    }

    public static EndEventRegistrationCompleted endEventRegistrationCompleted() {
      return new EndEventRegistrationCompleted();
    }

    public static EndEventRegistrationNotPossible endEventRegistrationNotPossible() {
      return new EndEventRegistrationNotPossible();
    }

    public static ErrorEventInvalidMail errorEventInvalidMail() {
      return new ErrorEventInvalidMail();
    }

    public static GatewayJoinNotifications gatewayJoinNotifications() {
      return new GatewayJoinNotifications();
    }

    public static GatewaySplitNotifications gatewaySplitNotifications() {
      return new GatewaySplitNotifications();
    }

    public static ServiceTaskIncrementSubscriptionCounter serviceTaskIncrementSubscriptionCounter(
        ) {
      return new ServiceTaskIncrementSubscriptionCounter();
    }

    public static StartEventSubmitRegistrationForm startEventSubmitRegistrationForm() {
      return new StartEventSubmitRegistrationForm();
    }

    public static SubProcessConfirmation subProcessConfirmation() {
      return new SubProcessConfirmation();
    }

    public static TimerAfter3Days timerAfter3Days() {
      return new TimerAfter3Days();
    }

    public static Next then() {
      return new Next();
    }

    public static final class Next {
      public StartEventSubmitRegistrationForm startEventSubmitRegistrationForm() {
        return new StartEventSubmitRegistrationForm();
      }
    }

    public static final class ActivityNotifyCommunity extends AbstractFlowNode implements Navigable<ActivityNotifyCommunity.Next> {
      public ActivityNotifyCommunity() {
        super(new ElementId("Activity_NotifyCommunity"), "SERVICE_TASK");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public GatewayJoinNotifications gatewayJoinNotifications() {
          return new GatewayJoinNotifications();
        }
      }
    }

    public static final class ActivitySendWelcomeMail extends AbstractFlowNode implements Navigable<ActivitySendWelcomeMail.Next> {
      public ActivitySendWelcomeMail() {
        super(new ElementId("Activity_SendWelcomeMail"), "SERVICE_TASK");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public GatewayJoinNotifications gatewayJoinNotifications() {
          return new GatewayJoinNotifications();
        }
      }
    }

    public static final class CallActivityAbortRegistration extends AbstractFlowNode implements Navigable<CallActivityAbortRegistration.Next> {
      public final ProcessId calledProcess = new ProcessId("abort-registration");

      public CallActivityAbortRegistration() {
        super(new ElementId("CallActivity_AbortRegistration"), "CALL_ACTIVITY");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public CompensationEndEventRegistrationAborted compensationEndEventRegistrationAborted() {
          return new CompensationEndEventRegistrationAborted();
        }
      }
    }

    public static final class CompensationEndEventRegistrationAborted extends AbstractFlowNode {
      public CompensationEndEventRegistrationAborted() {
        super(new ElementId("CompensationEndEvent_RegistrationAborted"), "COMPENSATION_END_EVENT");
      }
    }

    public static final class CompensationEventOnSubscriptionCounter extends AbstractFlowNode {
      public CompensationEventOnSubscriptionCounter() {
        super(new ElementId("CompensationEvent_OnSubscriptionCounter"), "COMPENSATION_BOUNDARY_EVENT");
      }
    }

    public static final class CompensationTaskDecrementSubscriptionCounter extends AbstractFlowNode {
      public CompensationTaskDecrementSubscriptionCounter() {
        super(new ElementId("CompensationTask_DecrementSubscriptionCounter"), "TASK");
      }
    }

    public static final class EndEventRegistrationCompleted extends AbstractFlowNode {
      public EndEventRegistrationCompleted() {
        super(new ElementId("EndEvent_RegistrationCompleted"), "END_EVENT");
      }
    }

    public static final class EndEventRegistrationNotPossible extends AbstractFlowNode {
      public EndEventRegistrationNotPossible() {
        super(new ElementId("EndEvent_RegistrationNotPossible"), "SIGNAL_END_EVENT");
      }
    }

    public static final class ErrorEventInvalidMail extends AbstractFlowNode implements Navigable<ErrorEventInvalidMail.Next> {
      public ErrorEventInvalidMail() {
        super(new ElementId("ErrorEvent_InvalidMail"), "ERROR_BOUNDARY_EVENT");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public EndEventRegistrationNotPossible endEventRegistrationNotPossible() {
          return new EndEventRegistrationNotPossible();
        }
      }
    }

    public static final class GatewayJoinNotifications extends AbstractFlowNode implements Navigable<GatewayJoinNotifications.Next> {
      public GatewayJoinNotifications() {
        super(new ElementId("Gateway_JoinNotifications"), "PARALLEL_GATEWAY");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public EndEventRegistrationCompleted endEventRegistrationCompleted() {
          return new EndEventRegistrationCompleted();
        }
      }
    }

    public static final class GatewaySplitNotifications extends AbstractFlowNode implements Navigable<GatewaySplitNotifications.Next> {
      public GatewaySplitNotifications() {
        super(new ElementId("Gateway_SplitNotifications"), "PARALLEL_GATEWAY");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public ActivityNotifyCommunity activityNotifyCommunity() {
          return new ActivityNotifyCommunity();
        }

        public ActivitySendWelcomeMail activitySendWelcomeMail() {
          return new ActivitySendWelcomeMail();
        }
      }
    }

    public static final class ServiceTaskIncrementSubscriptionCounter extends AbstractFlowNode implements Navigable<ServiceTaskIncrementSubscriptionCounter.Next> {
      public ServiceTaskIncrementSubscriptionCounter() {
        super(new ElementId("serviceTask_incrementSubscriptionCounter"), "SERVICE_TASK");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public CompensationEventOnSubscriptionCounter compensationEventOnSubscriptionCounter() {
          return new CompensationEventOnSubscriptionCounter();
        }

        public SubProcessConfirmation subProcessConfirmation() {
          return new SubProcessConfirmation();
        }
      }
    }

    public static final class StartEventSubmitRegistrationForm extends AbstractFlowNode implements Navigable<StartEventSubmitRegistrationForm.Next> {
      public StartEventSubmitRegistrationForm() {
        super(new ElementId("StartEvent_SubmitRegistrationForm"), "MESSAGE_START_EVENT");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public ServiceTaskIncrementSubscriptionCounter serviceTaskIncrementSubscriptionCounter() {
          return new ServiceTaskIncrementSubscriptionCounter();
        }
      }
    }

    public static final class SubProcessConfirmation extends AbstractFlowNode implements Navigable<SubProcessConfirmation.Next>, HasInner<SubProcessConfirmation.Inner> {
      public SubProcessConfirmation() {
        super(new ElementId("SubProcess_Confirmation"), "SUB_PROCESS");
      }

      @Override
      public Next then() {
        return new Next();
      }

      @Override
      public SubProcessConfirmation.Inner inner() {
        return new SubProcessConfirmation.Inner();
      }

      public static final class Next {
        public ErrorEventInvalidMail errorEventInvalidMail() {
          return new ErrorEventInvalidMail();
        }

        public GatewaySplitNotifications gatewaySplitNotifications() {
          return new GatewaySplitNotifications();
        }

        public TimerAfter3Days timerAfter3Days() {
          return new TimerAfter3Days();
        }
      }

      public static final class Inner implements NavigationScope<SubProcessConfirmation.Inner.Next> {
        public ActivityConfirmRegistration activityConfirmRegistration() {
          return new ActivityConfirmRegistration();
        }

        public ActivitySendConfirmationMail activitySendConfirmationMail() {
          return new ActivitySendConfirmationMail();
        }

        public EndEventSubscriptionConfirmed endEventSubscriptionConfirmed() {
          return new EndEventSubscriptionConfirmed();
        }

        public StartEventRequestReceived startEventRequestReceived() {
          return new StartEventRequestReceived();
        }

        public TimerEveryDay timerEveryDay() {
          return new TimerEveryDay();
        }

        @Override
        public Next then() {
          return new Next();
        }

        public static final class Next {
          public StartEventRequestReceived startEventRequestReceived() {
            return new StartEventRequestReceived();
          }
        }

        public static final class ActivityConfirmRegistration extends AbstractFlowNode implements Navigable<ActivityConfirmRegistration.Next> {
          public final String name = "Confirm registration";

          public ActivityConfirmRegistration() {
            super(new ElementId("Activity_ConfirmRegistration"), "RECEIVE_TASK");
          }

          @Override
          public Next then() {
            return new Next();
          }

          public static final class Next {
            public EndEventSubscriptionConfirmed endEventSubscriptionConfirmed() {
              return new EndEventSubscriptionConfirmed();
            }

            public TimerEveryDay timerEveryDay() {
              return new TimerEveryDay();
            }
          }
        }

        public static final class ActivitySendConfirmationMail extends AbstractFlowNode implements Navigable<ActivitySendConfirmationMail.Next> {
          public ActivitySendConfirmationMail() {
            super(new ElementId("Activity_SendConfirmationMail"), "SERVICE_TASK");
          }

          @Override
          public Next then() {
            return new Next();
          }

          public static final class Next {
            public ActivityConfirmRegistration activityConfirmRegistration() {
              return new ActivityConfirmRegistration();
            }
          }
        }

        public static final class EndEventSubscriptionConfirmed extends AbstractFlowNode {
          public EndEventSubscriptionConfirmed() {
            super(new ElementId("EndEvent_SubscriptionConfirmed"), "END_EVENT");
          }
        }

        public static final class StartEventRequestReceived extends AbstractFlowNode implements Navigable<StartEventRequestReceived.Next> {
          public StartEventRequestReceived() {
            super(new ElementId("StartEvent_RequestReceived"), "START_EVENT");
          }

          @Override
          public Next then() {
            return new Next();
          }

          public static final class Next {
            public ActivitySendConfirmationMail activitySendConfirmationMail() {
              return new ActivitySendConfirmationMail();
            }
          }
        }

        public static final class TimerEveryDay extends AbstractFlowNode implements Navigable<TimerEveryDay.Next> {
          public TimerEveryDay() {
            super(new ElementId("Timer_EveryDay"), "TIMER_BOUNDARY_EVENT");
          }

          @Override
          public Next then() {
            return new Next();
          }

          public static final class Next {
            public ActivitySendConfirmationMail activitySendConfirmationMail() {
              return new ActivitySendConfirmationMail();
            }
          }
        }
      }
    }

    public static final class TimerAfter3Days extends AbstractFlowNode implements Navigable<TimerAfter3Days.Next> {
      public TimerAfter3Days() {
        super(new ElementId("Timer_After3Days"), "TIMER_BOUNDARY_EVENT");
      }

      @Override
      public Next then() {
        return new Next();
      }

      public static final class Next {
        public CallActivityAbortRegistration callActivityAbortRegistration() {
          return new CallActivityAbortRegistration();
        }
      }
    }
  }
}
