// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import java.util.List;

/**
 * Names of the process variables used in {@code @Variable(name = ProcessVariables.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ProcessVariables {
  public static final String AGE = "age";

  public static final String APPLICATION_ID = "applicationId";

  public static final String BIKE_ID = "bikeId";

  public static final String BIKE_IDS = "bikeIds";

  public static final String CANCELLATION_COSTS = "cancellationCosts";

  public static final String CANCELLATION_POSSIBLE = "cancellationPossible";

  public static final String CITY = "city";

  public static final String CONTRACT_ID = "contractId";

  public static final String DELIVERY_ADDRESS = "deliveryAddress";

  public static final String MONTHLY_NET_INCOME = "monthlyNetIncome";

  public static final String ORDER_IDS = "orderIds";

  public static final String STREET = "street";

  private ProcessVariables() {
  }

  public static List<String> all() {
    return List.of(
        AGE,
        APPLICATION_ID,
        BIKE_ID,
        BIKE_IDS,
        CANCELLATION_COSTS,
        CANCELLATION_POSSIBLE,
        CITY,
        CONTRACT_ID,
        DELIVERY_ADDRESS,
        MONTHLY_NET_INCOME,
        ORDER_IDS,
        STREET);
  }
}
