// Generated by bpmn-to-code
package io.miragon.bpmn.runtime.example;

import java.lang.String;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String NEWSLETTER_SEND_CONFIRMATION_MAIL = "#{newsletterSendConfirmationMail}";

  public static final String NEWSLETTER_SEND_WELCOME_MAIL = "${newsletterSendWelcomeMail}";

  public static final String COUNTER_CLASS = "counterClass";

  public static final String NEWSLETTER_NOTIFY_COMMUNITY = "newsletter.notifyCommunity";

  public static final String NEWSLETTER_REGISTRATION_COMPLETED = "newsletter.registrationCompleted";
}
