package io.miragon.bpmn.domain

/**
 * What every generated source file says about itself, whatever its language.
 * A file carrying it is owned by the generator, which may overwrite or remove it.
 */
internal object GeneratedFileHeader {

    const val COMMENT = "Generated by bpmn-to-code"
    const val LINE = "// $COMMENT"

    private const val LEADING_LINE_COUNT = 2

    fun isCarriedBy(lines: Sequence<String>): Boolean {
        val leadingLines = lines.take(LEADING_LINE_COUNT)
        return leadingLines.any { it.trim() == LINE }
    }
}
