package io.miragon.bpmn.domain

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource

class GeneratedFileHeaderTest {

    @ParameterizedTest(name = "{0} -> {1}")
    @CsvSource(
        "// Generated by bpmn-to-code|package com.example, true",
        "// <auto-generated/>|// Generated by bpmn-to-code|#nullable enable, true",
        "package com.example||// Generated by bpmn-to-code, false",
        "// Generated by bpmn-to-code from the BPMN model, false",
        "package com.example, false",
    )
    fun `isCarriedBy recognises the header only on the leading lines`(content: String, expected: Boolean) {
        // given: the lines of a source file
        val lines = content.split("|").asSequence()

        // when: checking for the header
        val carriesHeader = GeneratedFileHeader.isCarriedBy(lines)

        // then: only an exact header on the first two lines counts
        assertThat(carriesHeader).isEqualTo(expected)
    }
}
