// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.AttachedBoundaryEvent
import io.miragon.bpmn.runtime.BoundaryEvent
import io.miragon.bpmn.runtime.BpmnElementType
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnErrorDefinition
import io.miragon.bpmn.runtime.BpmnEscalationDefinition
import io.miragon.bpmn.runtime.BpmnEventType
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.CallActivity
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.ErrorEvent
import io.miragon.bpmn.runtime.EscalationEvent
import io.miragon.bpmn.runtime.Event
import io.miragon.bpmn.runtime.FlowNode
import io.miragon.bpmn.runtime.FlowScope
import io.miragon.bpmn.runtime.HasJobType
import io.miragon.bpmn.runtime.HasMessage
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.InputOutputMapping
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.SequenceFlows
import io.miragon.bpmn.runtime.TimerEvent
import io.miragon.bpmn.runtime.TimerType
import io.miragon.bpmn.runtime.VariableName
import kotlin.Boolean
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

object BikeLeasingProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("bikeLeasing")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * Typed navigation over the process flow: one nested object per BPMN element.
   */
  object FlowNodes {
    val entries: List<FlowNode> = listOf(
      BoundaryApplicationInvalid,
      BoundaryCompensateContract,
      BoundaryCompensateInsurance,
      BoundaryCompensateOrder,
      BoundaryContractNotSigned,
      BusinessRuleTaskCheckCreditRating,
      CallActivityCancelBikeOrder,
      EndEventApplicationCancelled,
      EndEventApplicationRejected,
      EndEventContractConcluded,
      EndEventContractNotSigned,
      EndEventCustomerReminded,
      EndEventDeliveryAddressUpdated,
      EndEventLeasingActive,
      EventContractSigned,
      EventReverseApplication,
      GatewayAwaitSignature,
      GatewayCollectRejections,
      GatewayFork,
      GatewayIsSolvent,
      GatewayJoin,
      ReceiveTaskHandoverReported,
      ServiceTaskCancelContract,
      ServiceTaskCancelPolicy,
      ServiceTaskIssueInsurancePolicy,
      ServiceTaskOrderBike,
      ServiceTaskSendCancellationConfirmation,
      ServiceTaskSendContract,
      ServiceTaskSendRejection,
      ServiceTaskSendReminderMail,
      ServiceTaskValidateApplication,
      StartEventAddressChanged,
      StartEventApplicationWithdrawn,
      StartEventCustomerEligible,
      StartEventLeasingRequestReceived,
      SubProcessAddressChanged,
      SubProcessApplicationWithdrawn,
      SubProcessConcludeContract,
      TimerSignatureDeadline,
      TimerSignatureReminder,
      TimerWithdrawalPeriodElapsed,
      UserTaskUpdateDeliveryAddress,
    )

    object BoundaryApplicationInvalid : AbstractFlowNode(
      id = ElementId(BoundaryApplicationInvalid.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Application invalid",
    ), HasSuccessors<BoundaryApplicationInvalid.Next>,
        BoundaryEvent<ServiceTaskValidateApplication>, ErrorEvent {
      override val eventType: BpmnEventType = BpmnEventType.ERROR

      const val ELEMENT_ID: String = "boundary_applicationInvalid"

      override val error: BpmnErrorDefinition = Errors.MIRAVELO_APPLICATION_INVALID

      override val attachedTo: ServiceTaskValidateApplication
        get() = ServiceTaskValidateApplication

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val gatewayCollectRejections: SequenceFlows<GatewayCollectRejections>
          get() = SequenceFlows.single(flowId = ElementId("flow_applicationInvalidToCollectRejections"), target = GatewayCollectRejections)
      }
    }

    object BoundaryCompensateContract : AbstractFlowNode(
      id = ElementId(BoundaryCompensateContract.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Contract to revoke",
    ), BoundaryEvent<SubProcessConcludeContract> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "boundary_compensateContract"

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = true
    }

    object BoundaryCompensateInsurance : AbstractFlowNode(
      id = ElementId(BoundaryCompensateInsurance.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Policy to cancel",
    ), BoundaryEvent<ServiceTaskIssueInsurancePolicy> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "boundary_compensateInsurance"

      override val attachedTo: ServiceTaskIssueInsurancePolicy
        get() = ServiceTaskIssueInsurancePolicy

      override val isInterrupting: Boolean = true
    }

    object BoundaryCompensateOrder : AbstractFlowNode(
      id = ElementId(BoundaryCompensateOrder.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Order to cancel",
    ), BoundaryEvent<ServiceTaskOrderBike> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "boundary_compensateOrder"

      override val attachedTo: ServiceTaskOrderBike
        get() = ServiceTaskOrderBike

      override val isInterrupting: Boolean = true
    }

    object BoundaryContractNotSigned : AbstractFlowNode(
      id = ElementId(BoundaryContractNotSigned.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Contract not signed",
    ), HasSuccessors<BoundaryContractNotSigned.Next>, BoundaryEvent<SubProcessConcludeContract>,
        EscalationEvent {
      override val eventType: BpmnEventType = BpmnEventType.ESCALATION

      const val ELEMENT_ID: String = "boundary_contractNotSigned"

      override val escalation: BpmnEscalationDefinition = Escalations.MIRAVELO_CONTRACT_NOT_SIGNED

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val gatewayCollectRejections: SequenceFlows<GatewayCollectRejections>
          get() = SequenceFlows.single(flowId = ElementId("flow_contractNotSignedToCollectRejections"), target = GatewayCollectRejections)
      }
    }

    object BusinessRuleTaskCheckCreditRating : AbstractFlowNode(
      id = ElementId(BusinessRuleTaskCheckCreditRating.ELEMENT_ID),
      elementType = BpmnElementType.BUSINESS_RULE_TASK,
      name = "Check credit rating",
    ), HasSuccessors<BusinessRuleTaskCheckCreditRating.Next> {
      const val ELEMENT_ID: String = "businessRuleTask_checkCreditRating"

      override val next: Next = Next

      object Next {
        val gatewayIsSolvent: SequenceFlows<GatewayIsSolvent>
          get() = SequenceFlows.single(flowId = ElementId("flow_checkCreditRatingToIsSolvent"), target = GatewayIsSolvent)
      }
    }

    object CallActivityCancelBikeOrder : AbstractFlowNode(
      id = ElementId(CallActivityCancelBikeOrder.ELEMENT_ID),
      elementType = BpmnElementType.CALL_ACTIVITY,
      name = "Cancel bike order",
    ), CallActivity {
      const val ELEMENT_ID: String = "callActivity_cancelBikeOrder"

      override val calledProcess: ProcessId = ProcessId("cancelBikeOrder")

      object Variables {
        val APPLICATION_ID: VariableName.Input =
            VariableName.Input(ProcessVariables.APPLICATION_ID)

        val CANCELLATION_COSTS: VariableName.Output =
            VariableName.Output(ProcessVariables.CANCELLATION_COSTS)

        val ORDER_IDS: VariableName.Input = VariableName.Input(ProcessVariables.ORDER_IDS)
      }

      object Inputs {
        val APPLICATION_ID: InputOutputMapping = InputOutputMapping(
          target = "applicationId",
          sourceExpression = $$"""${applicationId}""",
        )

        val ORDER_IDS: InputOutputMapping = InputOutputMapping(
          target = "orderIds",
          source = "orderIds",
        )
      }

      object Outputs {
        val CANCELLATION_COSTS: InputOutputMapping = InputOutputMapping(
          target = "cancellationCosts",
          source = "cancellationCosts",
        )
      }
    }

    object EndEventApplicationCancelled : AbstractFlowNode(
      id = ElementId(EndEventApplicationCancelled.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Application cancelled",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_applicationCancelled"
    }

    object EndEventApplicationRejected : AbstractFlowNode(
      id = ElementId(EndEventApplicationRejected.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Application rejected",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.TERMINATE

      const val ELEMENT_ID: String = "endEvent_applicationRejected"
    }

    object EndEventContractConcluded : AbstractFlowNode(
      id = ElementId(EndEventContractConcluded.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Contract concluded",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_contractConcluded"
    }

    object EndEventContractNotSigned : AbstractFlowNode(
      id = ElementId(EndEventContractNotSigned.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Contract not signed",
    ), Event, EscalationEvent {
      override val eventType: BpmnEventType = BpmnEventType.ESCALATION

      const val ELEMENT_ID: String = "endEvent_contractNotSigned"

      override val escalation: BpmnEscalationDefinition = Escalations.MIRAVELO_CONTRACT_NOT_SIGNED
    }

    object EndEventCustomerReminded : AbstractFlowNode(
      id = ElementId(EndEventCustomerReminded.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Customer reminded",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_customerReminded"
    }

    object EndEventDeliveryAddressUpdated : AbstractFlowNode(
      id = ElementId(EndEventDeliveryAddressUpdated.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Delivery address updated",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_deliveryAddressUpdated"
    }

    object EndEventLeasingActive : AbstractFlowNode(
      id = ElementId(EndEventLeasingActive.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Leasing active",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_leasingActive"
    }

    object EventContractSigned : AbstractFlowNode(
      id = ElementId(EventContractSigned.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "Contract signed",
    ), HasSuccessors<EventContractSigned.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "event_contractSigned"

      override val message: MessageName = Messages.MIRAVELO_CONTRACT_SIGNED

      override val next: Next = Next

      object Next {
        val endEventContractConcluded: SequenceFlows<EndEventContractConcluded>
          get() = SequenceFlows.single(flowId = ElementId("flow_contractSignedToContractConcluded"), target = EndEventContractConcluded)
      }
    }

    object EventReverseApplication : AbstractFlowNode(
      id = ElementId(EventReverseApplication.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_THROW_EVENT,
      name = "Application reversed",
    ), HasSuccessors<EventReverseApplication.Next>, Event {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_reverseApplication"

      override val next: Next = Next

      object Next {
        val serviceTaskSendCancellationConfirmation:
            SequenceFlows<ServiceTaskSendCancellationConfirmation>
          get() = SequenceFlows.single(flowId = ElementId("flow_reverseApplicationToSendCancellationConfirmation"), target = ServiceTaskSendCancellationConfirmation)
      }
    }

    object GatewayAwaitSignature : AbstractFlowNode(
      id = ElementId(GatewayAwaitSignature.ELEMENT_ID),
      elementType = BpmnElementType.EVENT_BASED_GATEWAY,
      name = "Await signature",
    ), HasSuccessors<GatewayAwaitSignature.Next> {
      const val ELEMENT_ID: String = "gateway_awaitSignature"

      override val next: Next = Next

      object Next {
        val eventContractSigned: SequenceFlows<EventContractSigned>
          get() = SequenceFlows.single(flowId = ElementId("flow_awaitSignatureToContractSigned"), target = EventContractSigned)

        val timerSignatureDeadline: SequenceFlows<TimerSignatureDeadline>
          get() = SequenceFlows.single(flowId = ElementId("flow_awaitSignatureToSignatureDeadline"), target = TimerSignatureDeadline)
      }
    }

    object GatewayCollectRejections : AbstractFlowNode(
      id = ElementId(GatewayCollectRejections.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
    ), HasSuccessors<GatewayCollectRejections.Next> {
      const val ELEMENT_ID: String = "gateway_collectRejections"

      override val next: Next = Next

      object Next {
        val serviceTaskSendRejection: SequenceFlows<ServiceTaskSendRejection>
          get() = SequenceFlows.single(flowId = ElementId("flow_collectRejectionsToSendRejection"), target = ServiceTaskSendRejection)
      }
    }

    object GatewayFork : AbstractFlowNode(
      id = ElementId(GatewayFork.ELEMENT_ID),
      elementType = BpmnElementType.PARALLEL_GATEWAY,
    ), HasSuccessors<GatewayFork.Next> {
      const val ELEMENT_ID: String = "gateway_fork"

      override val next: Next = Next

      object Next {
        val serviceTaskIssueInsurancePolicy: SequenceFlows<ServiceTaskIssueInsurancePolicy>
          get() = SequenceFlows.single(flowId = ElementId("flow_forkToIssueInsurancePolicy"), target = ServiceTaskIssueInsurancePolicy)

        val serviceTaskOrderBike: SequenceFlows<ServiceTaskOrderBike>
          get() = SequenceFlows.single(flowId = ElementId("flow_forkToOrderBike"), target = ServiceTaskOrderBike)
      }
    }

    object GatewayIsSolvent : AbstractFlowNode(
      id = ElementId(GatewayIsSolvent.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
      name = "Solvent?",
    ), HasSuccessors<GatewayIsSolvent.Next> {
      const val ELEMENT_ID: String = "gateway_isSolvent"

      override val next: Next = Next

      object Next {
        val gatewayCollectRejections: SequenceFlows<GatewayCollectRejections>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_isSolventToCollectRejections"),
            name = "No",
            conditionExpression = $$"""${!solvent}""",
            target = GatewayCollectRejections,
          )

        val subProcessConcludeContract: SequenceFlows<SubProcessConcludeContract>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_isSolventToConcludeContract"),
            name = "Yes",
            isDefault = true,
            target = SubProcessConcludeContract,
          )
      }
    }

    object GatewayJoin : AbstractFlowNode(
      id = ElementId(GatewayJoin.ELEMENT_ID),
      elementType = BpmnElementType.PARALLEL_GATEWAY,
    ), HasSuccessors<GatewayJoin.Next> {
      const val ELEMENT_ID: String = "gateway_join"

      override val next: Next = Next

      object Next {
        val receiveTaskHandoverReported: SequenceFlows<ReceiveTaskHandoverReported>
          get() = SequenceFlows.single(flowId = ElementId("flow_joinToHandoverReported"), target = ReceiveTaskHandoverReported)
      }
    }

    object ReceiveTaskHandoverReported : AbstractFlowNode(
      id = ElementId(ReceiveTaskHandoverReported.ELEMENT_ID),
      elementType = BpmnElementType.RECEIVE_TASK,
      name = "Await bike handover",
    ), HasSuccessors<ReceiveTaskHandoverReported.Next>, HasMessage {
      const val ELEMENT_ID: String = "receiveTask_handoverReported"

      override val message: MessageName = Messages.MIRAVELO_HANDOVER_REPORTED

      override val next: Next = Next

      object Next {
        val timerWithdrawalPeriodElapsed: SequenceFlows<TimerWithdrawalPeriodElapsed>
          get() = SequenceFlows.single(flowId = ElementId("flow_handoverReportedToWithdrawalPeriodElapsed"), target = TimerWithdrawalPeriodElapsed)
      }
    }

    object ServiceTaskCancelContract : AbstractFlowNode(
      id = ElementId(ServiceTaskCancelContract.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Cancel contract",
    ), HasJobType {
      const val ELEMENT_ID: String = "serviceTask_cancelContract"

      override val jobType: String = ServiceTasks.CANCEL_CONTRACT_DELEGATE
    }

    object ServiceTaskCancelPolicy : AbstractFlowNode(
      id = ElementId(ServiceTaskCancelPolicy.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Cancel policy",
    ), HasJobType {
      const val ELEMENT_ID: String = "serviceTask_cancelPolicy"

      override val jobType: String = ServiceTasks.MIRAVELO_CANCEL_POLICY
    }

    object ServiceTaskIssueInsurancePolicy : AbstractFlowNode(
      id = ElementId(ServiceTaskIssueInsurancePolicy.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Issue insurance policy",
    ), HasSuccessors<ServiceTaskIssueInsurancePolicy.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_issueInsurancePolicy"

      override val jobType: String =
          ServiceTasks.IO_MIRAVELO_LEASING_ISSUE_INSURANCE_POLICY_DELEGATE

      override val next: Next = Next

      object Variables {
        val BIKE_ID: VariableName.Input = VariableName.Input(ProcessVariables.BIKE_ID)

        val BIKE_IDS: VariableName.Input = VariableName.Input(ProcessVariables.BIKE_IDS)
      }

      object Next {
        val boundaryCompensateInsurance: AttachedBoundaryEvent<BoundaryCompensateInsurance>
          get() = AttachedBoundaryEvent(target = BoundaryCompensateInsurance)

        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(flowId = ElementId("flow_issueInsurancePolicyToJoin"), target = GatewayJoin)
      }
    }

    object ServiceTaskOrderBike : AbstractFlowNode(
      id = ElementId(ServiceTaskOrderBike.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Order bike",
    ), HasSuccessors<ServiceTaskOrderBike.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_orderBike"

      override val jobType: String = ServiceTasks.MIRAVELO_ORDER_BIKE

      override val next: Next = Next

      object Variables {
        val BIKE_ID: VariableName.Input = VariableName.Input(ProcessVariables.BIKE_ID)

        val BIKE_IDS: VariableName.Input = VariableName.Input(ProcessVariables.BIKE_IDS)
      }

      object Next {
        val boundaryCompensateOrder: AttachedBoundaryEvent<BoundaryCompensateOrder>
          get() = AttachedBoundaryEvent(target = BoundaryCompensateOrder)

        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(flowId = ElementId("flow_orderBikeToJoin"), target = GatewayJoin)
      }
    }

    object ServiceTaskSendCancellationConfirmation : AbstractFlowNode(
      id = ElementId(ServiceTaskSendCancellationConfirmation.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send cancellation confirmation",
    ), HasSuccessors<ServiceTaskSendCancellationConfirmation.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendCancellationConfirmation"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION

      override val next: Next = Next

      object Next {
        val endEventApplicationCancelled: SequenceFlows<EndEventApplicationCancelled>
          get() = SequenceFlows.single(flowId = ElementId("flow_sendCancellationConfirmationToApplicationCancelled"), target = EndEventApplicationCancelled)
      }
    }

    object ServiceTaskSendContract : AbstractFlowNode(
      id = ElementId(ServiceTaskSendContract.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send contract",
    ), HasSuccessors<ServiceTaskSendContract.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendContract"

      override val jobType: String = ServiceTasks.SEND_CONTRACT_DELEGATE

      override val next: Next = Next

      object Variables {
        val APPLICATION_ID: VariableName.Input =
            VariableName.Input(ProcessVariables.APPLICATION_ID)

        val CONTRACT_ID: VariableName.Output =
            VariableName.Output(ProcessVariables.CONTRACT_ID)
      }

      object Next {
        val gatewayAwaitSignature: SequenceFlows<GatewayAwaitSignature>
          get() = SequenceFlows.single(flowId = ElementId("flow_sendContractToAwaitSignature"), target = GatewayAwaitSignature)
      }
    }

    object ServiceTaskSendRejection : AbstractFlowNode(
      id = ElementId(ServiceTaskSendRejection.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send rejection",
    ), HasSuccessors<ServiceTaskSendRejection.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendRejection"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_REJECTION

      override val next: Next = Next

      object Next {
        val endEventApplicationRejected: SequenceFlows<EndEventApplicationRejected>
          get() = SequenceFlows.single(flowId = ElementId("flow_sendRejectionToApplicationRejected"), target = EndEventApplicationRejected)
      }
    }

    object ServiceTaskSendReminderMail : AbstractFlowNode(
      id = ElementId(ServiceTaskSendReminderMail.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send reminder mail",
    ), HasSuccessors<ServiceTaskSendReminderMail.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendReminderMail"

      override val jobType: String = ServiceTasks.MAIL_SERVICE_SEND_REMINDER_APPLICATION_ID_

      override val next: Next = Next

      object Next {
        val endEventCustomerReminded: SequenceFlows<EndEventCustomerReminded>
          get() = SequenceFlows.single(flowId = ElementId("flow_sendReminderMailToCustomerReminded"), target = EndEventCustomerReminded)
      }
    }

    object ServiceTaskValidateApplication : AbstractFlowNode(
      id = ElementId(ServiceTaskValidateApplication.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Validate application",
    ), HasSuccessors<ServiceTaskValidateApplication.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_validateApplication"

      override val jobType: String = ServiceTasks.VALIDATE_APPLICATION_DELEGATE

      override val next: Next = Next

      object Next {
        val boundaryApplicationInvalid: AttachedBoundaryEvent<BoundaryApplicationInvalid>
          get() = AttachedBoundaryEvent(target = BoundaryApplicationInvalid)

        val businessRuleTaskCheckCreditRating:
            SequenceFlows<BusinessRuleTaskCheckCreditRating>
          get() = SequenceFlows.single(flowId = ElementId("flow_validateApplicationToCheckCreditRating"), target = BusinessRuleTaskCheckCreditRating)
      }
    }

    object StartEventAddressChanged : AbstractFlowNode(
      id = ElementId(StartEventAddressChanged.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Address changed",
    ), HasSuccessors<StartEventAddressChanged.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "startEvent_addressChanged"

      override val message: MessageName = Messages.MIRAVELO_ADDRESS_CHANGED

      val isInterrupting: Boolean = false

      override val next: Next = Next

      object Variables {
        val CITY: VariableName.Input = VariableName.Input(ProcessVariables.CITY)

        val STREET: VariableName.Input = VariableName.Input(ProcessVariables.STREET)
      }

      object Next {
        val userTaskUpdateDeliveryAddress: SequenceFlows<UserTaskUpdateDeliveryAddress>
          get() = SequenceFlows.single(flowId = ElementId("flow_addressChangedToUpdateDeliveryAddress"), target = UserTaskUpdateDeliveryAddress)
      }
    }

    object StartEventApplicationWithdrawn : AbstractFlowNode(
      id = ElementId(StartEventApplicationWithdrawn.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Application withdrawn",
    ), HasSuccessors<StartEventApplicationWithdrawn.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "startEvent_applicationWithdrawn"

      override val message: MessageName = Messages.MIRAVELO_APPLICATION_WITHDRAWN

      val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val eventReverseApplication: SequenceFlows<EventReverseApplication>
          get() = SequenceFlows.single(flowId = ElementId("flow_applicationWithdrawnToReverseApplication"), target = EventReverseApplication)
      }
    }

    object StartEventCustomerEligible : AbstractFlowNode(
      id = ElementId(StartEventCustomerEligible.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Customer eligible",
    ), HasSuccessors<StartEventCustomerEligible.Next>, Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "startEvent_customerEligible"

      override val next: Next = Next

      object Next {
        val serviceTaskSendContract: SequenceFlows<ServiceTaskSendContract>
          get() = SequenceFlows.single(flowId = ElementId("flow_customerEligibleToSendContract"), target = ServiceTaskSendContract)
      }
    }

    object StartEventLeasingRequestReceived : AbstractFlowNode(
      id = ElementId(StartEventLeasingRequestReceived.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Leasing request received",
    ), HasSuccessors<StartEventLeasingRequestReceived.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "startEvent_leasingRequestReceived"

      override val message: MessageName = Messages.MIRAVELO_LEASING_REQUEST_RECEIVED

      override val next: Next = Next

      object Variables {
        val AGE: VariableName.Input = VariableName.Input(ProcessVariables.AGE)

        val APPLICATION_ID: VariableName.Input =
            VariableName.Input(ProcessVariables.APPLICATION_ID)

        val BIKE_IDS: VariableName.Input = VariableName.Input(ProcessVariables.BIKE_IDS)

        val MONTHLY_NET_INCOME: VariableName.Input =
            VariableName.Input(ProcessVariables.MONTHLY_NET_INCOME)
      }

      object Next {
        val serviceTaskValidateApplication: SequenceFlows<ServiceTaskValidateApplication>
          get() = SequenceFlows.single(flowId = ElementId("flow_leasingRequestReceivedToValidateApplication"), target = ServiceTaskValidateApplication)
      }
    }

    object SubProcessAddressChanged : AbstractFlowNode(
      id = ElementId(SubProcessAddressChanged.ELEMENT_ID),
      elementType = BpmnElementType.EVENT_SUB_PROCESS,
      name = "Delivery address changed",
    ), FlowScope<SubProcessAddressChanged.Start> {
      const val ELEMENT_ID: String = "subProcess_addressChanged"

      override val startEvents: Start = Start

      object Start {
        val startEventAddressChanged: StartEventAddressChanged
          get() = StartEventAddressChanged
      }
    }

    object SubProcessApplicationWithdrawn : AbstractFlowNode(
      id = ElementId(SubProcessApplicationWithdrawn.ELEMENT_ID),
      elementType = BpmnElementType.EVENT_SUB_PROCESS,
      name = "Application withdrawn",
    ), FlowScope<SubProcessApplicationWithdrawn.Start> {
      const val ELEMENT_ID: String = "subProcess_applicationWithdrawn"

      override val startEvents: Start = Start

      object Start {
        val startEventApplicationWithdrawn: StartEventApplicationWithdrawn
          get() = StartEventApplicationWithdrawn
      }
    }

    object SubProcessConcludeContract : AbstractFlowNode(
      id = ElementId(SubProcessConcludeContract.ELEMENT_ID),
      elementType = BpmnElementType.SUB_PROCESS,
      name = "Conclude contract",
    ), HasSuccessors<SubProcessConcludeContract.Next>, FlowScope<SubProcessConcludeContract.Start> {
      const val ELEMENT_ID: String = "subProcess_concludeContract"

      override val next: Next = Next

      override val startEvents: Start = Start

      object Next {
        val boundaryCompensateContract: AttachedBoundaryEvent<BoundaryCompensateContract>
          get() = AttachedBoundaryEvent(target = BoundaryCompensateContract)

        val boundaryContractNotSigned: AttachedBoundaryEvent<BoundaryContractNotSigned>
          get() = AttachedBoundaryEvent(target = BoundaryContractNotSigned)

        val gatewayFork: SequenceFlows<GatewayFork>
          get() = SequenceFlows.single(flowId = ElementId("flow_concludeContractToFork"), target = GatewayFork)

        val timerSignatureReminder: AttachedBoundaryEvent<TimerSignatureReminder>
          get() = AttachedBoundaryEvent(target = TimerSignatureReminder)
      }

      object Start {
        val startEventCustomerEligible: StartEventCustomerEligible
          get() = StartEventCustomerEligible
      }
    }

    object TimerSignatureDeadline : AbstractFlowNode(
      id = ElementId(TimerSignatureDeadline.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "14 days passed",
    ), HasSuccessors<TimerSignatureDeadline.Next>, Event, TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "timer_signatureDeadline"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = "P14D",
      )

      override val next: Next = Next

      object Next {
        val endEventContractNotSigned: SequenceFlows<EndEventContractNotSigned>
          get() = SequenceFlows.single(flowId = ElementId("flow_signatureDeadlineToContractNotSigned"), target = EndEventContractNotSigned)
      }
    }

    object TimerSignatureReminder : AbstractFlowNode(
      id = ElementId(TimerSignatureReminder.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "7 days passed",
    ), HasSuccessors<TimerSignatureReminder.Next>, BoundaryEvent<SubProcessConcludeContract>,
        TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "timer_signatureReminder"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = "P7D",
      )

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = false

      override val next: Next = Next

      object Next {
        val serviceTaskSendReminderMail: SequenceFlows<ServiceTaskSendReminderMail>
          get() = SequenceFlows.single(flowId = ElementId("flow_signatureReminderToSendReminderMail"), target = ServiceTaskSendReminderMail)
      }
    }

    object TimerWithdrawalPeriodElapsed : AbstractFlowNode(
      id = ElementId(TimerWithdrawalPeriodElapsed.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "Withdrawal period elapsed",
    ), HasSuccessors<TimerWithdrawalPeriodElapsed.Next>, Event, TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "timer_withdrawalPeriodElapsed"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = $$"""${withdrawalPeriod}""",
      )

      override val next: Next = Next

      object Next {
        val endEventLeasingActive: SequenceFlows<EndEventLeasingActive>
          get() = SequenceFlows.single(flowId = ElementId("flow_withdrawalPeriodElapsedToLeasingActive"), target = EndEventLeasingActive)
      }
    }

    object UserTaskUpdateDeliveryAddress : AbstractFlowNode(
      id = ElementId(UserTaskUpdateDeliveryAddress.ELEMENT_ID),
      elementType = BpmnElementType.USER_TASK,
      name = "Update delivery address",
    ), HasSuccessors<UserTaskUpdateDeliveryAddress.Next> {
      const val ELEMENT_ID: String = "userTask_updateDeliveryAddress"

      override val next: Next = Next

      object Variables {
        val DELIVERY_ADDRESS: VariableName.InOut =
            VariableName.InOut(ProcessVariables.DELIVERY_ADDRESS)
      }

      object Next {
        val endEventDeliveryAddressUpdated: SequenceFlows<EndEventDeliveryAddressUpdated>
          get() = SequenceFlows.single(flowId = ElementId("flow_updateDeliveryAddressToDeliveryAddressUpdated"), target = EndEventDeliveryAddressUpdated)
      }
    }
  }
}
