// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.BpmnError
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
object Errors {
  val MIRAVELO_APPLICATION_INVALID_APPLICATION_INVALID: BpmnError = BpmnError(
    name = "miravelo.applicationInvalid",
    code = "applicationInvalid",
  )

  val entries: List<BpmnError> = listOf(
    MIRAVELO_APPLICATION_INVALID_APPLICATION_INVALID,
  )
}
