// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.BpmnErrorDefinition
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
object Errors {
  val MIRAVELO_APPLICATION_INVALID: BpmnErrorDefinition = BpmnErrorDefinition(
    name = Names.MIRAVELO_APPLICATION_INVALID_NAME,
    code = Names.MIRAVELO_APPLICATION_INVALID_CODE,
  )

  val entries: List<BpmnErrorDefinition> = listOf(
    MIRAVELO_APPLICATION_INVALID,
  )

  object Names {
    const val MIRAVELO_APPLICATION_INVALID_NAME: String = "miravelo.applicationInvalid"

    const val MIRAVELO_APPLICATION_INVALID_CODE: String = "applicationInvalid"
  }
}
