// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.BpmnEscalationDefinition
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN escalation definitions with name and code, as thrown and caught by the processes.
 */
object Escalations {
  val MIRAVELO_CONTRACT_NOT_SIGNED: BpmnEscalationDefinition = BpmnEscalationDefinition(
    name = Names.MIRAVELO_CONTRACT_NOT_SIGNED_NAME,
    code = Names.MIRAVELO_CONTRACT_NOT_SIGNED_CODE,
  )

  val entries: List<BpmnEscalationDefinition> = listOf(
    MIRAVELO_CONTRACT_NOT_SIGNED,
  )

  object Names {
    const val MIRAVELO_CONTRACT_NOT_SIGNED_NAME: String = "miravelo.contractNotSigned"

    const val MIRAVELO_CONTRACT_NOT_SIGNED_CODE: String = "contractNotSigned"
  }
}
