// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.MessageName
import kotlin.Suppress

/**
 * BPMN message names used to correlate messages to running process instances.
 */
object Messages {
  val MESSAGE_FORM_SUBMITTED: MessageName = MessageName("Message_FormSubmitted")
}
