// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.MessageName
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN message names used to correlate messages to running process instances.
 */
object Messages {
  val MIRAVELO_ADDRESS_CHANGED: MessageName = MessageName(Names.MIRAVELO_ADDRESS_CHANGED)

  val MIRAVELO_APPLICATION_WITHDRAWN: MessageName =
      MessageName(Names.MIRAVELO_APPLICATION_WITHDRAWN)

  val MIRAVELO_CONTRACT_SIGNED: MessageName = MessageName(Names.MIRAVELO_CONTRACT_SIGNED)

  val MIRAVELO_HANDOVER_REPORTED: MessageName = MessageName(Names.MIRAVELO_HANDOVER_REPORTED)

  val MIRAVELO_LEASING_REQUEST_RECEIVED: MessageName =
      MessageName(Names.MIRAVELO_LEASING_REQUEST_RECEIVED)

  val entries: List<MessageName> = listOf(
    MIRAVELO_ADDRESS_CHANGED,
    MIRAVELO_APPLICATION_WITHDRAWN,
    MIRAVELO_CONTRACT_SIGNED,
    MIRAVELO_HANDOVER_REPORTED,
    MIRAVELO_LEASING_REQUEST_RECEIVED,
  )

  object Names {
    const val MIRAVELO_ADDRESS_CHANGED: String = "miravelo.addressChanged"

    const val MIRAVELO_APPLICATION_WITHDRAWN: String = "miravelo.applicationWithdrawn"

    const val MIRAVELO_CONTRACT_SIGNED: String = "miravelo.contractSigned"

    const val MIRAVELO_HANDOVER_REPORTED: String = "miravelo.handoverReported"

    const val MIRAVELO_LEASING_REQUEST_RECEIVED: String = "miravelo.leasingRequestReceived"
  }
}
