// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.BpmnElementType
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.FlowNode
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.SequenceFlow
import io.miragon.bpmn.runtime.SequenceFlows
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

object OrderProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("order")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * Typed navigation over the process flow: one nested object per BPMN element.
   */
  object FlowNodes {
    val all: List<FlowNode> = listOf(
      GatewayAmount,
      TaskApprove,
      TaskReview,
    )

    object GatewayAmount : AbstractFlowNode(
      id = ElementId(GatewayAmount.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
    ), HasSuccessors<GatewayAmount.Next> {
      const val ELEMENT_ID: String = "gateway_amount"

      override val next: Next = Next

      object Next {
        val taskApprove: SequenceFlows<TaskApprove>
          get() = SequenceFlows(
            TaskApprove,
            SequenceFlow(
              id = ElementId("flow_small"),
              conditionExpression = "=amount < 100",
              target = TaskApprove,
            ),
            SequenceFlow(
              id = ElementId("flow_vip"),
              conditionExpression = "=customer.isVip",
              target = TaskApprove,
            ),
          )

        val taskReview: SequenceFlows<TaskReview>
          get() = SequenceFlows(
            TaskReview,
            SequenceFlow(
              id = ElementId("flow_review"),
              isDefault = true,
              target = TaskReview,
            ),
          )
      }
    }

    object TaskApprove : AbstractFlowNode(
      id = ElementId(TaskApprove.ELEMENT_ID),
      elementType = BpmnElementType.UNKNOWN,
    ) {
      const val ELEMENT_ID: String = "task_approve"
    }

    object TaskReview : AbstractFlowNode(
      id = ElementId(TaskReview.ELEMENT_ID),
      elementType = BpmnElementType.UNKNOWN,
    ) {
      const val ELEMENT_ID: String = "task_review"
    }
  }
}
