// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnError
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.HasInnerScope
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.InputOutputMapping
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.NavigationScope
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.SignalName
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("newsletterSubscription")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val ACTIVITY_CONFIRM_REGISTRATION: ElementId = ElementId("Activity_ConfirmRegistration")

    val ACTIVITY_NOTIFY_COMMUNITY: ElementId = ElementId("Activity_NotifyCommunity")

    val ACTIVITY_SEND_CONFIRMATION_MAIL: ElementId =
        ElementId("Activity_SendConfirmationMail")

    val ACTIVITY_SEND_WELCOME_MAIL: ElementId = ElementId("Activity_SendWelcomeMail")

    val CALL_ACTIVITY_ABORT_REGISTRATION: ElementId =
        ElementId("CallActivity_AbortRegistration")

    val COMPENSATION_END_EVENT_REGISTRATION_ABORTED: ElementId =
        ElementId("CompensationEndEvent_RegistrationAborted")

    val COMPENSATION_EVENT_ON_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("CompensationEvent_OnSubscriptionCounter")

    val COMPENSATION_TASK_DECREMENT_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("CompensationTask_DecrementSubscriptionCounter")

    val END_EVENT_REGISTRATION_COMPLETED: ElementId =
        ElementId("EndEvent_RegistrationCompleted")

    val END_EVENT_REGISTRATION_NOT_POSSIBLE: ElementId =
        ElementId("EndEvent_RegistrationNotPossible")

    val END_EVENT_SUBSCRIPTION_CONFIRMED: ElementId =
        ElementId("EndEvent_SubscriptionConfirmed")

    val ERROR_EVENT_INVALID_MAIL: ElementId = ElementId("ErrorEvent_InvalidMail")

    val GATEWAY_JOIN_NOTIFICATIONS: ElementId = ElementId("Gateway_JoinNotifications")

    val GATEWAY_SPLIT_NOTIFICATIONS: ElementId = ElementId("Gateway_SplitNotifications")

    val START_EVENT_REQUEST_RECEIVED: ElementId = ElementId("StartEvent_RequestReceived")

    val START_EVENT_SUBMIT_REGISTRATION_FORM: ElementId =
        ElementId("StartEvent_SubmitRegistrationForm")

    val SUB_PROCESS_CONFIRMATION: ElementId = ElementId("SubProcess_Confirmation")

    val TIMER_AFTER_3_DAYS: ElementId = ElementId("Timer_After3Days")

    val TIMER_EVERY_DAY: ElementId = ElementId("Timer_EveryDay")

    val SERVICE_TASK_INCREMENT_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("serviceTask_incrementSubscriptionCounter")
  }

  /**
   * Call activities grouped by element. Each nested object exposes the called `PROCESS_ID` plus the variable mappings passed into (`Inputs`) and returned from (`Outputs`) the called process.
   */
  object CallActivities {
    object CallActivityAbortRegistration {
      val PROCESS_ID: ProcessId = ProcessId("abort-registration")

      object Inputs {
        val SUBSCRIPTION_ID: InputOutputMapping =
            InputOutputMapping(target = "subscriptionId", source = "=subscriptionId")
      }
    }
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  object Messages {
    val MESSAGE_FORM_SUBMITTED: MessageName = MessageName("Message_FormSubmitted")

    val MESSAGE_SUBSCRIPTION_CONFIRMED: MessageName =
        MessageName("Message_SubscriptionConfirmed")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val NEWSLETTER_INCREMENT_COUNTER: String = "newsletter.incrementCounter"

    const val NEWSLETTER_NOTIFY_COMMUNITY: String = "newsletter.notifyCommunity"

    const val NEWSLETTER_REGISTRATION_COMPLETED: String = "newsletter.registrationCompleted"

    const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "newsletter.sendConfirmationMail"

    const val NEWSLETTER_SEND_WELCOME_MAIL: String = "newsletter.sendWelcomeMail"
  }

  object Timers {
    val TIMER_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", "=testVariable")

    val TIMER_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")
  }

  object Errors {
    val ERROR_INVALID_MAIL: BpmnError = BpmnError("Error_InvalidMail", "500")
  }

  object Signals {
    val SIGNAL_REGISTRATION_NOT_POSSIBLE: SignalName =
        SignalName("Signal_RegistrationNotPossible")
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object ActivitySendConfirmationMail {
      val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")

      val TEST_VARIABLE: VariableName.Input = VariableName.Input("testVariable")
    }

    object ActivitySendWelcomeMail {
      val SUBSCRIPTION_ID: VariableName.InOut = VariableName.InOut("subscriptionId")
    }

    object CallActivityAbortRegistration {
      val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")
    }

    object CompensationTaskDecrementSubscriptionCounter {
      val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")
    }

    object EndEventRegistrationCompleted {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object ErrorEventInvalidMail {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventRequestReceived {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventSubmitRegistrationForm {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }
  }

  /**
   * Typed navigation over the process flow.
   * Each element is a node exposing its `id`, `elementType` and display `name`, plus the elements reachable from it as named properties — so a full path is verified by the compiler and offered by autocomplete. A subprocess's interior is its nested `Inner` scope.
   * Intended for tooling, tests, and reasoning about the process shape.
   */
  object Relations {
    val activityNotifyCommunity: ActivityNotifyCommunity
      get() = ActivityNotifyCommunity

    val activitySendWelcomeMail: ActivitySendWelcomeMail
      get() = ActivitySendWelcomeMail

    val callActivityAbortRegistration: CallActivityAbortRegistration
      get() = CallActivityAbortRegistration

    val compensationEndEventRegistrationAborted: CompensationEndEventRegistrationAborted
      get() = CompensationEndEventRegistrationAborted

    val compensationEventOnSubscriptionCounter: CompensationEventOnSubscriptionCounter
      get() = CompensationEventOnSubscriptionCounter

    val compensationTaskDecrementSubscriptionCounter:
        CompensationTaskDecrementSubscriptionCounter
      get() = CompensationTaskDecrementSubscriptionCounter

    val endEventRegistrationCompleted: EndEventRegistrationCompleted
      get() = EndEventRegistrationCompleted

    val endEventRegistrationNotPossible: EndEventRegistrationNotPossible
      get() = EndEventRegistrationNotPossible

    val errorEventInvalidMail: ErrorEventInvalidMail
      get() = ErrorEventInvalidMail

    val gatewayJoinNotifications: GatewayJoinNotifications
      get() = GatewayJoinNotifications

    val gatewaySplitNotifications: GatewaySplitNotifications
      get() = GatewaySplitNotifications

    val serviceTaskIncrementSubscriptionCounter: ServiceTaskIncrementSubscriptionCounter
      get() = ServiceTaskIncrementSubscriptionCounter

    val startEventSubmitRegistrationForm: StartEventSubmitRegistrationForm
      get() = StartEventSubmitRegistrationForm

    val subProcessConfirmation: SubProcessConfirmation
      get() = SubProcessConfirmation

    val timerAfter3Days: TimerAfter3Days
      get() = TimerAfter3Days

    fun then(): Next = Next

    object Next {
      val startEventSubmitRegistrationForm: StartEventSubmitRegistrationForm
        get() = StartEventSubmitRegistrationForm
    }

    object ActivityNotifyCommunity : AbstractFlowNode(ElementId("Activity_NotifyCommunity"), "SERVICE_TASK"),
        HasSuccessors<ActivityNotifyCommunity.Next> {
      val name: String = "Notify community"

      override fun then(): Next = Next

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }
    }

    object ActivitySendWelcomeMail : AbstractFlowNode(ElementId("Activity_SendWelcomeMail"), "SERVICE_TASK"),
        HasSuccessors<ActivitySendWelcomeMail.Next> {
      val name: String = "Send Welcome-Mail"

      override fun then(): Next = Next

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }
    }

    object CallActivityAbortRegistration : AbstractFlowNode(ElementId("CallActivity_AbortRegistration"), "CALL_ACTIVITY"),
        HasSuccessors<CallActivityAbortRegistration.Next> {
      val name: String = "Abort registration"

      val calledProcess: ProcessId = ProcessId("abort-registration")

      override fun then(): Next = Next

      object Next {
        val compensationEndEventRegistrationAborted: CompensationEndEventRegistrationAborted
          get() = CompensationEndEventRegistrationAborted
      }
    }

    object CompensationEndEventRegistrationAborted : AbstractFlowNode(ElementId("CompensationEndEvent_RegistrationAborted"), "COMPENSATION_END_EVENT") {
      val name: String = "Registration aborted"
    }

    object CompensationEventOnSubscriptionCounter : AbstractFlowNode(ElementId("CompensationEvent_OnSubscriptionCounter"), "COMPENSATION_BOUNDARY_EVENT") {
      val name: String = "Registration aborted"
    }

    object CompensationTaskDecrementSubscriptionCounter : AbstractFlowNode(ElementId("CompensationTask_DecrementSubscriptionCounter"), "SERVICE_TASK") {
      val name: String = "Decrement subscription counter"
    }

    object EndEventRegistrationCompleted : AbstractFlowNode(ElementId("EndEvent_RegistrationCompleted"), "MESSAGE_END_EVENT") {
      val name: String = "Registration completed"
    }

    object EndEventRegistrationNotPossible : AbstractFlowNode(ElementId("EndEvent_RegistrationNotPossible"), "SIGNAL_END_EVENT") {
      val name: String = "Registration not possible"
    }

    object ErrorEventInvalidMail : AbstractFlowNode(ElementId("ErrorEvent_InvalidMail"), "ERROR_BOUNDARY_EVENT"),
        HasSuccessors<ErrorEventInvalidMail.Next> {
      val name: String = "Invalid Mail"

      override fun then(): Next = Next

      object Next {
        val endEventRegistrationNotPossible: EndEventRegistrationNotPossible
          get() = EndEventRegistrationNotPossible
      }
    }

    object GatewayJoinNotifications : AbstractFlowNode(ElementId("Gateway_JoinNotifications"), "PARALLEL_GATEWAY"),
        HasSuccessors<GatewayJoinNotifications.Next> {
      override fun then(): Next = Next

      object Next {
        val endEventRegistrationCompleted: EndEventRegistrationCompleted
          get() = EndEventRegistrationCompleted
      }
    }

    object GatewaySplitNotifications : AbstractFlowNode(ElementId("Gateway_SplitNotifications"), "PARALLEL_GATEWAY"),
        HasSuccessors<GatewaySplitNotifications.Next> {
      override fun then(): Next = Next

      object Next {
        val activityNotifyCommunity: ActivityNotifyCommunity
          get() = ActivityNotifyCommunity

        val activitySendWelcomeMail: ActivitySendWelcomeMail
          get() = ActivitySendWelcomeMail
      }
    }

    object ServiceTaskIncrementSubscriptionCounter : AbstractFlowNode(ElementId("serviceTask_incrementSubscriptionCounter"), "SERVICE_TASK"),
        HasSuccessors<ServiceTaskIncrementSubscriptionCounter.Next> {
      val name: String = "Increment subscription counter"

      override fun then(): Next = Next

      object Next {
        val compensationEventOnSubscriptionCounter: CompensationEventOnSubscriptionCounter
          get() = CompensationEventOnSubscriptionCounter

        val subProcessConfirmation: SubProcessConfirmation
          get() = SubProcessConfirmation
      }
    }

    object StartEventSubmitRegistrationForm : AbstractFlowNode(ElementId("StartEvent_SubmitRegistrationForm"), "MESSAGE_START_EVENT"),
        HasSuccessors<StartEventSubmitRegistrationForm.Next> {
      val name: String = "Submit newsletter form"

      override fun then(): Next = Next

      object Next {
        val serviceTaskIncrementSubscriptionCounter: ServiceTaskIncrementSubscriptionCounter
          get() = ServiceTaskIncrementSubscriptionCounter
      }
    }

    object SubProcessConfirmation : AbstractFlowNode(ElementId("SubProcess_Confirmation"), "SUB_PROCESS"),
        HasSuccessors<SubProcessConfirmation.Next>, HasInnerScope<SubProcessConfirmation.Inner> {
      val name: String = "Subscription Confirmation"

      val activityConfirmRegistration: ActivityConfirmRegistration
        get() = ActivityConfirmRegistration

      val activitySendConfirmationMail: ActivitySendConfirmationMail
        get() = ActivitySendConfirmationMail

      val endEventSubscriptionConfirmed: EndEventSubscriptionConfirmed
        get() = EndEventSubscriptionConfirmed

      val startEventRequestReceived: StartEventRequestReceived
        get() = StartEventRequestReceived

      val timerEveryDay: TimerEveryDay
        get() = TimerEveryDay

      override fun then(): Next = Next

      override fun `inner`(): SubProcessConfirmation.Inner = SubProcessConfirmation.Inner

      object Next {
        val errorEventInvalidMail: ErrorEventInvalidMail
          get() = ErrorEventInvalidMail

        val gatewaySplitNotifications: GatewaySplitNotifications
          get() = GatewaySplitNotifications

        val timerAfter3Days: TimerAfter3Days
          get() = TimerAfter3Days
      }

      object Inner : NavigationScope<SubProcessConfirmation.Inner.Next> {
        override fun then(): Next = Next

        object Next {
          val startEventRequestReceived: StartEventRequestReceived
            get() = StartEventRequestReceived
        }
      }

      object ActivityConfirmRegistration : AbstractFlowNode(ElementId("Activity_ConfirmRegistration"), "RECEIVE_TASK"),
          HasSuccessors<ActivityConfirmRegistration.Next> {
        val name: String = "Confirm subscription"

        override fun then(): Next = Next

        object Next {
          val endEventSubscriptionConfirmed: EndEventSubscriptionConfirmed
            get() = EndEventSubscriptionConfirmed

          val timerEveryDay: TimerEveryDay
            get() = TimerEveryDay
        }
      }

      object ActivitySendConfirmationMail : AbstractFlowNode(ElementId("Activity_SendConfirmationMail"), "SERVICE_TASK"),
          HasSuccessors<ActivitySendConfirmationMail.Next> {
        val name: String = "Send confirmation mail"

        override fun then(): Next = Next

        object Next {
          val activityConfirmRegistration: ActivityConfirmRegistration
            get() = ActivityConfirmRegistration
        }
      }

      object EndEventSubscriptionConfirmed : AbstractFlowNode(ElementId("EndEvent_SubscriptionConfirmed"), "END_EVENT") {
        val name: String = "Subscription confirmed"
      }

      object StartEventRequestReceived : AbstractFlowNode(ElementId("StartEvent_RequestReceived"), "START_EVENT"),
          HasSuccessors<StartEventRequestReceived.Next> {
        val name: String = "Subscription requested"

        override fun then(): Next = Next

        object Next {
          val activitySendConfirmationMail: ActivitySendConfirmationMail
            get() = ActivitySendConfirmationMail
        }
      }

      object TimerEveryDay : AbstractFlowNode(ElementId("Timer_EveryDay"), "TIMER_BOUNDARY_EVENT"),
          HasSuccessors<TimerEveryDay.Next> {
        val name: String = "Every day"

        override fun then(): Next = Next

        object Next {
          val activitySendConfirmationMail: ActivitySendConfirmationMail
            get() = ActivitySendConfirmationMail
        }
      }
    }

    object TimerAfter3Days : AbstractFlowNode(ElementId("Timer_After3Days"), "TIMER_BOUNDARY_EVENT"),
        HasSuccessors<TimerAfter3Days.Next> {
      val name: String = "After 3 days"

      override fun then(): Next = Next

      object Next {
        val callActivityAbortRegistration: CallActivityAbortRegistration
          get() = CallActivityAbortRegistration
      }
    }
  }
}
