// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnError
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.FlowScope
import io.miragon.bpmn.runtime.HasFlows
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.InputOutputMapping
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.SequenceFlow
import io.miragon.bpmn.runtime.SignalName
import io.miragon.bpmn.runtime.VariableName
import kotlin.Boolean
import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("newsletterSubscription")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * Typed navigation over the process flow.
   * Each element is a nested object exposing its `id`, `elementType` and display `name`, plus the elements reachable from it behind `then()` — so a full path is verified by the compiler and offered by autocomplete. Every element is a direct child of `Flow`, whatever its subprocess depth; a subprocess opens its interior via `start()`.
   * Intended for tooling, tests, and reasoning about the process shape.
   */
  object Flow {
    object CallActivityAbortRegistration : AbstractFlowNode(
      id = ElementId("callActivity_abortRegistration"),
      elementType = "CALL_ACTIVITY",
    ), HasSuccessors<CallActivityAbortRegistration.Next>,
        HasFlows<CallActivityAbortRegistration.Flows> {
      val calledProcess: ProcessId = ProcessId("abort-registration")

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Variables {
        val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")
      }

      object Inputs {
        val CHILD_REASON_CODE: InputOutputMapping = InputOutputMapping(
          target = "childReasonCode",
          sourceExpression = $$"""${reasonCode}""",
        )

        val CHILD_SUBSCRIPTION_ID: InputOutputMapping = InputOutputMapping(
          target = "childSubscriptionId",
          source = "subscriptionId",
        )
      }

      object Outputs {
        val ABORT_RESULT: InputOutputMapping = InputOutputMapping(
          target = "abortResult",
          source = "childAbortResult",
        )
      }

      object Next {
        val compensationEndEventRegistrationAborted: CompensationEndEventRegistrationAborted
          get() = CompensationEndEventRegistrationAborted
      }

      object Flows {
        val flowAbortToRegistrationAborted:
            SequenceFlow<CompensationEndEventRegistrationAborted>
          get() = SequenceFlow(
            id = ElementId("flow_abortToRegistrationAborted"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = CompensationEndEventRegistrationAborted,
          )
      }
    }

    object CompensationEndEventRegistrationAborted : AbstractFlowNode(
      id = ElementId("compensationEndEvent_registrationAborted"),
      elementType = "COMPENSATION_END_EVENT",
    )

    object CompensationEventOnSubscriptionCounter : AbstractFlowNode(
      id = ElementId("compensationEvent_onSubscriptionCounter"),
      elementType = "COMPENSATION_BOUNDARY_EVENT",
    ) {
      val attachedTo: ServiceTaskIncrementSubscriptionCounter
        get() = ServiceTaskIncrementSubscriptionCounter

      val isInterrupting: Boolean = true
    }

    object EndEventRegistrationCompleted : AbstractFlowNode(
      id = ElementId("endEvent_registrationCompleted"),
      elementType = "END_EVENT",
    ) {
      const val JOB_TYPE: String = ServiceTasks.NEWSLETTER_REGISTRATION_COMPLETED

      object Variables {
        val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
      }
    }

    object EndEventRegistrationNotPossible : AbstractFlowNode(
      id = ElementId("endEvent_registrationNotPossible"),
      elementType = "SIGNAL_END_EVENT",
    ) {
      val signal: SignalName = Signals.SIGNAL_REGISTRATION_NOT_POSSIBLE
    }

    object EndEventSubscriptionConfirmed : AbstractFlowNode(
      id = ElementId("endEvent_subscriptionConfirmed"),
      elementType = "END_EVENT",
    )

    object ErrorEventInvalidMail : AbstractFlowNode(
      id = ElementId("errorEvent_invalidMail"),
      elementType = "ERROR_BOUNDARY_EVENT",
    ), HasSuccessors<ErrorEventInvalidMail.Next>, HasFlows<ErrorEventInvalidMail.Flows> {
      val error: BpmnError = Errors.ERROR_INVALID_MAIL_500

      val attachedTo: SubProcessConfirmation
        get() = SubProcessConfirmation

      val isInterrupting: Boolean = true

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val endEventRegistrationNotPossible: EndEventRegistrationNotPossible
          get() = EndEventRegistrationNotPossible
      }

      object Flows {
        val flowInvalidMailToNotPossible: SequenceFlow<EndEventRegistrationNotPossible>
          get() = SequenceFlow(
            id = ElementId("flow_invalidMailToNotPossible"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = EndEventRegistrationNotPossible,
          )
      }
    }

    object GatewayJoinNotifications : AbstractFlowNode(
      id = ElementId("gateway_joinNotifications"),
      elementType = "PARALLEL_GATEWAY",
    ), HasSuccessors<GatewayJoinNotifications.Next>, HasFlows<GatewayJoinNotifications.Flows> {
      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val endEventRegistrationCompleted: EndEventRegistrationCompleted
          get() = EndEventRegistrationCompleted
      }

      object Flows {
        val flowJoinToRegistrationCompleted: SequenceFlow<EndEventRegistrationCompleted>
          get() = SequenceFlow(
            id = ElementId("flow_joinToRegistrationCompleted"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = EndEventRegistrationCompleted,
          )
      }
    }

    object GatewaySplitNotifications : AbstractFlowNode(
      id = ElementId("gateway_splitNotifications"),
      elementType = "PARALLEL_GATEWAY",
    ), HasSuccessors<GatewaySplitNotifications.Next>, HasFlows<GatewaySplitNotifications.Flows> {
      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val serviceTaskNotifyCommunity: ServiceTaskNotifyCommunity
          get() = ServiceTaskNotifyCommunity

        val serviceTaskSendWelcomeMail: ServiceTaskSendWelcomeMail
          get() = ServiceTaskSendWelcomeMail
      }

      object Flows {
        val flowSplitToNotifyCommunity: SequenceFlow<ServiceTaskNotifyCommunity>
          get() = SequenceFlow(
            id = ElementId("flow_splitToNotifyCommunity"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = ServiceTaskNotifyCommunity,
          )

        val flowSplitToWelcomeMail: SequenceFlow<ServiceTaskSendWelcomeMail>
          get() = SequenceFlow(
            id = ElementId("flow_splitToWelcomeMail"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = ServiceTaskSendWelcomeMail,
          )
      }
    }

    object ServiceTaskDecrementSubscriptionCounter : AbstractFlowNode(
      id = ElementId("serviceTask_decrementSubscriptionCounter"),
      elementType = "SERVICE_TASK",
    ) {
      const val JOB_TYPE: String = ServiceTasks.COUNTER_CLASS
    }

    object ServiceTaskIncrementSubscriptionCounter : AbstractFlowNode(
      id = ElementId("serviceTask_incrementSubscriptionCounter"),
      elementType = "SERVICE_TASK",
    ), HasSuccessors<ServiceTaskIncrementSubscriptionCounter.Next>,
        HasFlows<ServiceTaskIncrementSubscriptionCounter.Flows> {
      const val JOB_TYPE: String = ServiceTasks.COUNTER_CLASS

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val compensationEventOnSubscriptionCounter: CompensationEventOnSubscriptionCounter
          get() = CompensationEventOnSubscriptionCounter

        val subProcessConfirmation: SubProcessConfirmation
          get() = SubProcessConfirmation
      }

      object Flows {
        val flowIncrementCounterToConfirmation: SequenceFlow<SubProcessConfirmation>
          get() = SequenceFlow(
            id = ElementId("flow_incrementCounterToConfirmation"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = SubProcessConfirmation,
          )
      }
    }

    object ServiceTaskNotifyCommunity : AbstractFlowNode(
      id = ElementId("serviceTask_notifyCommunity"),
      elementType = "SERVICE_TASK",
    ), HasSuccessors<ServiceTaskNotifyCommunity.Next>, HasFlows<ServiceTaskNotifyCommunity.Flows> {
      const val JOB_TYPE: String = ServiceTasks.NEWSLETTER_NOTIFY_COMMUNITY

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }

      object Flows {
        val flowNotifyCommunityToJoin: SequenceFlow<GatewayJoinNotifications>
          get() = SequenceFlow(
            id = ElementId("flow_notifyCommunityToJoin"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = GatewayJoinNotifications,
          )
      }
    }

    object ServiceTaskSendConfirmationMail : AbstractFlowNode(
      id = ElementId("serviceTask_sendConfirmationMail"),
      elementType = "SERVICE_TASK",
    ), HasSuccessors<ServiceTaskSendConfirmationMail.Next>,
        HasFlows<ServiceTaskSendConfirmationMail.Flows> {
      const val JOB_TYPE: String = ServiceTasks.NEWSLETTER_SEND_CONFIRMATION_MAIL

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Variables {
        val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")

        val TEST_VARIABLE: VariableName.Input = VariableName.Input("testVariable")
      }

      object Next {
        val userTaskConfirmRegistration: UserTaskConfirmRegistration
          get() = UserTaskConfirmRegistration
      }

      object Flows {
        val flowConfirmationMailToConfirm: SequenceFlow<UserTaskConfirmRegistration>
          get() = SequenceFlow(
            id = ElementId("flow_confirmationMailToConfirm"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = UserTaskConfirmRegistration,
          )
      }
    }

    object ServiceTaskSendWelcomeMail : AbstractFlowNode(
      id = ElementId("serviceTask_sendWelcomeMail"),
      elementType = "SERVICE_TASK",
    ), HasSuccessors<ServiceTaskSendWelcomeMail.Next>, HasFlows<ServiceTaskSendWelcomeMail.Flows> {
      const val JOB_TYPE: String = ServiceTasks.NEWSLETTER_SEND_WELCOME_MAIL

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Variables {
        val SUBSCRIPTION_ID: VariableName.InOut = VariableName.InOut("subscriptionId")
      }

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }

      object Flows {
        val flowWelcomeMailToJoin: SequenceFlow<GatewayJoinNotifications>
          get() = SequenceFlow(
            id = ElementId("flow_welcomeMailToJoin"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = GatewayJoinNotifications,
          )
      }
    }

    object StartEventRequestReceived : AbstractFlowNode(
      id = ElementId("startEvent_requestReceived"),
      elementType = "START_EVENT",
    ), HasSuccessors<StartEventRequestReceived.Next>, HasFlows<StartEventRequestReceived.Flows> {
      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Variables {
        val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
      }

      object Next {
        val serviceTaskSendConfirmationMail: ServiceTaskSendConfirmationMail
          get() = ServiceTaskSendConfirmationMail
      }

      object Flows {
        val flowRequestToConfirmationMail: SequenceFlow<ServiceTaskSendConfirmationMail>
          get() = SequenceFlow(
            id = ElementId("flow_requestToConfirmationMail"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = ServiceTaskSendConfirmationMail,
          )
      }
    }

    object StartEventSubmitRegistrationForm : AbstractFlowNode(
      id = ElementId("startEvent_submitRegistrationForm"),
      elementType = "MESSAGE_START_EVENT",
    ), HasSuccessors<StartEventSubmitRegistrationForm.Next>,
        HasFlows<StartEventSubmitRegistrationForm.Flows> {
      val message: MessageName = Messages.MESSAGE_FORM_SUBMITTED

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Variables {
        val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
      }

      object Next {
        val serviceTaskIncrementSubscriptionCounter: ServiceTaskIncrementSubscriptionCounter
          get() = ServiceTaskIncrementSubscriptionCounter
      }

      object Flows {
        val flowSubmitToIncrementCounter:
            SequenceFlow<ServiceTaskIncrementSubscriptionCounter>
          get() = SequenceFlow(
            id = ElementId("flow_submitToIncrementCounter"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = ServiceTaskIncrementSubscriptionCounter,
          )
      }
    }

    object SubProcessConfirmation : AbstractFlowNode(
      id = ElementId("subProcess_confirmation"),
      elementType = "SUB_PROCESS",
    ), HasSuccessors<SubProcessConfirmation.Next>, HasFlows<SubProcessConfirmation.Flows>,
        FlowScope<SubProcessConfirmation.Start> {
      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      override fun start(): Start = Start

      object Next {
        val errorEventInvalidMail: ErrorEventInvalidMail
          get() = ErrorEventInvalidMail

        val gatewaySplitNotifications: GatewaySplitNotifications
          get() = GatewaySplitNotifications

        val timerAfter3Days: TimerAfter3Days
          get() = TimerAfter3Days
      }

      object Flows {
        val flowConfirmationToSplit: SequenceFlow<GatewaySplitNotifications>
          get() = SequenceFlow(
            id = ElementId("flow_confirmationToSplit"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = GatewaySplitNotifications,
          )
      }

      object Start {
        val startEventRequestReceived: StartEventRequestReceived
          get() = StartEventRequestReceived
      }
    }

    object TimerAfter3Days : AbstractFlowNode(
      id = ElementId("timer_after3Days"),
      elementType = "TIMER_BOUNDARY_EVENT",
    ), HasSuccessors<TimerAfter3Days.Next>, HasFlows<TimerAfter3Days.Flows> {
      val timer: BpmnTimer = BpmnTimer(
        type = "Duration",
        timerValue = $$"""${testVariable}""",
      )

      val attachedTo: SubProcessConfirmation
        get() = SubProcessConfirmation

      val isInterrupting: Boolean = true

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val callActivityAbortRegistration: CallActivityAbortRegistration
          get() = CallActivityAbortRegistration
      }

      object Flows {
        val flowAfter3DaysToAbort: SequenceFlow<CallActivityAbortRegistration>
          get() = SequenceFlow(
            id = ElementId("flow_after3DaysToAbort"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = CallActivityAbortRegistration,
          )
      }
    }

    object TimerEveryDay : AbstractFlowNode(
      id = ElementId("timer_everyDay"),
      elementType = "TIMER_BOUNDARY_EVENT",
    ), HasSuccessors<TimerEveryDay.Next>, HasFlows<TimerEveryDay.Flows> {
      val timer: BpmnTimer = BpmnTimer(
        type = "Duration",
        timerValue = "PT1M",
      )

      val attachedTo: UserTaskConfirmRegistration
        get() = UserTaskConfirmRegistration

      val isInterrupting: Boolean = false

      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val serviceTaskSendConfirmationMail: ServiceTaskSendConfirmationMail
          get() = ServiceTaskSendConfirmationMail
      }

      object Flows {
        val flowEveryDayToConfirmationMail: SequenceFlow<ServiceTaskSendConfirmationMail>
          get() = SequenceFlow(
            id = ElementId("flow_everyDayToConfirmationMail"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = ServiceTaskSendConfirmationMail,
          )
      }
    }

    object UserTaskConfirmRegistration : AbstractFlowNode(
      id = ElementId("userTask_confirmRegistration"),
      elementType = "RECEIVE_TASK",
      name = "Confirm registration",
    ), HasSuccessors<UserTaskConfirmRegistration.Next>,
        HasFlows<UserTaskConfirmRegistration.Flows> {
      override fun then(): Next = Next

      override fun flows(): Flows = Flows

      object Next {
        val endEventSubscriptionConfirmed: EndEventSubscriptionConfirmed
          get() = EndEventSubscriptionConfirmed

        val timerEveryDay: TimerEveryDay
          get() = TimerEveryDay
      }

      object Flows {
        val flowConfirmToConfirmed: SequenceFlow<EndEventSubscriptionConfirmed>
          get() = SequenceFlow(
            id = ElementId("flow_confirmToConfirmed"),
            name = null,
            conditionExpression = null,
            isDefault = false,
            target = EndEventSubscriptionConfirmed,
          )
      }
    }
  }
}
