// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Names of the process variables used in `@Variable(name = ProcessVariables.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ProcessVariables {
  const val AGE: String = "age"

  const val APPLICATION_ID: String = "applicationId"

  const val BIKE_ID: String = "bikeId"

  const val BIKE_IDS: String = "bikeIds"

  const val CANCELLATION_COSTS: String = "cancellationCosts"

  const val CANCELLATION_POSSIBLE: String = "cancellationPossible"

  const val CITY: String = "city"

  const val CONTRACT_ID: String = "contractId"

  const val DELIVERY_ADDRESS: String = "deliveryAddress"

  const val MONTHLY_NET_INCOME: String = "monthlyNetIncome"

  const val ORDER_IDS: String = "orderIds"

  const val STREET: String = "street"

  val all: List<String> = listOf(
    AGE,
    APPLICATION_ID,
    BIKE_ID,
    BIKE_IDS,
    CANCELLATION_COSTS,
    CANCELLATION_POSSIBLE,
    CITY,
    CONTRACT_ID,
    DELIVERY_ADDRESS,
    MONTHLY_NET_INCOME,
    ORDER_IDS,
    STREET,
  )
}
