// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import kotlin.String
import kotlin.Suppress

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "#{newsletterSendConfirmationMail}"

  const val NEWSLETTER_SEND_WELCOME_MAIL: String = $$"""${newsletterSendWelcomeMail}"""

  const val COUNTER_CLASS: String = "counterClass"

  const val NEWSLETTER_NOTIFY_COMMUNITY: String = "newsletter.notifyCommunity"

  const val NEWSLETTER_REGISTRATION_COMPLETED: String = "newsletter.registrationCompleted"
}
