// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val CANCEL_CONTRACT_DELEGATE: String = $$"""${cancelContractDelegate}"""

  const val MAIL_SERVICE_SEND_REMINDER_APPLICATION_ID_: String =
      $$"""${mailService.sendReminder(applicationId)}"""

  const val SEND_CONTRACT_DELEGATE: String = $$"""${sendContractDelegate}"""

  const val VALIDATE_APPLICATION_DELEGATE: String = $$"""${validateApplicationDelegate}"""

  const val IO_MIRAVELO_LEASING_ISSUE_INSURANCE_POLICY_DELEGATE: String =
      "io.miravelo.leasing.IssueInsurancePolicyDelegate"

  const val MIRAVELO_CANCEL_POLICY: String = "miravelo.cancelPolicy"

  const val MIRAVELO_ORDER_BIKE: String = "miravelo.orderBike"

  const val MIRAVELO_SEND_CANCELLATION_CONFIRMATION: String =
      "miravelo.sendCancellationConfirmation"

  const val MIRAVELO_SEND_REJECTION: String = "miravelo.sendRejection"

  val all: List<String> = listOf(
    CANCEL_CONTRACT_DELEGATE,
    MAIL_SERVICE_SEND_REMINDER_APPLICATION_ID_,
    SEND_CONTRACT_DELEGATE,
    VALIDATE_APPLICATION_DELEGATE,
    IO_MIRAVELO_LEASING_ISSUE_INSURANCE_POLICY_DELEGATE,
    MIRAVELO_CANCEL_POLICY,
    MIRAVELO_ORDER_BIKE,
    MIRAVELO_SEND_CANCELLATION_CONFIRMATION,
    MIRAVELO_SEND_REJECTION,
  )
}
