// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.runtime.path.example

import io.miragon.bpmn.runtime.SignalName
import kotlin.Suppress

object Signals {
  val SIGNAL_REGISTRATION_NOT_POSSIBLE: SignalName =
      SignalName("Signal_RegistrationNotPossible")
}
