package io.miragon.bpmn.adapter.outbound.filesystem

import io.miragon.bpmn.domain.GeneratedApiFile
import io.miragon.bpmn.domain.shared.OutputLanguage
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

class ProcessApiFileSaverTest {

    private val underTest = ProcessApiFileSaver()

    @Test
    fun `saver writes multiple files to correct locations`(@TempDir tempDir: File) {
        // given: multiple generated files with different package paths
        val firstFile = GeneratedApiFile(
            fileName = "OrderProcessApi.kt",
            packagePath = "com.example.order",
            content = "// order process api code",
            language = OutputLanguage.KOTLIN,
            processId = "order",
        )
        val secondFile = GeneratedApiFile(
            fileName = "PaymentProcessApi.kt",
            packagePath = "com.example.payment",
            content = "// payment process api code",
            language = OutputLanguage.KOTLIN,
            processId = "payment",
        )
        val thirdFile = GeneratedApiFile(
            fileName = "ShippingProcessApi.kt",
            packagePath = "com.example.order.shipping",
            content = "// shipping process api code",
            language = OutputLanguage.KOTLIN,
            processId = "shipping",
        )

        // when: writeFiles is called
        underTest.writeFiles(listOf(firstFile, secondFile, thirdFile), tempDir.absolutePath)

        // then: all directories are created and files are written with correct content
        val orderFile = File(tempDir, "com/example/order/OrderProcessApi.kt")
        val paymentFile = File(tempDir, "com/example/payment/PaymentProcessApi.kt")
        val shippingFile = File(tempDir, "com/example/order/shipping/ShippingProcessApi.kt")

        assertThat(orderFile.exists()).isTrue()
        assertThat(paymentFile.exists()).isTrue()
        assertThat(shippingFile.exists()).isTrue()

        assertThat(orderFile.readText()).isEqualTo("// order process api code")
        assertThat(paymentFile.readText()).isEqualTo("// payment process api code")
        assertThat(shippingFile.readText()).isEqualTo("// shipping process api code")
    }

    @Test
    fun `saver deletes generated files that are no longer produced`(@TempDir tempDir: File) {
        // given: a previously generated Kotlin file and a C# file carrying the header below its auto-generated marker
        val packageDir = File(tempDir, "com/example/order").also { it.mkdirs() }
        val staleKotlinFile = File(packageDir, "Signals.kt").also { it.writeText("// Generated by bpmn-to-code\nobject Signals") }
        val staleCSharpFile = File(packageDir, "Signals.cs")
        staleCSharpFile.writeText("// <auto-generated/>\n// Generated by bpmn-to-code\npublic static class Signals {}")

        // when: the current run no longer produces them
        deleteStaleFilesOfOrderPackage(tempDir, generatedFiles = listOf(generatedFile("OrderProcessApi.kt")))

        // then: both are removed
        assertThat(staleKotlinFile).doesNotExist()
        assertThat(staleCSharpFile).doesNotExist()
    }

    @Test
    fun `saver keeps hand-written files`(@TempDir tempDir: File) {
        // given: files without the header, one of them only mentioning it further down
        val packageDir = File(tempDir, "com/example/order").also { it.mkdirs() }
        val handWrittenFile = File(packageDir, "OrderWorker.kt").also { it.writeText("package com.example.order") }
        val mentioningFile = File(packageDir, "Notes.kt")
        mentioningFile.writeText("package com.example.order\n\n// Generated by bpmn-to-code")

        // when: stale files are deleted
        deleteStaleFilesOfOrderPackage(tempDir, generatedFiles = emptyList())

        // then: both are untouched
        assertThat(handWrittenFile).exists()
        assertThat(mentioningFile).exists()
    }

    @Test
    fun `saver keeps generated files that are still produced`(@TempDir tempDir: File) {
        // given: a previously generated file that the current run produces again
        val packageDir = File(tempDir, "com/example/order").also { it.mkdirs() }
        val currentFile = File(packageDir, "OrderProcessApi.kt").also { it.writeText("// Generated by bpmn-to-code") }

        // when: stale files are deleted
        deleteStaleFilesOfOrderPackage(tempDir, generatedFiles = listOf(generatedFile("OrderProcessApi.kt")))

        // then: it is untouched
        assertThat(currentFile).exists()
    }

    @Test
    fun `saver keeps generated files outside the target package`(@TempDir tempDir: File) {
        // given: generated files in a sub-package and in a sibling package
        val subPackageDir = File(tempDir, "com/example/order/shipping").also { it.mkdirs() }
        val siblingPackageDir = File(tempDir, "com/example/payment").also { it.mkdirs() }
        val subPackageFile = File(subPackageDir, "ShippingProcessApi.kt").also { it.writeText("// Generated by bpmn-to-code") }
        val siblingFile = File(siblingPackageDir, "PaymentProcessApi.kt").also { it.writeText("// Generated by bpmn-to-code") }

        // when: stale files of the order package are deleted
        deleteStaleFilesOfOrderPackage(tempDir, generatedFiles = emptyList())

        // then: other packages are untouched
        assertThat(subPackageFile).exists()
        assertThat(siblingFile).exists()
    }

    @Test
    fun `saver deletes nothing when the package folder does not exist`(@TempDir tempDir: File) {
        // when: stale files are deleted before the first generation
        deleteStaleFilesOfOrderPackage(tempDir, generatedFiles = emptyList())

        // then: the output folder stays empty
        assertThat(tempDir.listFiles()).isEmpty()
    }

    private fun deleteStaleFilesOfOrderPackage(outputFolder: File, generatedFiles: List<GeneratedApiFile>) {
        underTest.deleteStaleFiles(
            generatedFiles = generatedFiles,
            outputFolderPath = outputFolder.absolutePath,
            packagePath = "com.example.order",
        )
    }

    private fun generatedFile(fileName: String) = GeneratedApiFile(
        fileName = fileName,
        packagePath = "com.example.order",
        content = "// Generated by bpmn-to-code",
        language = OutputLanguage.KOTLIN,
        processId = null,
    )
}
