package io.miragon.bpmn.adapter.outbound.codegen.builder.csharp

import io.miragon.bpmn.adapter.outbound.codegen.CodeGenerationAdapter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpErrorsWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpEscalationsWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpMessagesWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpServiceTasksWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpSharedDefinitionWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.shared.CSharpSignalsWriter
import io.miragon.bpmn.domain.GeneratedApiFile
import io.miragon.bpmn.domain.SharedDefinitionsApi

/**
 * Generates one C# static class per kind of engine-global identifier, shared by all Process APIs of a run.
 * Plain `const string`s need none of the runtime types [CSharpProcessApiBuilder] inlines per file, so the
 * classes are the same for every process; the file header matches the Process API's so it compiles under
 * any consumer settings.
 */
internal class CSharpSharedDefinitionsBuilder : CodeGenerationAdapter.AbstractSharedDefinitionsBuilder() {

    private val writers = listOf(
        CSharpServiceTasksWriter,
        CSharpMessagesWriter,
        CSharpSignalsWriter,
        CSharpErrorsWriter,
        CSharpEscalationsWriter,
    )

    override fun buildApiFiles(api: SharedDefinitionsApi): List<GeneratedApiFile> = writers
        .filter { it.shouldWrite(api.definitions) }
        .map { toFile(it, api) }

    private fun toFile(sharedDefinitionWriter: CSharpSharedDefinitionWriter<*>, api: SharedDefinitionsApi): GeneratedApiFile {
        val writer = CSharpWriter()
        writer.line("// <auto-generated/>")
        writer.line("// $autoGenComment")
        writer.line("#nullable enable")
        writer.line("#pragma warning disable CS1591")
        writer.line("namespace ${api.packagePath};")
        writer.line()
        sharedDefinitionWriter.write(writer, api.definitions)
        return GeneratedApiFile(
            fileName = "${sharedDefinitionWriter.type.typeName}.cs",
            packagePath = api.packagePath,
            content = writer.render(),
            language = api.outputLanguage,
            processId = null,
        )
    }
}
