package io.miragon.bpmn.adapter.outbound.codegen.builder.csharp

import io.miragon.bpmn.adapter.outbound.codegen.CodeGenerationAdapter
import io.miragon.bpmn.adapter.outbound.codegen.SharedDefinitionType
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.CSharpWriter
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.CSharpWriter.Companion.disambiguated
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.CSharpWriter.Companion.toPascalCase
import io.miragon.bpmn.adapter.outbound.codegen.builder.csharp.staticListProperty
import io.miragon.bpmn.domain.GeneratedApiFile
import io.miragon.bpmn.domain.SharedDefinitionsApi
import io.miragon.bpmn.domain.shared.VariableMapping

/**
 * Generates one C# static class per kind of engine-global identifier, shared by all Process APIs of a run.
 * Plain `const string`s need none of the runtime types [CSharpProcessApiBuilder] inlines per file, so the
 * classes are the same for every process; the file header matches the Process API's so it compiles under
 * any consumer settings.
 */
internal class CSharpSharedDefinitionsBuilder : CodeGenerationAdapter.AbstractSharedDefinitionsBuilder() {

    override fun buildApiFiles(api: SharedDefinitionsApi): List<GeneratedApiFile> {
        val definitions = api.definitions
        return listOfNotNull(
            constants(api = api, className = SharedDefinitionType.SERVICE_TASKS.typeName, doc = "Job worker task types — the task type a C# worker subscribes to.", items = definitions.serviceTasks),
            constants(api = api, className = SharedDefinitionType.MESSAGES.typeName, doc = "BPMN message names used to correlate messages to running process instances.", items = definitions.messages),
            constants(api = api, className = SharedDefinitionType.SIGNALS.typeName, doc = "BPMN signal names broadcast and caught by signal events.", items = definitions.signals),
            nameAndCodes(api = api, className = SharedDefinitionType.ERRORS.typeName, doc = "BPMN error definitions with name and code, as thrown and caught by the processes.", items = definitions.errors),
            nameAndCodes(api = api, className = SharedDefinitionType.ESCALATIONS.typeName, doc = "BPMN escalation definitions with name and code, as thrown and caught by the processes.", items = definitions.escalations),
        )
    }

    private fun constants(api: SharedDefinitionsApi, className: String, doc: String, items: List<VariableMapping<String>>): GeneratedApiFile? = items.ifNotEmpty {
        toFile(api, className, doc) { writer ->
            items.forEach { writer.constant(it.getName().toPascalCase(), it.getValue()) }
            writer.line()
            writer.staticListProperty(name = "All", elementType = "string", elements = memberNames(items, className))
        }
    }

    private fun nameAndCodes(api: SharedDefinitionsApi, className: String, doc: String, items: List<VariableMapping<Pair<String, String>>>): GeneratedApiFile? = items.ifNotEmpty {
        toFile(api, className, doc) { writer ->
            writer.forEachSeparated(items) { item ->
                val (name, code) = item.getValue()
                writer.staticClass(item.getName().toPascalCase()) {
                    writer.constant("Reference", name)
                    writer.constant("Code", code)
                }
            }
            writer.line()
            val nameAndCodes = memberNames(items, className).map { "($it.Reference, $it.Code)" }
            writer.staticListProperty(name = "All", elementType = "(string Reference, string Code)", elements = nameAndCodes)
        }
    }

    private fun memberNames(items: List<VariableMapping<*>>, className: String): List<String> = items.map { disambiguated(it.getName().toPascalCase(), className) }

    private fun toFile(api: SharedDefinitionsApi, className: String, doc: String, body: (CSharpWriter) -> Unit): GeneratedApiFile {
        val writer = CSharpWriter()
        writer.line("// <auto-generated/>")
        writer.line("// $autoGenComment")
        writer.line("#nullable enable")
        writer.line("#pragma warning disable CS1591")
        writer.line("namespace ${api.packagePath};")
        writer.line()
        writer.docComment(doc)
        writer.staticClass(className) { body(writer) }
        return GeneratedApiFile(
            fileName = "$className.cs",
            packagePath = api.packagePath,
            content = writer.render(),
            language = api.outputLanguage,
            processId = null,
        )
    }

    private fun <T> List<T>.ifNotEmpty(build: () -> GeneratedApiFile): GeneratedApiFile? = if (isEmpty()) null else build()
}
