package io.miragon.bpmn.adapter.outbound.codegen.builder.csharp

import io.miragon.bpmn.adapter.outbound.codegen.GeneratedFileHeader
import io.miragon.bpmn.domain.GeneratedApiFile
import io.miragon.bpmn.domain.shared.OutputLanguage

/**
 * Renders C# types as a generated source file named after [typeName]. The file is marked `<auto-generated/>` and
 * opts into nullable annotations itself, because Roslyn treats generated files as nullable-disabled regardless of
 * the project, so it compiles under any consumer settings.
 */
internal object CSharpSourceFile {

    fun render(
        typeName: String,
        packagePath: String,
        processId: String? = null,
        writeTypes: (CSharpWriter) -> Unit,
    ): GeneratedApiFile {
        val writer = CSharpWriter()
        writer.line("// <auto-generated/>")
        writer.line("// ${GeneratedFileHeader.COMMENT}")
        writer.line("#nullable enable")
        writer.line("#pragma warning disable CS1591")
        writer.line("namespace $packagePath;")
        writer.line()
        writeTypes(writer)
        return GeneratedApiFile(
            fileName = "$typeName.cs",
            packagePath = packagePath,
            content = writer.render(),
            language = OutputLanguage.CSHARP,
            processId = processId,
        )
    }
}
