plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.mavenPublish)
    alias(libs.plugins.dokka)
    jacoco
}

group = "io.miragon"
version = property("projectVersion").toString()

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.bundles.testing)
    testRuntimeOnly(libs.junitPlatformLauncher)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

// The checked-in generated sample API (ProcessPath test fixture) is generated code, not hand-written —
// exclude it from detekt, as a consumer would exclude their own generated output.
tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    exclude("**/io/miragon/bpmn/runtime/path/example/**")
}

mavenPublishing {

    publishToMavenCentral()
    if (project.hasProperty("signArtifacts")) signAllPublications()
    coordinates("io.miragon", "bpmn-to-code-runtime", version.toString())

    pom {
        name.set("bpmn-to-code-runtime")
        description.set("Shared runtime types for APIs generated by bpmn-to-code (ProcessId, ElementId, VariableName, ...)")
        inceptionYear.set("2026")
        url.set("https://github.com/Miragon/bpmn-to-code")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
                distribution.set("https://opensource.org/licenses/MIT")
            }
        }
        developers {
            developer {
                id.set("emaarco")
                name.set("Marco Schaeck")
                url.set("https://github.com/emaarco")
                organization.set("Miragon")
                organizationUrl.set("https://miragon.io")
            }
        }
        scm {
            url.set("https://github.com/Miragon/bpmn-to-code")
            connection.set("scm:git:git://github.com/Miragon/bpmn-to-code.git")
            developerConnection.set("scm:git:ssh://git@github.com/Miragon/bpmn-to-code.git")
        }
    }
}
