package io.miragon.bpmn.adapter

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource
import java.io.File

class MavenMojoSmokeTest {

    @ParameterizedTest(name = "{0} / {1}")
    @CsvSource(
        "ZEEBE, KOTLIN, zeebe/bike-leasing.bpmn",
        "CAMUNDA_7, KOTLIN, c7/bike-leasing.bpmn",
        "OPERATON, KOTLIN, operaton/bike-leasing.bpmn",
        "ZEEBE, JAVA, zeebe/bike-leasing.bpmn",
        "ZEEBE, CSHARP, zeebe/bike-leasing.bpmn",
    )
    fun `mojo generates output files`(engine: String, language: String, bpmnFile: String, @TempDir projectDir: File) {
        // given: a temp project directory with a BPMN resource and a configured mojo
        val resourcesDir = File(projectDir, "src/main/resources").also { it.mkdirs() }
        val bpmnStream = requireNotNull(javaClass.classLoader.getResourceAsStream("bpmn/$bpmnFile"))
        File(resourcesDir, File(bpmnFile).name).writeBytes(bpmnStream.readBytes())
        val outputDir = File(projectDir, "build/generated")
        val mojo = BpmnModelMojo()
        setField(obj = mojo, name = "baseDir", value = projectDir.absolutePath)
        setField(obj = mojo, name = "filePattern", value = "src/main/resources/*.bpmn")
        setField(obj = mojo, name = "outputFolderPath", value = outputDir.absolutePath)
        setField(obj = mojo, name = "packagePath", value = "io.miragon.smoketest")
        setField(obj = mojo, name = "outputLanguage", value = language)
        setField(obj = mojo, name = "processEngine", value = engine)

        // when: executing the mojo
        mojo.execute()

        // then: only ProcessApi files are generated (shared types ship via runtime artifact)
        val packageDir = File(outputDir, "io/miragon/smoketest")
        assertThat(packageDir).isDirectory()
        val generatedFiles = requireNotNull(packageDir.listFiles())
        assertThat(generatedFiles).isNotEmpty()
        val expectedExt = when (language) {
            "KOTLIN" -> ".kt"
            "JAVA" -> ".java"
            else -> ".cs"
        }
        assertThat(generatedFiles).allSatisfy { file -> assertThat(file.isFile).isTrue() }
        assertThat(generatedFiles).allSatisfy { file -> assertThat(file.name).endsWith(expectedExt) }
    }

    @Test
    fun `mojo removes stale generated files and keeps hand-written ones`(@TempDir projectDir: File) {
        // given: a package folder holding a formerly generated file and a hand-written one
        val resourcesDir = File(projectDir, "src/main/resources").also { it.mkdirs() }
        val bpmnBytes = requireNotNull(javaClass.classLoader.getResourceAsStream("bpmn/zeebe/bike-leasing.bpmn")).readBytes()
        File(resourcesDir, "bike-leasing.bpmn").writeBytes(bpmnBytes)
        val outputDir = File(projectDir, "build/generated")
        val packageDir = File(outputDir, "io/miragon/smoketest").also { it.mkdirs() }
        val staleFile = File(packageDir, "RenamedProcessApi.java").also { it.writeText("// Generated by bpmn-to-code") }
        val handWrittenFile = File(packageDir, "HandWritten.java").also { it.writeText("package io.miragon.smoketest;") }
        val mojo = BpmnModelMojo()
        setField(obj = mojo, name = "baseDir", value = projectDir.absolutePath)
        setField(obj = mojo, name = "filePattern", value = "src/main/resources/*.bpmn")
        setField(obj = mojo, name = "outputFolderPath", value = outputDir.absolutePath)
        setField(obj = mojo, name = "packagePath", value = "io.miragon.smoketest")
        setField(obj = mojo, name = "outputLanguage", value = "JAVA")
        setField(obj = mojo, name = "processEngine", value = "ZEEBE")

        // when: executing the mojo
        mojo.execute()

        // then: only the file the generator owns and no longer produces is gone
        assertThat(staleFile).doesNotExist()
        assertThat(handWrittenFile).exists()
        assertThat(File(packageDir, "BikeLeasingProcessApi.java")).exists()
    }

    @Test
    fun `mojo rejects files sharing a process id that nothing tells apart`(@TempDir projectDir: File) {
        // given: the same process in two directories
        val bpmn = requireNotNull(javaClass.classLoader.getResourceAsStream("bpmn/zeebe/bike-leasing.bpmn")).readBytes().decodeToString()
        writeBpmn(projectDir = projectDir, path = "default/bike-leasing.bpmn", bpmn = bpmn)
        writeBpmn(projectDir = projectDir, path = "corporate/bike-leasing.bpmn", bpmn = bpmn)
        val mojo = modelMojo(projectDir)

        // when / then: the mojo fails naming the API, both files and the way to tell them apart
        assertThatThrownBy { mojo.execute() }
            .isInstanceOf(IllegalArgumentException::class.java)
            .hasMessageContaining("'BikeLeasingProcessApi'")
            .hasMessageContaining("corporate/bike-leasing.bpmn (process id 'bikeLeasing'), default/bike-leasing.bpmn (process id 'bikeLeasing')")
            .hasMessageContaining("variantName")
    }

    @Test
    fun `mojo generates an API per file once a variant name tells files sharing a process id apart`(@TempDir projectDir: File) {
        // given: the same process in two directories, one of the files declaring a variant name
        val bpmn = requireNotNull(javaClass.classLoader.getResourceAsStream("bpmn/zeebe/bike-leasing.bpmn")).readBytes().decodeToString()
        val variantProperty = """<zeebe:properties><zeebe:property name="variantName" value="corporate" /></zeebe:properties>"""
        val corporateBpmn = bpmn.replace(Regex("<bpmn:process [^>]*>")) { "${it.value}<bpmn:extensionElements>$variantProperty</bpmn:extensionElements>" }
        writeBpmn(projectDir = projectDir, path = "default/bike-leasing.bpmn", bpmn = bpmn)
        writeBpmn(projectDir = projectDir, path = "corporate/bike-leasing.bpmn", bpmn = corporateBpmn)
        val mojo = modelMojo(projectDir)

        // when: executing the mojo
        mojo.execute()

        // then: each file is generated as an API of its own
        val packageDir = File(projectDir, "build/generated/io/miragon/smoketest")
        assertThat(File(packageDir, "BikeLeasingProcessApi.kt")).exists()
        assertThat(File(packageDir, "CorporateBikeLeasingProcessApi.kt")).exists()
    }

    private fun writeBpmn(projectDir: File, path: String, bpmn: String) {
        val file = File(projectDir, "src/main/resources/$path")
        file.parentFile.mkdirs()
        file.writeText(bpmn)
    }

    private fun modelMojo(projectDir: File): BpmnModelMojo {
        val mojo = BpmnModelMojo()
        setField(obj = mojo, name = "baseDir", value = projectDir.absolutePath)
        setField(obj = mojo, name = "filePattern", value = "src/main/resources/**/*.bpmn")
        setField(obj = mojo, name = "outputFolderPath", value = File(projectDir, "build/generated").absolutePath)
        setField(obj = mojo, name = "packagePath", value = "io.miragon.smoketest")
        setField(obj = mojo, name = "outputLanguage", value = "KOTLIN")
        setField(obj = mojo, name = "processEngine", value = "ZEEBE")
        return mojo
    }
}
