// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.bpmn.testing.example

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnError
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.HasInner
import io.miragon.bpmn.runtime.InputOutputMapping
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.Navigable
import io.miragon.bpmn.runtime.NavigationScope
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.SignalName
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("newsletterSubscription")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val CALL_ACTIVITY_ABORT_REGISTRATION: ElementId =
        ElementId("CallActivity_AbortRegistration")

    val ACTIVITY_CONFIRM_REGISTRATION: ElementId = ElementId("Activity_ConfirmRegistration")

    val ACTIVITY_SEND_CONFIRMATION_MAIL: ElementId =
        ElementId("Activity_SendConfirmationMail")

    val ACTIVITY_SEND_WELCOME_MAIL: ElementId = ElementId("Activity_SendWelcomeMail")

    val ACTIVITY_NOTIFY_COMMUNITY: ElementId = ElementId("Activity_NotifyCommunity")

    val GATEWAY_SPLIT_NOTIFICATIONS: ElementId = ElementId("Gateway_SplitNotifications")

    val GATEWAY_JOIN_NOTIFICATIONS: ElementId = ElementId("Gateway_JoinNotifications")

    val COMPENSATION_END_EVENT_REGISTRATION_ABORTED: ElementId =
        ElementId("CompensationEndEvent_RegistrationAborted")

    val COMPENSATION_EVENT_ON_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("CompensationEvent_OnSubscriptionCounter")

    val COMPENSATION_TASK_DECREMENT_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("CompensationTask_DecrementSubscriptionCounter")

    val END_EVENT_REGISTRATION_COMPLETED: ElementId =
        ElementId("EndEvent_RegistrationCompleted")

    val END_EVENT_REGISTRATION_NOT_POSSIBLE: ElementId =
        ElementId("EndEvent_RegistrationNotPossible")

    val END_EVENT_SUBSCRIPTION_CONFIRMED: ElementId =
        ElementId("EndEvent_SubscriptionConfirmed")

    val ERROR_EVENT_INVALID_MAIL: ElementId = ElementId("ErrorEvent_InvalidMail")

    val SERVICE_TASK_INCREMENT_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("serviceTask_incrementSubscriptionCounter")

    val START_EVENT_REQUEST_RECEIVED: ElementId = ElementId("StartEvent_RequestReceived")

    val START_EVENT_SUBMIT_REGISTRATION_FORM: ElementId =
        ElementId("StartEvent_SubmitRegistrationForm")

    val SUB_PROCESS_CONFIRMATION: ElementId = ElementId("SubProcess_Confirmation")

    val TIMER_AFTER_3_DAYS: ElementId = ElementId("Timer_After3Days")

    val TIMER_EVERY_DAY: ElementId = ElementId("Timer_EveryDay")
  }

  /**
   * Call activities grouped by element. Each nested object exposes the called `PROCESS_ID` plus the variable mappings passed into (`Inputs`) and returned from (`Outputs`) the called process.
   */
  object CallActivities {
    object CallActivityAbortRegistration {
      val PROCESS_ID: ProcessId = ProcessId("abort-registration")

      object Inputs {
        val CHILD_REASON_CODE: InputOutputMapping =
            InputOutputMapping(target = "childReasonCode", sourceExpression = $$"""${reasonCode}""")

        val CHILD_SUBSCRIPTION_ID: InputOutputMapping =
            InputOutputMapping(target = "childSubscriptionId", source = "subscriptionId")
      }

      object Outputs {
        val ABORT_RESULT: InputOutputMapping =
            InputOutputMapping(target = "abortResult", source = "childAbortResult")
      }
    }
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  object Messages {
    val MESSAGE_FORM_SUBMITTED: MessageName = MessageName("Message_FormSubmitted")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val NEWSLETTER_SEND_CONFIRMATION_MAIL: String = "#{newsletterSendConfirmationMail}"

    const val NEWSLETTER_SEND_WELCOME_MAIL: String = $$"""${newsletterSendWelcomeMail}"""

    const val COUNTER_CLASS: String = "counterClass"

    const val NEWSLETTER_NOTIFY_COMMUNITY: String = "newsletter.notifyCommunity"

    const val NEWSLETTER_REGISTRATION_COMPLETED: String = "newsletter.registrationCompleted"
  }

  object Timers {
    val TIMER_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", $$"""${testVariable}""")

    val TIMER_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")
  }

  object Errors {
    val ERROR_INVALID_MAIL: BpmnError = BpmnError("Error_InvalidMail", "500")
  }

  object Compensations {
    val COMPENSATION_END_EVENT_REGISTRATION_ABORTED: ElementId =
        ElementId("CompensationEndEvent_RegistrationAborted")

    val COMPENSATION_EVENT_ON_SUBSCRIPTION_COUNTER: ElementId =
        ElementId("CompensationEvent_OnSubscriptionCounter")
  }

  object Signals {
    val SIGNAL_REGISTRATION_NOT_POSSIBLE: SignalName =
        SignalName("Signal_RegistrationNotPossible")
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object ActivitySendConfirmationMail {
      val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")

      val TEST_VARIABLE: VariableName.Input = VariableName.Input("testVariable")
    }

    object ActivitySendWelcomeMail {
      val SUBSCRIPTION_ID: VariableName.InOut = VariableName.InOut("subscriptionId")
    }

    object CallActivityAbortRegistration {
      val SUBSCRIPTION_ID: VariableName.Input = VariableName.Input("subscriptionId")
    }

    object EndEventRegistrationCompleted {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventRequestReceived {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }

    object StartEventSubmitRegistrationForm {
      val SUBSCRIPTION_ID: VariableName.Output = VariableName.Output("subscriptionId")
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_05_I_3_X_1_Y: BpmnFlow = BpmnFlow(
          id = "Flow_05i3x1y",
          sourceRef = "StartEvent_RequestReceived",
          targetRef = "Activity_SendConfirmationMail",
        )

    val FLOW_09_CUVZP: BpmnFlow = BpmnFlow(
          id = "Flow_09cuvzp",
          sourceRef = "SubProcess_Confirmation",
          targetRef = "Gateway_SplitNotifications",
        )

    val FLOW_0_I_2_CTUV: BpmnFlow = BpmnFlow(
          id = "Flow_0i2ctuv",
          sourceRef = "ErrorEvent_InvalidMail",
          targetRef = "EndEvent_RegistrationNotPossible",
        )

    val FLOW_0_X_4_EWVB: BpmnFlow = BpmnFlow(
          id = "Flow_0x4ewvb",
          sourceRef = "Timer_EveryDay",
          targetRef = "Activity_SendConfirmationMail",
        )

    val FLOW_0_ZDMT_0_T: BpmnFlow = BpmnFlow(
          id = "Flow_0zdmt0t",
          sourceRef = "serviceTask_incrementSubscriptionCounter",
          targetRef = "SubProcess_Confirmation",
        )

    val FLOW_16_HUB_0_N: BpmnFlow = BpmnFlow(
          id = "Flow_16hub0n",
          sourceRef = "Gateway_SplitNotifications",
          targetRef = "Activity_SendWelcomeMail",
        )

    val FLOW_1862_JD_8: BpmnFlow = BpmnFlow(
          id = "Flow_1862jd8",
          sourceRef = "Gateway_JoinNotifications",
          targetRef = "EndEvent_RegistrationCompleted",
        )

    val FLOW_1_BCKM_43: BpmnFlow = BpmnFlow(
          id = "Flow_1bckm43",
          sourceRef = "Activity_SendConfirmationMail",
          targetRef = "Activity_ConfirmRegistration",
        )

    val FLOW_1_BSB_8_NO: BpmnFlow = BpmnFlow(
          id = "Flow_1bsb8no",
          sourceRef = "CallActivity_AbortRegistration",
          targetRef = "CompensationEndEvent_RegistrationAborted",
        )

    val FLOW_1_CPWE_57: BpmnFlow = BpmnFlow(
          id = "Flow_1cpwe57",
          sourceRef = "Activity_ConfirmRegistration",
          targetRef = "EndEvent_SubscriptionConfirmed",
        )

    val FLOW_1_CSFYYZ: BpmnFlow = BpmnFlow(
          id = "Flow_1csfyyz",
          sourceRef = "StartEvent_SubmitRegistrationForm",
          targetRef = "serviceTask_incrementSubscriptionCounter",
        )

    val FLOW_1_DUWY_83: BpmnFlow = BpmnFlow(
          id = "Flow_1duwy83",
          sourceRef = "Activity_NotifyCommunity",
          targetRef = "Gateway_JoinNotifications",
        )

    val FLOW_1_I_7_HJID: BpmnFlow = BpmnFlow(
          id = "Flow_1i7hjid",
          sourceRef = "Activity_SendWelcomeMail",
          targetRef = "Gateway_JoinNotifications",
        )

    val FLOW_1_L_1_LJ_4_M: BpmnFlow = BpmnFlow(
          id = "Flow_1l1lj4m",
          sourceRef = "Timer_After3Days",
          targetRef = "CallActivity_AbortRegistration",
        )

    val FLOW_1_P_5_T_47_Z: BpmnFlow = BpmnFlow(
          id = "Flow_1p5t47z",
          sourceRef = "Gateway_SplitNotifications",
          targetRef = "Activity_NotifyCommunity",
        )
  }

  /**
   * Typed navigation over the process flow.
   * Each element is a node exposing its `id`, `elementType` and display `name`, plus the elements reachable from it as named properties — so a full path is verified by the compiler and offered by autocomplete. A subprocess's interior is its nested `Inner` scope.
   * Intended for tooling, tests, and reasoning about the process shape.
   */
  object Relations {
    val activityNotifyCommunity: ActivityNotifyCommunity
      get() = ActivityNotifyCommunity

    val activitySendWelcomeMail: ActivitySendWelcomeMail
      get() = ActivitySendWelcomeMail

    val callActivityAbortRegistration: CallActivityAbortRegistration
      get() = CallActivityAbortRegistration

    val compensationEndEventRegistrationAborted: CompensationEndEventRegistrationAborted
      get() = CompensationEndEventRegistrationAborted

    val compensationEventOnSubscriptionCounter: CompensationEventOnSubscriptionCounter
      get() = CompensationEventOnSubscriptionCounter

    val compensationTaskDecrementSubscriptionCounter:
        CompensationTaskDecrementSubscriptionCounter
      get() = CompensationTaskDecrementSubscriptionCounter

    val endEventRegistrationCompleted: EndEventRegistrationCompleted
      get() = EndEventRegistrationCompleted

    val endEventRegistrationNotPossible: EndEventRegistrationNotPossible
      get() = EndEventRegistrationNotPossible

    val errorEventInvalidMail: ErrorEventInvalidMail
      get() = ErrorEventInvalidMail

    val gatewayJoinNotifications: GatewayJoinNotifications
      get() = GatewayJoinNotifications

    val gatewaySplitNotifications: GatewaySplitNotifications
      get() = GatewaySplitNotifications

    val serviceTaskIncrementSubscriptionCounter: ServiceTaskIncrementSubscriptionCounter
      get() = ServiceTaskIncrementSubscriptionCounter

    val startEventSubmitRegistrationForm: StartEventSubmitRegistrationForm
      get() = StartEventSubmitRegistrationForm

    val subProcessConfirmation: SubProcessConfirmation
      get() = SubProcessConfirmation

    val timerAfter3Days: TimerAfter3Days
      get() = TimerAfter3Days

    fun then(): Next = Next

    object Next {
      val startEventSubmitRegistrationForm: StartEventSubmitRegistrationForm
        get() = StartEventSubmitRegistrationForm
    }

    object ActivityNotifyCommunity : AbstractFlowNode(ElementId("Activity_NotifyCommunity"), "SERVICE_TASK"),
        Navigable<ActivityNotifyCommunity.Next> {
      override fun then(): Next = Next

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }
    }

    object ActivitySendWelcomeMail : AbstractFlowNode(ElementId("Activity_SendWelcomeMail"), "SERVICE_TASK"),
        Navigable<ActivitySendWelcomeMail.Next> {
      override fun then(): Next = Next

      object Next {
        val gatewayJoinNotifications: GatewayJoinNotifications
          get() = GatewayJoinNotifications
      }
    }

    object CallActivityAbortRegistration : AbstractFlowNode(ElementId("CallActivity_AbortRegistration"), "CALL_ACTIVITY"),
        Navigable<CallActivityAbortRegistration.Next> {
      val calledProcess: ProcessId = ProcessId("abort-registration")

      override fun then(): Next = Next

      object Next {
        val compensationEndEventRegistrationAborted: CompensationEndEventRegistrationAborted
          get() = CompensationEndEventRegistrationAborted
      }
    }

    object CompensationEndEventRegistrationAborted : AbstractFlowNode(ElementId("CompensationEndEvent_RegistrationAborted"), "COMPENSATION_END_EVENT")

    object CompensationEventOnSubscriptionCounter : AbstractFlowNode(ElementId("CompensationEvent_OnSubscriptionCounter"), "COMPENSATION_BOUNDARY_EVENT")

    object CompensationTaskDecrementSubscriptionCounter : AbstractFlowNode(ElementId("CompensationTask_DecrementSubscriptionCounter"), "TASK")

    object EndEventRegistrationCompleted : AbstractFlowNode(ElementId("EndEvent_RegistrationCompleted"), "END_EVENT")

    object EndEventRegistrationNotPossible : AbstractFlowNode(ElementId("EndEvent_RegistrationNotPossible"), "SIGNAL_END_EVENT")

    object ErrorEventInvalidMail : AbstractFlowNode(ElementId("ErrorEvent_InvalidMail"), "ERROR_BOUNDARY_EVENT"),
        Navigable<ErrorEventInvalidMail.Next> {
      override fun then(): Next = Next

      object Next {
        val endEventRegistrationNotPossible: EndEventRegistrationNotPossible
          get() = EndEventRegistrationNotPossible
      }
    }

    object GatewayJoinNotifications : AbstractFlowNode(ElementId("Gateway_JoinNotifications"), "PARALLEL_GATEWAY"),
        Navigable<GatewayJoinNotifications.Next> {
      override fun then(): Next = Next

      object Next {
        val endEventRegistrationCompleted: EndEventRegistrationCompleted
          get() = EndEventRegistrationCompleted
      }
    }

    object GatewaySplitNotifications : AbstractFlowNode(ElementId("Gateway_SplitNotifications"), "PARALLEL_GATEWAY"),
        Navigable<GatewaySplitNotifications.Next> {
      override fun then(): Next = Next

      object Next {
        val activityNotifyCommunity: ActivityNotifyCommunity
          get() = ActivityNotifyCommunity

        val activitySendWelcomeMail: ActivitySendWelcomeMail
          get() = ActivitySendWelcomeMail
      }
    }

    object ServiceTaskIncrementSubscriptionCounter : AbstractFlowNode(ElementId("serviceTask_incrementSubscriptionCounter"), "SERVICE_TASK"),
        Navigable<ServiceTaskIncrementSubscriptionCounter.Next> {
      override fun then(): Next = Next

      object Next {
        val compensationEventOnSubscriptionCounter: CompensationEventOnSubscriptionCounter
          get() = CompensationEventOnSubscriptionCounter

        val subProcessConfirmation: SubProcessConfirmation
          get() = SubProcessConfirmation
      }
    }

    object StartEventSubmitRegistrationForm : AbstractFlowNode(ElementId("StartEvent_SubmitRegistrationForm"), "MESSAGE_START_EVENT"),
        Navigable<StartEventSubmitRegistrationForm.Next> {
      override fun then(): Next = Next

      object Next {
        val serviceTaskIncrementSubscriptionCounter: ServiceTaskIncrementSubscriptionCounter
          get() = ServiceTaskIncrementSubscriptionCounter
      }
    }

    object SubProcessConfirmation : AbstractFlowNode(ElementId("SubProcess_Confirmation"), "SUB_PROCESS"),
        Navigable<SubProcessConfirmation.Next>, HasInner<SubProcessConfirmation.Inner> {
      override fun then(): Next = Next

      override fun `inner`(): SubProcessConfirmation.Inner = SubProcessConfirmation.Inner

      object Next {
        val errorEventInvalidMail: ErrorEventInvalidMail
          get() = ErrorEventInvalidMail

        val gatewaySplitNotifications: GatewaySplitNotifications
          get() = GatewaySplitNotifications

        val timerAfter3Days: TimerAfter3Days
          get() = TimerAfter3Days
      }

      object Inner : NavigationScope<SubProcessConfirmation.Inner.Next> {
        val activityConfirmRegistration: ActivityConfirmRegistration
          get() = ActivityConfirmRegistration

        val activitySendConfirmationMail: ActivitySendConfirmationMail
          get() = ActivitySendConfirmationMail

        val endEventSubscriptionConfirmed: EndEventSubscriptionConfirmed
          get() = EndEventSubscriptionConfirmed

        val startEventRequestReceived: StartEventRequestReceived
          get() = StartEventRequestReceived

        val timerEveryDay: TimerEveryDay
          get() = TimerEveryDay

        override fun then(): Next = Next

        object Next {
          val startEventRequestReceived: StartEventRequestReceived
            get() = StartEventRequestReceived
        }

        object ActivityConfirmRegistration : AbstractFlowNode(ElementId("Activity_ConfirmRegistration"), "RECEIVE_TASK"),
            Navigable<ActivityConfirmRegistration.Next> {
          val name: String = "Confirm registration"

          override fun then(): Next = Next

          object Next {
            val endEventSubscriptionConfirmed: EndEventSubscriptionConfirmed
              get() = EndEventSubscriptionConfirmed

            val timerEveryDay: TimerEveryDay
              get() = TimerEveryDay
          }
        }

        object ActivitySendConfirmationMail : AbstractFlowNode(ElementId("Activity_SendConfirmationMail"), "SERVICE_TASK"),
            Navigable<ActivitySendConfirmationMail.Next> {
          override fun then(): Next = Next

          object Next {
            val activityConfirmRegistration: ActivityConfirmRegistration
              get() = ActivityConfirmRegistration
          }
        }

        object EndEventSubscriptionConfirmed : AbstractFlowNode(ElementId("EndEvent_SubscriptionConfirmed"), "END_EVENT")

        object StartEventRequestReceived : AbstractFlowNode(ElementId("StartEvent_RequestReceived"), "START_EVENT"),
            Navigable<StartEventRequestReceived.Next> {
          override fun then(): Next = Next

          object Next {
            val activitySendConfirmationMail: ActivitySendConfirmationMail
              get() = ActivitySendConfirmationMail
          }
        }

        object TimerEveryDay : AbstractFlowNode(ElementId("Timer_EveryDay"), "TIMER_BOUNDARY_EVENT"),
            Navigable<TimerEveryDay.Next> {
          override fun then(): Next = Next

          object Next {
            val activitySendConfirmationMail: ActivitySendConfirmationMail
              get() = ActivitySendConfirmationMail
          }
        }
      }
    }

    object TimerAfter3Days : AbstractFlowNode(ElementId("Timer_After3Days"), "TIMER_BOUNDARY_EVENT"),
        Navigable<TimerAfter3Days.Next> {
      override fun then(): Next = Next

      object Next {
        val callActivityAbortRegistration: CallActivityAbortRegistration
          get() = CallActivityAbortRegistration
      }
    }
  }
}
