package io.miragon.bpmn.adapter.outbound.codegen

import io.miragon.bpmn.adapter.outbound.codegen.builder.CSharpProcessApiBuilder
import io.miragon.bpmn.adapter.outbound.codegen.builder.CSharpSharedDefinitionsBuilder
import io.miragon.bpmn.adapter.outbound.codegen.builder.JavaProcessApiBuilder
import io.miragon.bpmn.adapter.outbound.codegen.builder.JavaSharedDefinitionsBuilder
import io.miragon.bpmn.adapter.outbound.codegen.builder.KotlinProcessApiBuilder
import io.miragon.bpmn.adapter.outbound.codegen.builder.KotlinSharedDefinitionsBuilder
import io.miragon.bpmn.application.port.outbound.GenerateApiCodePort
import io.miragon.bpmn.domain.BpmnModelApi
import io.miragon.bpmn.domain.GeneratedApiFile
import io.miragon.bpmn.domain.SharedDefinitionsApi
import io.miragon.bpmn.domain.shared.OutputLanguage

internal class CodeGenerationAdapter(
    private val processApiBuilders: Map<OutputLanguage, AbstractProcessApiBuilder<*>> = Companion.processApiBuilders,
    private val sharedDefinitionsBuilders: Map<OutputLanguage, AbstractSharedDefinitionsBuilder> = Companion.sharedDefinitionsBuilders,
) : GenerateApiCodePort {

    override fun generateCode(modelApi: BpmnModelApi): List<GeneratedApiFile> {
        val language = modelApi.outputLanguage
        val processApiBuilder = processApiBuilders[language] ?: throw IllegalArgumentException("$language is not supported")
        val processFile = processApiBuilder.buildApiFile(modelApi)
        return listOf(processFile)
    }

    override fun generateSharedCode(api: SharedDefinitionsApi): List<GeneratedApiFile> {
        val language = api.outputLanguage
        val sharedDefinitionsBuilder = sharedDefinitionsBuilders[language] ?: throw IllegalArgumentException("$language is not supported")
        return sharedDefinitionsBuilder.buildApiFiles(api)
    }

    abstract class AbstractProcessApiBuilder<MainBuilder : Any> {
        abstract fun buildApiFile(modelApi: BpmnModelApi): GeneratedApiFile
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    abstract class AbstractSharedDefinitionsBuilder {
        abstract fun buildApiFiles(api: SharedDefinitionsApi): List<GeneratedApiFile>
        protected val autoGenComment = "Generated by bpmn-to-code"
    }

    companion object {
        val processApiBuilders = mapOf(
            OutputLanguage.KOTLIN to KotlinProcessApiBuilder(),
            OutputLanguage.JAVA to JavaProcessApiBuilder(),
            OutputLanguage.CSHARP to CSharpProcessApiBuilder(),
        )
        val sharedDefinitionsBuilders = mapOf(
            OutputLanguage.KOTLIN to KotlinSharedDefinitionsBuilder(),
            OutputLanguage.JAVA to JavaSharedDefinitionsBuilder(),
            OutputLanguage.CSHARP to CSharpSharedDefinitionsBuilder(),
        )
    }
}
