package io.miragon.bpmn.adapter.outbound.codegen

/**
 * What every generated source file says about itself, whatever its language.
 */
internal object GeneratedFileHeader {

    const val COMMENT = "Generated by bpmn-to-code"
}
